### ISSUE TITLE
Slack Invite links inactive

### ISSUE THREAD

**Issue by DaltonSW** [PokeAPI/pokeapi#1002]
Seems like all of the Slack invite links are invalid presently. 

![image](https://github.com/PokeAPI/pokeapi/assets/33884368/c2f965df-45bd-4e0b-bca7-2b27abd4ce95)
![image](https://github.com/PokeAPI/pokeapi/assets/33884368/685f101b-ced6-45bb-9052-af73379d5518)

**Comment by Naramsim** [comment]
Thanks for reporting! We'll look into it

**Comment by Naramsim** [comment]
Hi, I created a new link and deployed a new version, will be up in ~10 mins. Can you check if you can use it?
