### ISSUE TITLE
GraphQL: Is dual type of X and Y

### ISSUE THREAD

**Issue by alexanderjophus** [PokeAPI/pokeapi#1023]
Hey,

Not sure what to make the title. The problem I have is this, I'm using the graphql endpoint, I want to list all pokemon who are type "grass" and "poison".

I'm trying something like this:
```graphql
query Finder {
  pokemon_v2_pokemon(
    where: {
      pokemon_v2_pokemontypes: {
        pokemon_v2_type: {
          name: { _in: ["grass", "poison"] }
        }
      }
    }
  ) {
    name
    pokemon_v2_pokemontypes {
      pokemon_v2_type {
        name
      }
    }
  }
}
```

However, as the pokemon type is a list of types, this matches anything that is poison _or_ grass, not poison _and_ grass. Is there a way to achieve what I need currently? I've tried a couple different methods, but nothing fruitful so far.

**Comment by Naramsim** [comment]
Check the example: https://github.com/PokeAPI/pokeapi/blob/master/graphql/examples/best_poison_grass_pokemon.gql

**Comment by alexanderjophus** [comment]
Ah, I was close. Thank you, I'll close this now.
