### ISSUE TITLE
Zygarde PokeDex id is incorrect

### ISSUE THREAD

**Issue by ModBoyex** [PokeAPI/pokeapi#1033]
I look on the pokeapi.co website itself, and found that when looking at the pokemon "pokemon/Zygarde-10", the id = 10181, and that ID is way out of bounds what id's you can search with the API? I may be missing something, but this does not seem right. I came across this problem when using the API through python, but found that the problem still exists on the website as well.
Steps to Reproduce:

1. go to the Poke API
2. search for pokemon/zygarde-10

**Comment by GreatNovaDragon** [comment]
forms get an extra out of bounds id, if you were to seek for the actual baseform, zygarde-50 you would get the natdex number, but due to how pokeapi works this is incidental

**Comment by Naramsim** [comment]
Yes, that's the intended way. We have some pokemons with ID>10000
