### ISSUE TITLE
GraphQL api is down

### ISSUE THREAD

**Issue by blevy115** [PokeAPI/pokeapi#1039]
Steps to Reproduce:

1. Attempt to make any request using the graphql console here https://beta.pokeapi.co/graphql/console/
2. Server sends back a Cloudflare 504 Gateway Timeout error

**Comment by Naramsim** [comment]
Thanks for pointing it out. The usual midnight reboot should fix the machine. Let's wait until tomorrow (UST) and check again.

**Comment by blevy115** [comment]
Still down

**Comment by blevy115** [comment]
Working now
