### ISSUE TITLE
Add pokemon cries to GraphqQL response

### ISSUE THREAD

**Issue by blevy115** [PokeAPI/pokeapi#1040]
With cries added to the pokemon model, it should also be available in the pokemon_v2_pokemon graphql object.  NOt sure if this has been done but could not figure out the object structure needed here: https://beta.pokeapi.co/graphql/console/  to return the cry 'ogg' file

**Comment by Naramsim** [comment]
Hi! I fixed the issue. I forgot to track the table on hasura. 

Now you should be able to query it
