### ISSUE TITLE
Pokemons rename in species request

### ISSUE THREAD

**Issue by aristofany-herderson** [PokeAPI/pokeapi#1045]
The names of the pokemons are different, taking into account the urls `https://pokeapi.co/api/v2/pokemon/{name}` and `https://pokeapi.co/api/v2/pokemon-species/{name}`, generating errors.

For example, in the `https://pokeapi.co/api/v2/pokemon/892` request, the name of the pokemon is **urshifu-single-strike**, however in the `https://pokeapi.co/api/v2/pokemon-species/892` request, the name is **urshifu**, generating an error, if the request is made by name.

**Comment by GreatNovaDragon** [comment]
Intended, species and pokemon are different things. Yeah, i also think its stupid. I talk bout that in #1037

species is telling you everything you find under an natdex number, while pokemon are just specific forms of a pokemon, the numeric request being the first form under the natdex number.

**Comment by Naramsim** [comment]
closing this since it's the intended way, as of now
