### ISSUE TITLE
Eevee's gender differences

### ISSUE THREAD

**Issue by OriolRV** [PokeAPI/pokeapi#1051]
Hi everyone! First time doing a GitHub issue, I hope I do everything right and that this is the correct place for this. I was playing around with the API and noticed that [Eevee](https://pokeapi.co/api/v2/pokemon-species/133) is noted as not having gender differences ("has_gender_differences":false). I know this started to apply to all Eevee from generation VIII onwards, but gender differences for Pokemon from generations I-III also started appearing later, in generation IV, so I think Eevee should be fixed.

Thanks!

**Comment by Naramsim** [comment]
Hi, we currently support only the latest data. We tried to address past values with changelog tables but the scope is limited. Currently, we cannot provide a way to reliably query past data.

**Comment by OriolRV** [comment]
Hi, yes, that's my point, that currently Eevee has a gender difference and thus it should be reflected in the API. The rest of my explanation on generations I-III Pokémon was just a justification of that.

**Comment by Naramsim** [comment]
Ah, got it! Can you try and fix that? You should update the relative CSV file

**Comment by SKCwillie** [comment]
@OriolRV thanks for reporting this!

Please continue to report these issues if you find any.

**Comment by OriolRV** [comment]
Thanks and sorry, I've been busy these days. If I find anything else, I'll let you know. Cheers!
