### ISSUE TITLE
Brambleghast missing Egg moves

### ISSUE THREAD

**Issue by Phyore** [PokeAPI/pokeapi#1055]
Looks like this Pokemon is missing their moves such as strength sap according to https://www.serebii.net/pokedex-sv/brambleghast/ - Unsure if there are other Pokemon missing egg moves

**Comment by Naramsim** [comment]
Hi! Could you help us fill in the missing info?

**Comment by Phyore** [comment]
> Hi! Could you help us fill in the missing info?

I can do that if pointed at the right location for it :)

**Comment by Naramsim** [comment]
Hi, this file contains all the moves and their _learn method_: https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv/pokemon_moves.csv

You should add new lines for the move that can be learned as an _egg_(pokemon_move_method_id). The identifier for the _egg_ method is `2`, as described here: https://github.com/PokeAPI/pokeapi/blob/master/data/v2/csv/pokemon_move_methods.csv . You can use `0` as `level`

**Comment by Phyore** [comment]
Pull request submitted: https://github.com/PokeAPI/pokeapi/pull/1133
