### ISSUE TITLE
Egg Cycles

### ISSUE THREAD

**Issue by CalvinaHarr** [PokeAPI/pokeapi#1057]
Hey,
When looking into the Pokémon-species page, there's no egg cycle feature. If it's already been added, where would I find it?

**Comment by Naramsim** [comment]
most probably there's no such data here

**Comment by Naramsim** [comment]
Hi! I correct myself, it seems we offer that kind of data: https://pokeapi.co/docs/v2#pokemon-species

It's tight to the pokemon species of a pokemon. It's the property `hatch_counter`. [Here](https://pokeapi.co/api/v2/pokemon-species/ditto) Ditto has it set to `20`.

The description of the property in our API says as follows

> Initial hatch counter: one must walk 255 × (hatch_counter + 1) steps before this Pokémon's egg hatches, unless utilizing bonuses like Flame Body's.

**Comment by CalvinaHarr** [comment]
Okay, thank you so much!
