### ISSUE TITLE
Maximum and Minimum of Stats 

### ISSUE THREAD

**Issue by PowerLevel9000** [PokeAPI/pokeapi#1058]
# Maximum and Minimum of Stats 

[stats](https://pokeapi.co/api/v2/stat/)
It would be helpful to have the maximum value for any stat, such as HP, weight, height, attack, and defense ...., for making accurate comparisons between Pokémon.

# Happy Developing 
![ConfusedGIF](https://github.com/PokeAPI/pokeapi/assets/116451144/0a33775d-2a27-458e-907a-aadbc8c5be66)

**Comment by EKO-GITHUB** [comment]
@Naramsim  what he probably means is the maximum and minimum base stat value at level 100.
max-EV = 31 stat points
max-IV = 63 stat points
beneficial nature = +10%
negative nature = -10%

non-HP base stat min-max can be calculated from:
min: (2 * stat_value+ 5 (static for non-HP stats) ) * negative nature
max: (2 * stat_value + max-EV + max-IV + 5) * beneficial nature 

HP min-max:
min: 2 * hp_value + 110 (static for HP)
max: 2 * hp_value + 110 + max-EV + max-IV

It's not necessary to expose this data to the client as the client can simply calculate it themselves, at least that's what I've done.

**Comment by Naramsim** [comment]
Oh, ok, I thought those numbers were a bit difficult to calculate. Anyways, thanks for coming up with the math, I'm closing this and your comment will be the reference.
