### ISSUE TITLE
Vivillon Icy Snow Image Incorrect

### ISSUE THREAD

**Issue by JRuffs7** [PokeAPI/pokeapi#1067]
When pulling data for the Vivillon forms, I noticed that the default form image for Vivillon (666) was the **Meadow** form. However, when going into the data call, it was specifying the _666-meadow.png_ image and was not specified as the default form (is_default: false).

When I grabbed the data for the **Icy Snow** form, this did not specify form within the image and just used _666.png_ image. This form was listed as the default (is_default: true). The default _666.png_ image is also the **Meadow** form, which is incorrect for the call being made.

Steps to Reproduce:

1. Access these two API calls:
- https://pokeapi.co/api/v2/pokemon-form/666 (Meadow, default pokemon ID)
- https://pokeapi.co/api/v2/pokemon-form/10086 (Icy Snow, specific form ID)
2. Look into the sprites for each form:
- Meadow Form page will have https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/666-meadow.png
- Icy Snow Form page will have https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/666.png
3. Both of these images are the same, therefore giving the Icy Snow form the incorrect image

Possible Solutions:
- There is an available https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/666-icy-snow.png image to use, it is just not referenced anywhere. This would need to be changed for each kind of image display (HOME, Official, etc.) that is attached to both the pokemon and pokemon-form endpoints.
- The default https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/666.png should be changed the Icy Snow form image. However, this would be a widespread change as there are many images for each kind of image display (HOME, Official, etc.)

**Comment by Naramsim** [comment]
Hi, could you submit a PR fixing this? About the possible two options, I'd go with the easiest one in terms of efforts as of now

**Comment by Deleca7755** [comment]
Wouldn't the solution here ( solution 1 more like ) be just setting the `is_default` on form 666 to be `true` Instead of on form 10086? Otherwise, If It's not like that within code, then the Images would have to be swapped around accordingly to this
