### ISSUE TITLE
Missing Alcremie Forms and Images

### ISSUE THREAD

**Issue by JRuffs7** [PokeAPI/pokeapi#1069]
The base Alcremie API (https://pokeapi.co/api/v2/pokemon/869) has links to all the different **cream** forms, but there is no link to any different **sweet** versions of the form.

Example:
- The base form of Alcremie is [Vanilla Cream Strawberry Sweet](https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/869.png) 
- Another version of Alcremie is [Vanilla Cream Star Sweet](https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/869-vanilla-cream-star-sweet.png), however this version is not referenced within the main Alcremie API

The base API does point to the other cream versions such as [Mint Cream](https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/869-mint-cream-strawberry-sweet.png), but these do not have their own images within the pokemon-form api pages.

The only images reference when it comes to Alcremie is the base Vanilla/Strawberry form. There are only references to the cream forms (with no images) and no references to any of the other sweet forms. There are a total of 63 forms, but only 9 Alcremie form pages within the API (unless they are under another ID that is not referenced within the base API page).

**Comment by Naramsim** [comment]
Hi sorry for the late late late reply! Anyways, if you have some spare time you could add the data and the sprites for Alcremie.

**Comment by Deleca7755** [comment]
If new forms are added do we bump up the `order` of forms listed after In the csv?
