### ISSUE TITLE
The API description doesnt document the Colour field in the name DataType

### ISSUE THREAD

**Issue by GreatNovaDragon** [PokeAPI/pokeapi#1074]
Apparently Contest Types have a colour. The csv tables and the request do tell us that under the Name Response... now, well... if you go to the readme of pokemon_v2 and seek the Name DataType... there is no Colour.

Makes Colour an undocumented Field.

**Comment by Naramsim** [comment]
The readme of pokeapi_v2 isn't maintained.

The info is present at: https://pokeapi.co/docs/v2#contest-types

**Comment by GreatNovaDragon** [comment]
I'll close, with the comment that the readme at that place should be deleted then
