### ISSUE TITLE
Linking cord from PLA.

### ISSUE THREAD

**Issue by jigokusaru** [PokeAPI/pokeapi#1082]
Hi, I didn't see the Linking Cord from PLA in the items. I tried searching for it a few ways and did not find it. Could this be added My discord bot is going to require that item in the list. I assume it would be an evolution item.

**Comment by jigokusaru** [comment]
No clue how. Still figuring out Github for myself.

**Comment by GreatNovaDragon** [comment]
gimme a sec.

**Comment by jigokusaru** [comment]
by all means, take your time. I see a lot of new items that need info. If I figure out how to add things myself, I'll update them, I see things like Peat-block has no details so I'll try to figure things out to help out.

**Comment by GreatNovaDragon** [comment]
Basically anything from sword and shield till now has no info. More volunteers would be great.

**Comment by jigokusaru** [comment]
I will see what I can do. not sure how to update anything myself.

**Comment by Naramsim** [comment]
Thanks a lot @GreatNovaDragon 

@jigokusaru basically to modify the API data we need to change some CSV files. Take a look at the changes made here: https://github.com/PokeAPI/pokeapi/pull/1083/files

**Comment by jigokusaru** [comment]
Thanks. that does make since.
