### ISSUE TITLE
Missing version names for the gen 9 dlcs

### ISSUE THREAD

**Issue by GamiloFR** [PokeAPI/pokeapi#1107]
I noticed that the version names of the gen 9 dlcs (_the-teal-mask_ and _the-indigo-disk_) are missing in most languages .

I didn't see any issues related to this, so I took the liberty of opening a pull request : https://github.com/PokeAPI/pokeapi/pull/1106.

> I'm sorry if I was too fast at opening the PR, I didn't catch the sentence _"Please see the [issues on GitHub](https://github.com/PokeAPI/pokeapi/issues) before you submit a pull request or raise an issue, someone else might have beat you to it."_ in the guidelines

**Comment by Naramsim** [comment]
Thanks!
