### ISSUE TITLE
Ability by effects

### ISSUE THREAD

**Issue by blevy115** [PokeAPI/pokeapi#1108]
Hi, was just wondering if it's possible to get a list of abilities by effect, similar to https://bulbapedia.bulbagarden.net/wiki/Category:Abilities_by_effect

**Comment by Naramsim** [comment]
Most probably you can by using graphql

**Comment by blevy115** [comment]
Any idea on what that query would look like, i tried looking in the graphql console but couldn't find those data points

**Comment by Naramsim** [comment]
hi, I checked the data and it's not there. So it's not possible
