### ISSUE TITLE
CORS error after few days

### ISSUE THREAD

**Issue by emirhanyagci** [PokeAPI/pokeapi#1111]
I finished project it was working , after couple days i checked project for is everything ok ? but i get this error, when i try request from postman api working but in my deployment does not .
btw i checked https://github.com/PokeAPI/pokeapi/issues/289 not helpful

![image](https://github.com/PokeAPI/pokeapi/assets/66957950/5f4b63b6-b6ec-42fd-9607-224bf9e2b847)

this is how my code look like like i said it was working greatly until a few days ago
```javascript
import axios from "axios";
import { POKE_PER_PAGE, MAX_POKE_COUNT } from "../helpers/constants";
const axiosInstance = axios.create({
  baseURL: `https://pokeapi.co/api/v2/pokemon`,
});
export const getPokemons = (page) => {
  const offSet = POKE_PER_PAGE * (page - 1);
  return axiosInstance.get(`?offset=${offSet}&limit=${POKE_PER_PAGE}`);
};

export const getPokemonWithId = (pokeId) => {
  return axiosInstance.get(`/${pokeId}`);
};
export const getPokemonWithUrl = (url) => {
  return axios.get(url);
};

```
++ i check few repository which using this api they get same error eg:
https://github.com/Ridwan-A-wae/Quiz-pokemon-v2
https://github.com/Sergio9815/pokedex-api

**Comment by Naramsim** [comment]
Hi! Thanks so much for the issue!

You are right. Today I switched from functions V1 to V2 and CORS headers have been removed. I'm publishing a fix right now. Most probably I'll have to purge all Cloudflare cache for you to see the effects. Give me some minutes.

**Comment by Naramsim** [comment]
That said, most of our resources are cached for 1 day. So only few uncached resources have the missing header.

**Comment by Naramsim** [comment]
should be deployed. can you check?

**Comment by emirhanyagci** [comment]
I checked, usually working fine but there is still some unfixed uri's these are my catch:
`https://pokeapi.co/api/v2/pokemon/2` and `https://pokeapi.co/api/v2/pokemon/20`
![image](https://github.com/PokeAPI/pokeapi/assets/66957950/91d28417-7d48-4012-a51c-221b8e45c171)
![image](https://github.com/PokeAPI/pokeapi/assets/66957950/ff9de35d-68d6-4cc8-a409-6b3c1f83048a)

You can check from this repository https://github.com/emirhanyagci/astopia-test-case

**Comment by Naramsim** [comment]
Ok, can you retry?

**Comment by emirhanyagci** [comment]
Look like working great. Thanks again.
