### ISSUE TITLE
Pokémon's highest and lowest stats.

### ISSUE THREAD

**Issue by Renen12** [PokeAPI/pokeapi#1112]
Pretty much what the title says, I would like to be able to fetch this information. Do we have this information in some database, or do we need to gather it from scratch? I could maybe help out a bit, if necessary.

**Comment by Naramsim** [comment]
Hi: here a past issue for the same problem. 

https://github.com/PokeAPI/pokeapi/issues/1058

We decided to close it since those min/max values are inferred from other values present in the API with a mathematical formula.

**Comment by Naramsim** [comment]
If you see the benefits of adding such a feature, you could try coding it on your PC and then submit a PR. Or ask here for details

**Comment by Renen12** [comment]
> Hi: here a past issue for the same problem. 
> 
> https://github.com/PokeAPI/pokeapi/issues/1058
> 
> We decided to close it since those min/max values are inferred from other values present in the API with a mathematical formula. 

Would it be necessary to add such a mathematical formula? What I'm referring to is just the highest base stat of the Pokémon, like that Groudon's highest stat is attack, and it's lowest is Special defense and speed,  and so on.  I guess I must've missed the stat array, so I could probably implement the highest and lowest stats in my application without an additional property programmed into Pokéapi. It's definitely more of a convenience thing, than a necessity.

**Comment by Renen12** [comment]
> > Hi: here a past issue for the same problem.
> > #1058
> > We decided to close it since those min/max values are inferred from other values present in the API with a mathematical formula.
> 
> Would it be necessary to add such a mathematical formula? What I'm referring to is just the highest base stat of the Pokémon, like that Groudon's highest stat is attack, and it's lowest is Special defense and speed, and so on. I guess I must've missed the stat array, so I could probably implement the highest and lowest stats in my application without an additional property programmed into Pokéapi. It's definitely more of a convenience thing, than a necessity.

I've implemented the highest and lowest stats in my application, so the addition to pokeapi is definetly not necessary. It only took a few for loops!
