### ISSUE TITLE
make build-db isn't working

### ISSUE THREAD

**Issue by dugramen** [PokeAPI/pokeapi#1113]
I ran the setup instructions, and the database file seems to be setup properly but no actual data is stored inside. It seems to be failing when I run `make build-db`. The output is this, and the resulting `db.sqlite3` file is only 2.4 megabytes

```
Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> 'from data.v2.build import build_all; build_all()'
>>>
now exiting InteractiveConsole...
```

Steps to Reproduce:

1. `make setup`
2. `make build-db`

Also I'm on windows 11, and not using docker due to wsl issues

**Comment by Naramsim** [comment]
Hi! I think windows lacks Linux `|`, so the echo command in the make build-db target doesn't reach `python`. 

Can you run the make command from within `bash`?

**Comment by Naramsim** [comment]
Ah no, I checked your log. The pipe seems to be working. But maybe the command is piped to the interpreter as a string and not as a command. Can you input the command without quotes?

**Comment by dugramen** [comment]
Thanks! That's exactly what it was. I removed the quotes under `build-db` in the make file and its all building now. Is that just a windows quirk or something?

**Comment by Naramsim** [comment]
Maybe it's how the cmd/PowerShell interprets quotes
