### ISSUE TITLE
Little problem with some pokemons

### ISSUE THREAD

**Issue by jrdelrio** [PokeAPI/pokeapi#1119]
Hi, thank you for the api!
I'm using it to some of my profile projects.

I'm using react and im having problems with 3 pokemons:
- gible
- ralts
- slakoth
error message: SyntaxError: Unexpected end of JSON input

Thank you very much!

**Comment by Naramsim** [comment]
Hi, the error isn't really clear. By looking at the JSON object, does it seem well formatted?

**Comment by Naramsim** [comment]
Can you reproduce the error in an online platform such as JSfiddle?

**Comment by jrdelrio** [comment]
When I render the image of pokemon "Gible" y get a Magicarp image.
I'll do some changes in my code and check again if it isn't my error and
let you know.
