### ISSUE TITLE
Change Resource Name for Giratina

### ISSUE THREAD

**Issue by krai-dev** [PokeAPI/pokeapi#1128]
I found data for Giratina under the URL https://pokeapi.co/api/v2/pokemon/giratina-altered, but there is no data for https://pokeapi.co/api/v2/pokemon/giratina. Since "Giratina" is the base form of this Pokémon, it would be more intuitive if the base URL https://pokeapi.co/api/v2/pokemon/giratina worked for it as well, without needing the "altered" form suffix.

Steps to Reproduce:

Navigate to the URL: https://pokeapi.co/api/v2/pokemon/giratina.
Observe the "Resource not found" error message.
Compare this with https://pokeapi.co/api/v2/pokemon/giratina-altered, which works.
Expected Behavior:
The URL https://pokeapi.co/api/v2/pokemon/giratina should return data for Giratina without the need to specify the form.

Thank you!

**Comment by Naramsim** [comment]
Hi, you should use the pokemon-species endpoint if you want to query the data about the species and then being redirected to the various pokemon.
