### ISSUE TITLE
"Nice Name" for Pokemon

### ISSUE THREAD

**Issue by Phyore** [PokeAPI/pokeapi#1134]
Is there any thoughts on adding "nice names" to Pokemon? E.g. calyrex-ice nice name would be Calyrex Ice Rider. Benefit could be for those wanting to use the API and easily access the names in a correct readable form. If this is something of interest, if pointed in the direction I could happily take a look

**Comment by phalt** [comment]
A human-readable name?

The `names` array on the [Pokemon species](https://pokeapi.co/docs/v2#name) resource has human-readable names.

**Comment by Phyore** [comment]
What about with alternative forms? Example: https://pokeapi.co/api/v2/pokemon-species/10193 (calyrex-ice)
