### ISSUE TITLE
Evolution chains returning incorrect data

### ISSUE THREAD

**Issue by HenkJanPie** [PokeAPI/pokeapi#1135]
The evolution chain API return incorrect evolution data. This is the case for (nearly) all ids. The evolution id seems to be roughly doubled somewhere. It's very easy to reproduce.

1. use the api. for example: https://pokeapi.co/api/v2/evolution-chain/4/
2. look at the evolution chain data. The current Id is correct(4 in this case), but the claimed evolution chain is completely incorrect (10 and 11 in this case).

Only bulbasaur (nr 1) and pokemon without evolutions seem to work correctly.

**Comment by Naramsim** [comment]
The linked evolution chain is for Caterpie, metapod and butterfly. Isn't it the correct order?

**Comment by HenkJanPie** [comment]
I think I see the issue. The ID isn't the Pokémon ID, but a unique ID for the specific evolution chain(id 1 = > Bulbasaur to Venusaur, id 2 = Charmander to Charizard, and so on).

You might want to add that to the documentation(+where you can get that ID), because that's pretty confusing imo.

For anyone having the same issue, I just looked around a bit, and you can find the evolution chain for a pokemon in: https://pokeapi.co/api/v2/pokemon-species/{pokemon id}, under 'evolution_chain'.

**Comment by Naramsim** [comment]
Yeah that's how the entire API works
