### ISSUE TITLE
Some types within the API do not provide the sprites key

### ISSUE THREAD

**Issue by m4rc0s4p4r1c10** [PokeAPI/pokeapi#1150]
When I fetch the [type endpoint](https://pokeapi.co/docs/v2#types) i am not able to fetch the sprites for some particular types depending on whether I use the ID 

From my testing this only happens with normal and shadow types for some reason(using the name instead of the ID).
Ice doesn't even have sprites key in neither key nor type queries.
Dark type doesnt have the sprites key on the key but it does on the name

Steps to Reproduce:

1. Go to https://pokeapi.co/api/v2/type/normal/

2. Go to https://pokeapi.co/api/v2/type/1/ (the same type but referencing its id)

3. Compare results

### Wrong results:
![2024-10-14_18-40](https://github.com/user-attachments/assets/2239ca38-27fe-47d0-b1b4-8b7f0483716c)
s
![image](https://github.com/user-attachments/assets/180ef0b1-35ae-44db-b940-ddf175c669e7)
![image](https://github.com/user-attachments/assets/7321898f-733f-4244-934a-040107bb3cd6)
![image](https://github.com/user-attachments/assets/e44a8c16-d558-4949-9a3f-2eae5609dbe3)

How it should be:
![image](https://github.com/user-attachments/assets/906591a2-6aa4-4cf1-9a49-6545699b16e5)

**Comment by Hongxiao-Chen** [comment]
I ran into the same problem. The types were fine yesterday but today the sprites are missing.
In my case, https://pokeapi.co/api/v2/type/fighting returns the sprites 
but https://pokeapi.co/api/v2/type/fighting/ did not.

**Comment by Naramsim** [comment]
Hi! You are right. Most probably the updater script had some problems with the amount of data present in the API. I'll try to regenerate it

**Comment by Naramsim** [comment]
Could you check again in 3 hours?

**Comment by m4rc0s4p4r1c10** [comment]
I won't be able to  but I'll try tomorrow

**Comment by Naramsim** [comment]
Ok! It seems a caching problem now. We can wait 24 hours and see what's happening then

**Comment by m4rc0s4p4r1c10** [comment]
Did some testing using this little script, most types are working fine now, the only one that is causing problems now is stellar type, particularly `https://pokeapi.co/api/v2/type/stellar` and also its corresponding ids `https://pokeapi.co/api/v2/type/19` and `https://pokeapi.co/api/v2/type/19/`. Those 3 appear as not found and for some reason `https://pokeapi.co/api/v2/type/stellar/` appears just fine

```bash
main_url="https://pokeapi.co/api/v2/type"

test_has_sprites(){

  response=$(curl -s "$1")
  echo -n "testing $1 "


  # Check if the .sprites key exists in the JSON response
  if [[ $(echo "$response" | jq 'has("sprites")') == true ]]; then
      echo "✔"
  else
      echo ".sprites key does not exist ⚔"
  fi
  echo '---'
}

names_to_test=($(curl -s "$main_url" | jq -r '.results[] .name'))
# Create an array from the space-separated string
ids_urls=($(curl -s "$main_url" | jq -r '.results[] .url'))


for test in  "${names_to_test[@]}"
do
  test_has_sprites "$main_url/$test"
  test_has_sprites "$main_url/$test/"
done;

for test in  "${ids_urls[@]}"
do
  without_trailing_slash="${test%/}"

  test_has_sprites "$without_trailing_slash"
  test_has_sprites "$test"
done;
```

**Comment by Naramsim** [comment]
Ok, root cause: https://github.com/PokeAPI/deploy/blob/master/functions_v1/src/index.js#L100

404 are cached 5 days.

**Comment by m4rc0s4p4r1c10** [comment]
Closing issue as now all types show the sprites key, thanks for the fixes!
