### ISSUE TITLE
Some Generation VIII and all Generation IX moves are returning 404

### ISSUE THREAD

**Issue by andreferreiradlw** [PokeAPI/pokeapi#1151]
Some `Generation VIII` and all `Generation IX` moves seem to be returning 404 since yesterday.

On the `Generation VIII` moves, the ones that seem to be returning 404 are also missing effect entries, for example:
- [apple-acid](https://pokeapi.co/api/v2/move/apple-acid)
- [court-change](https://pokeapi.co/api/v2/move/court-change)

Other moves from the same generation seem to work as usual, for example:
- [astral-barrage](https://pokeapi.co/api/v2/move/astral-barrage)
- [dragon-energy](https://pokeapi.co/api/v2/move/dragon-energy)

Example of a Generation IX move:
- [kowtow-cleave](https://pokeapi.co/api/v2/move/kowtow-cleave)

All of these move were returning data up until yesterday so I was wondering if anything has changed since then?

**Comment by Naramsim** [comment]
Hi, it seems we lost data at some point yesterday while merging PRs. We are aware of it and already regenerated the correct data (we think). Now it's going to take a day for Cloudflare to invalidate the data and serve the proper content.

**Comment by iamc24** [comment]
> Hi, it seems we lost data at some point yesterday while merging PRs. We are aware of it and already regenerated the correct data (we think). Now it's going to take a day for Cloudflare to invalidate the data and serve the proper content.

pounce, supercell-slam, behemoth-blade, and behemoth-bash are all still down.

**Comment by Naramsim** [comment]
Hi! It was a caching problem. I purged the cache on CF. Can you retry in a few minutes?

**Comment by iamc24** [comment]
All four move endpoints are up again, but behemoth-blade and behemoth-bash are missing learned_by_pokemon data. I noticed b/c that's what I'm trying to pull from the API, and I'm getting errors from that being missing for those 2 moves.

**Comment by andreferreiradlw** [comment]
@Naramsim thanks for the update, I've just checked everything and seems like the moves are back again so the original issue opened seems to be resolved now
