### ISSUE TITLE
Male and Female Basculegion forms have different version-groups

### ISSUE THREAD

**Issue by Deleca7755** [PokeAPI/pokeapi#1163]
Male https://pokeapi.co/api/v2/pokemon-form/902 has `sword-shield` as the `version-group` while female has https://pokeapi.co/api/v2/pokemon-form/10417/ `legends-arceus` as the `version-group`. I don't think this mon was In SwSh ever

I'll be more than happy to make a PR but I want to make sure this Issue Is even valid so

**Comment by Naramsim** [comment]
If you believe that the data is wrong and you checked on some website to confirm it, go ahead and submit a pr
