### ISSUE TITLE
Multiple issues resoved but are still open and need to be closed.

### ISSUE THREAD

**Issue by Writey0327** [PokeAPI/pokeapi#1166]
Going through the current open issues to fix problems to find many that have been resolved and need to be closed. Here is some examples.

https://github.com/PokeAPI/pokeapi/issues/786
![image](https://github.com/user-attachments/assets/da91a37d-45d9-4bb0-b144-02538bd5102c)

https://github.com/PokeAPI/pokeapi/issues/882

https://github.com/PokeAPI/pokeapi/issues/865

https://github.com/PokeAPI/pokeapi/issues/901

https://github.com/PokeAPI/pokeapi/issues/1069 fixed by https://github.com/PokeAPI/sprites/pull/156

Was just pointing this out in hoping some of the issue clutter is reduced.

**Comment by Naramsim** [comment]
Thanks a lot! Later I'll go through and close them!

**Comment by Naramsim** [comment]
Ok! Closed! Thanks for going through so many issues!

**Comment by Naramsim** [comment]
If you spot others, ping me in a comment at the issue and I'll check and close it
