### ISSUE TITLE
Unknown move ailment can't be found by id, only by name

### ISSUE THREAD

**Issue by sargunster** [PokeAPI/pokeapi#145]
`/move-ailment/-1/` is not found, but `/move-ailment/unknown/` works fine.

**Comment by phalt** [comment]
Why does a resource have a PK as `-1`?

**Comment by sargunster** [comment]
I got it from the resource list http://pokeapi.co/api/v2/move-ailment/.

**Comment by zaneadix** [comment]
@sargunster @phalt damn it looks like these resources start from -1 in the csv rather than 1. Odd. I'm not even sure what we could do about that off the top of my head. I'll try to look into this deeper soon.

**Comment by phalt** [comment]
The ID doesn't really matter so we could just update them? This is assuming everyone integrating with it is using hypermedia properly :laughing:

**Comment by sargunster** [comment]
Most likely updating the regex here will fix it. Will try later. https://github.com/PokeAPI/pokeapi/blob/master/pokemon_v2/api.py#L37
