### ISSUE TITLE
EV yield values for pokemon

### ISSUE THREAD

**Issue by sotrh** [PokeAPI/pokeapi#152]
The current api returns this for Venusaur:
```
{
	"id": 3,
	"name": "venusaur",
	"base_experience": 236,
	"height": 20,
	"is_default": true,
	"order": 3,
	"weight": 1000,
	...
 }
```
It would be nice to add EV yield values. (Taken from [pokemondb](http://pokemondb.net/pokedex/venusaur))

```
{
	"id": 3,
	"name": "venusaur",
	"base_experience": 236,
	"height": 20,
	"is_default": true,
	"order": 3,
	"weight": 1000,
	"ev_yield":[
		{
			"type":"SPECIAL_ATTACK"
			"value":2
		},
		{
			"type":"SPECIAL_DEFENSE"
			"value":1
		}
	],
	...
}
```
I believe that adding this feature would be just some database manipulation. I would create a fork and do it myself, but I have no idea where to start.

**Comment by charly-palencia** [comment]
@phalt  @sotrh  I already have a list of all the EV yield for each pokemon in a json file (via bulbapedia). should i create a CSV file ?

**Comment by phalt** [comment]
@sotrh it's just some database manipulation, you said yourself it can't be that hard? 😉 

I swear we've got some data like this already? I'm happy to accept a PR that adds this data.

**Comment by charly-palencia** [comment]
I would try to create the PR for this change. But first i need to understand the project :)

**Comment by charly-palencia** [comment]
@phalt  you are right, you already have this information https://github.com/charly-palencia/pokeapi/blob/master/data/v2/csv/pokemon_stats.csv. I'm looking for some endpoint with this information right now.

**Comment by charly-palencia** [comment]
@sotrh I found the api already has this data into the pokemon Endpoint. you have to check the effort into the Stats relation:

Example: 

`pokemon/1`

```
...
"stats": [
		{
			"stat": {
				"url": "http://localhost:8000/api/v2/stat/1/",
				"name": "hp"
			},
			"effort": 0, #<== this is what you are looking for
			"base_stat": 78
		},
...
```

cc @phalt, I think that you can close this Issue now. thanks

**Comment by sargunster** [comment]
It'll be easier to find EV with that change to the doc :P
