### ISSUE TITLE
SubResourcing

### ISSUE THREAD

**Issue by Naramsim** [PokeAPI/pokeapi#180]
It will be great to let users download a single part of a JSON: let me explain, if I want to see machop type, I dont want to download all things related machop. It could be useful to make an API similar to this: https://pokeapi.co/api/v2/pokemon/machop/types. So the JSON will be lighter and the server will be less stressed

**Comment by phalt** [comment]
I agree. I think in particular `pokemon/ID/locations` would benefit from this, considering it's substantial size.

**Comment by sdcinglis** [comment]
How about a fields param in the request? IE pokemon/25?fields=id,name,sprites[front_default] would just return:
```
{
    id:25,
    name:"pikachu"
    sprites:{
        front_default:"http://www.pokeapi.co/media/sprites/pokemon/25.png"
    }
}
```

This is the syntax used by most google APIs I've used, probably not a simple thing to add though. Subresourcing would let you get a small part of larger objects like pokemon but if you need multiple small parts you're still forced to make multiple api calls.

**Comment by phalt** [comment]
@sdcinglis It's an interesting idea but I think it's a fairly complex API. Also, I've not seen this implemented much, and I want to avoid bespoke ways of doing things for a tool that is primarily used for education.

What is wrong with the whole JSON document and just using the parts you want?
