### ISSUE TITLE
Evolution gender docs

### ISSUE THREAD

**Issue by sargunster** [PokeAPI/pokeapi#192]
The docs claim that EvolutionDetail's gender field is a named resource to the gender object, but in reality it's just an int. This a bug either in the code or the docs. I think this should be changed to a named resource of the gender, but if not then update the doc.

See: `/api/v2/evolution-chain/213/`

**Comment by zaneadix** [comment]
Oh nice catch. This is actually just an error in the docs. If I remember right it should be a value between 1 and 8. 1 meaning all of them are male. 8 meaning all of them are female. 2-7 to represent the percentage leaning male vs female. Something like that.

**Comment by sargunster** [comment]
Percentage doesn't really make sense here. It's an object describing the conditions for evolution. In this case it's null if it doesn't matter, or the int id of the gender if a specific gender is required for evolution.

For example: Burmy evolves to Wormadam iff it is female, so the `gender` field is `1`. I think it should be `{"name": "female", "url": "https://pokeapi.co/api/v2/gender/1/"}` instead, since all other references to objects use that format instead of just the id.
