### ISSUE TITLE
Pokemon's Location Area Encounters docs inconsistent with API response.

### ISSUE THREAD

**Issue by fferegrino** [PokeAPI/pokeapi#195]
The property `"location_area_encounters"` at the Pokemon endpoint now returns a string pointing to an URL

Example, for Resource Jirachi: `"location_area_encounters": "/api/v2/pokemon/385/encounters"`

According to the docs, it should return an array:

`"location_area_encounters": [],`

Is this a mistake or a change in the API?

**Comment by phalt** [comment]
@fferegrino this is a known change made to improve the performance of the API. I completely forgot to update the docs to reflect this! I guess this is a good testament to how quickly changes affect end users. Sorry about that! I'll rename your ticket to reflect the bad docs.

**Comment by fferegrino** [comment]
Cool, thank you for your quick response. I'm creating a client (called [Jirapi](https://github.com/ThatCSharpGuy/Jirapi)) and this issue arose during some tests. I'll modify accordingly.

A final question, querying that endpoint should return the same result as the property did?

**Comment by sargunster** [comment]
Yep

**Comment by Naramsim** [comment]
Sorry, maybe it's me.
But here http://pokeapi.co/api/v1/pokemon/13/ I can't find any "location_area_encounter".
Was moved?
