### ISSUE TITLE
Pokedex entry for id #10 is missing

### ISSUE THREAD

**Issue by mrand01** [PokeAPI/pokeapi#215]
http://pokeapi.co/api/v2/pokedex returns a count of 14, but when I call http://pokeapi.co/api/v2/pokedex/10 the record is not found.  Also, it looks like you have a record at http://pokeapi.co/api/v2/pokedex/15 that shouldn't exist.  Could the 15th record be the missing 10th?

Quick edit: I also see that this file https://github.com/PokeAPI/pokeapi/blob/master/data/v2/csv/pokedexes.csv indicates maybe the 10th entry shouldn't be able to be called by id?  Is that correct behavior?

**Comment by sargunster** [comment]
IDs are not always consecutive. Check the results list.

**Comment by mrand01** [comment]
Yep, just noticed that in your seed data in the csv I linked above.  Strange behavior, but easy enough to work around.  Thanks!
