### ISSUE TITLE
App Showcase section

### ISSUE THREAD

**Issue by phalt** [PokeAPI/pokeapi#217]
We get a tonne of new apps being developed with PokéAPI. We should build a section that helps to promote them, especially ones that are new and from first-time programmers.

This doesn't need to be anything fancy, but a simple form for people to submit their projects with a URL link and an image, with a simple way of approving apps, is all it takes.

Who would like to work on something like this?

**Comment by kikin81** [comment]
This is a great idea! 👍

**Comment by ReduxRedstone** [comment]
that would be cool. currently using this API to get the sprites for a PokemonGO project im working on ( https://youtu.be/CjwBZABvRn0 ) so it would be cool to have a showcase area

**Comment by DigitalFlow** [comment]
Firstly, I'd like to thank you very much for creating this great API.
I'm using parts of it for my application which makes proposals for completing your Pokemon teams based on usage statistics from Pokemon GL.
Your API is used for creating an initial Pokedex XML with all Pokemon, Names, IDs and sprites, which are used for being displayed and for defining the available Pokemon set.
You can find it [here](https://github.com/DigitalFlow/Pokemon-Team-Builder).
