### ISSUE TITLE
Surf HM for ORAS has wrong item listed

### ISSUE THREAD

**Issue by sentwistler** [PokeAPI/pokeapi#222]
When making a request to `/api/v2/machine/1164/` (from a locally hosted server, as the machine resources don't seem to be available quite yet from the website), the following output is shown:

``` json
{
    "item": {
        "url": "http://localhost:8000/api/v2/item/407/",
        "name": "rule-book"
    },
    "move": {
        "url": "http://localhost:8000/api/v2/move/57/",
        "name": "surf"
    },
    "id": 1164,
    "version_group": {
        "url": "http://localhost:8000/api/v2/version-group/16/",
        "name": "omega-ruby-alpha-sapphire"
    }
}
```

Although the entry ostensibly refers to the Surf HM for ORAS, the item it refers to is incorrect. The error appears to be in the [data itself](https://github.com/PokeAPI/pokeapi/blob/master/data/v2/csv/machines.csv#L1165). The `item_id` entry should be 399, like the other entries for `103`.

I've seen on other issues that the data comes from another source, so I'm not sure if the policy is to have it fixed upstream rather than patching it here, but I still figured it was worth mentioning it just in case.

**Comment by sargunster** [comment]
Yeah, the data comes from here: https://github.com/veekun/pokedex

It's preferable to have the data fixed upstream so we're not maintaining our own patches on the data. I wonder if it's already been fixed there? I'm not sure how up-to-date we are with veekun's data.
