### ISSUE TITLE
Bulbasaur has gender differences

### ISSUE THREAD

**Issue by addui** [PokeAPI/pokeapi#225]
Currently your data says that Bulbasaur does not have gender differences, that is incorrect.

**Comment by phalt** [comment]
@addui which API version?

**Comment by addui** [comment]
2

**Comment by zaneadix** [comment]
@addui I believe this field may just be documented incorrectly.

has_gender_differences - Whether or not this Pokémon can have different genders

My bad. It should really say whether or not they have visual gender differences (like venusaur for example).

**Comment by addui** [comment]
So is there another field that says if there they have gender or not?

**Comment by sdcinglis** [comment]
The gender_ratio field is -1 for genderless Pokemon like unown.
