### ISSUE TITLE
Search Pokemon with other language

### ISSUE THREAD

**Issue by MTRNord** [PokeAPI/pokeapi#235]
We/I have the Problem that the Api only uses english (I think) names for the endpoints of "api/v2/pokemon/{name}/" but I (and others in a chat where I use the API) only learned the german names. Is there a way to call the API with german names or to "auto-translate" it correct?

**Comment by sargunster** [comment]
No, that functionality doesn't exist. Your best bet is to call by id
instead. The full object contains translated names.

**Comment by MTRNord** [comment]
And is there a file where these translations are belongside the english ones? I have as idea that I could use the german names and "translate" it to an id or where do you get the translations from?

**Comment by sargunster** [comment]
https://github.com/PokeAPI/pokeapi/blob/master/data/v2/csv/pokemon_species_names.csv

I believe German is language id 6.

**Comment by MTRNord** [comment]
Ok than I write and thingy that searches the german name in that file and gets that ID. If you want you can close the issue :)

**Comment by sargunster** [comment]
I've made the proposal #236 to cover use cases like this. Go ahead and follow that if you're interested.

**Comment by GladiusBlack** [comment]
@MTRNord # könntest du mir das mal erklären wie das funktioniert die Pokemon und den Pokedex auf Deutsch einzustellen? Ich verstehe die Computersprache nicht so wirklich. Das einzige was ich bis jetzt geschafft habe ist das man nun die Texte auf dDeutsch hat wenn man es gefangen hat ect.

**Comment by Davidwalser** [comment]
@MTRNord did you come up with something?

**Comment by MTRNord** [comment]
> @MTRNord did you come up with something?

I don't even remember having opened this issue 6 years ago :D so I also don't remember where I used it or how I used it. Sorry 😅

**Comment by Davidwalser** [comment]
@MTRNord all good :) the api is kinda frustrating tho not offering proper language support :(

**Comment by Naramsim** [comment]
@Davidwalser here you go: 

```gql
query searchForPokemonInGerman {
  pokemon_v2_pokemonspecies(
    where: {
      pokemon_v2_pokemonspeciesnames: {
        pokemon_v2_language: { name: { _eq: "de" } }
        name: { _regex: "Ento.*" }
      }
    }
  ) {
    pokemon_v2_pokemonspeciesnames(
      where: { pokemon_v2_language: { name: { _eq: "de" } } }
    ) {
      name
    }
    id
  }
}
```

I used [GraphQL](https://beta.pokeapi.co/graphql/console/). If you want you can insert two variables (`language_name` and `pokemon_name_in_the_specified_language`) and use the native GQL functionality to form a GQL query. Or use the above and substitute `"de"` with your [language](https://pokeapi.co/api/v2/language/) and `"Ento*` with your pokemon name. 

Btw, _Enton_ and _Entoron_ are Psyduck and Golduck in German.
