### ISSUE TITLE
CloudFlare doesn't provide benefits

### ISSUE THREAD

**Issue by nimaje** [PokeAPI/pokeapi#237]
[This article](http://cryto.net/~joepie91/blog/2016/07/14/cloudflare-we-have-a-problem/) argues that there are no benefits by using CloudFlare, but big issues like:
  - blocking based on IP-adresses -> a lot of false positives
  - MITM by CloudFlare
  - the "I'm Under Attack" challange is easily solveable by computers

The article provides actual solutions.
Therefore I suggest to stop using CloudFlare.

**Comment by phalt** [comment]
I am going to continue using CloudFlare, it provided us huge benefit when we were being DDoS'd last month, and it has significant benefit for the server load.
