### ISSUE TITLE
[STATUS PAGE] Cachethq

### ISSUE THREAD

**Issue by Naramsim** [PokeAPI/pokeapi#241]
Hi, I think we should definitely add a status page to the pokeapi.co website.

[Cachethq.io](https://cachethq.io/) is pretty good. It analyses everything and makes beautiful graphs.
Here is a [demo](https://demo.cachethq.io/)

PS: it is free :yellow_heart:

**Comment by Kaijiro** [comment]
In the same domain, I know [Datadog](https://www.datadoghq.com/) which is used to monitor [actual PokémonGo servers](http://ispokemongodownornot.com/).

It has also a free plan but I don't really know if it fit your needs.
