### ISSUE TITLE
Node.js wrapper for v2

### ISSUE THREAD

**Issue by palanik** [PokeAPI/pokeapi#243]
Created a simple [wrapper](https://github.com/wrapi/pokemon) for Pokéapi V2.

Review & feedback are welcome.

**Comment by sargunster** [comment]
You can add it to the list of wrappers here: https://pokeapi.co/docsv2/#wrap via PR.

**Comment by palanik** [comment]
Done. [PR-244](https://github.com/PokeAPI/pokeapi/pull/244).
Thanks.
