### ISSUE TITLE
Download of Default Front Image slow

### ISSUE THREAD

**Issue by DigitalFlow** [PokeAPI/pokeapi#245]
Hello everyone,

First of all I would like to thank you for your great API, it is very useful to me.
I'm currently creating an application which helps building Pokemon Teams.
For this I retrieve all Pokemon with their default sprites and save them into an XML file for not needing to contact the API too often.
Unfortunately retrieving all pictures is very slow, it took almost 14 minutes to retrieve the first 250 sprites.
Now I wonder, whether I'm doing something wrong and if I could speed things up.
I'm using HttpClient with GetAsync for retrieving the images.

Thanks for your help.

Kind regards,
Florian

**Comment by sargunster** [comment]
Sounds like it's taking you 3-4 seconds to get each sprite. This is about the same time my requests are currently taking. It was definitely faster a few weeks ago, it's probably because traffic to the API has been really high lately.

**Comment by DigitalFlow** [comment]
Thanks for your response @sargunster, that's good to hear. Will just hope for the traffic to become less again, although the Pokemon Go hype might still push it further.
I will close the issue in this case.
