### ISSUE TITLE
Description of the Pokémon in V2

### ISSUE THREAD

**Issue by AjawadMahmoud** [PokeAPI/pokeapi#247]
Hello,,
Huge thanks for everyone working on this.

I'm not sure if i'm mistaken here, but, V2 doesn't provide Pokémon description like V1. and the docs for the Pokémon endpoint is missing from the docs making it more confusing to decide whether i'm missing something from the call results or it's really the case.
One more thing the gender ratio. I also can't find it anywhere in the V2.

**Comment by sargunster** [comment]
The `pokemon-species` endpoint has flavor text and gender rate.

**Comment by AjawadMahmoud** [comment]
Alright. I guess the docs need to state that in the Pokemon category.
