### ISSUE TITLE
[QUESTION] Status code 429

### ISSUE THREAD

**Issue by Naramsim** [PokeAPI/pokeapi#248]
While building and test our Node wrapper. Pokeapi.co responded us with:
`StatusCodeError: 429 - {"detail":"Request was throttled. Expected available in 831.0 seconds."}`

What does this mean? Did it ban us for a short period of time?

Thanks

**Comment by phalt** [comment]
@Naramsim yeah it looks like you hit the API rate limiting.

**Comment by Naramsim** [comment]
Ok, thanks @phalt 
Are you going to merge and test #240?
