### ISSUE TITLE
[QUESTION] $effect_chance%

### ISSUE THREAD

**Issue by Naramsim** [PokeAPI/pokeapi#249]
Hi, when querying: http://pokeapi.co/api/v2/move/secret-power/

The effect proposed is this one:

> Has a $effect_chance% chance to inflict a status effect which depends upon the terrain.

Is normal, or API didn't render a part of the JSON?

**Comment by phalt** [comment]
@Naramsim I think this is some specific syntax with the data set we use. It could even be syntax used by the games to create hyperlinking.

**Comment by Naramsim** [comment]
So it will remain as it is now?
I'll replace with a random number :smile:

**Comment by phalt** [comment]
@Naramsim yep :)
