### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by sotojuan** [PokeAPI/pokeapi#250]
Hi, I'm getting really slow response times on the API and site itself... more than three seconds for requests for a few days. I don't know anything about Django otherwise I'd help, but just wanted to bring it to attention. Thanks!

**Comment by Naramsim** [comment]
Cache cache cache and do not overload the APIs.

@phalt, @vohras, @zaneadix should the APIs rate limit be lowered?

**Comment by sargunster** [comment]
I think we should see how the 4-worker Nginx config performs before lowering the rate limit further. Or is it already being used?

**Comment by sotojuan** [comment]
I haven't overloaded the APIs at all—at most I make 10 requests a day. I'm assuming others are since it's a public, no-auth API. Hope you guys can find a solution—limiting rates more sounds good. At the same time, SWAPI (Star Wars API) is also a Django project, as popular (maybe not?), and is pretty fast. Are they limiting more than Poke API?

**Comment by sargunster** [comment]
PokeAPI has had a huge increase in usage since Pokemon Go came out.

**Comment by sotojuan** [comment]
Got it—a good problem to have ha. Hope you guys sort it out!

**Comment by phalt** [comment]
@sotojuan key difference with SWAPI is that I'm hosting it on Heroku, whereas PokéAPI is 1) about 20x more popular and 2) on DigitalOcean, a different hosting provider :)

I am inclined to wait out the popularity storm, as this isn't an accurate time for judging the API's popularity or performance. The NGINX config changes - I just need to find a day to sit down and work on it.

**Comment by sotojuan** [comment]
Got it—had no idea it was this popular. Didn't meant to sound angry or disappointed, was just genuinely curious!

**Comment by phalt** [comment]
@sotojuan absolutely no problem :)
