### ISSUE TITLE
I am creting at python client class to consume the api, but I receive error 503 and I dont have get the data. If I test in the web broser(Example : Chrome ) I receive in some times of test at message of dds protection.

### ISSUE THREAD

**Issue by camilonos77** [PokeAPI/pokeapi#251]
I am creting at python client class to consume the api, but I receive error 503 and I dont have get the data. If I test in the web broser(Example : Chrome ) I receive in some times of test at message of dds protection.

**Comment by phalt** [comment]
@camilonos77 please update your description to reflect your issue.

**Comment by phalt** [comment]
@camilonos77 we are currently experiencing a violation of fair use, causing the service to run very slow. We are banning API access until the developer stops causing a denial of service.

**Comment by camilonos77** [comment]
Oshhh, In this case I dont have use the api ?

**Comment by phalt** [comment]
@camilonos77 until the attack subsides, access to the API is being limited.

**Comment by camilonos77** [comment]
Ok I goint to test later, I want to get the api for caching the data and make myself pokedex to test django + angularjs app.

Regards.

**Comment by nimaje** [comment]
@camilonos77 If you only need the data you can get it from https://github.com/veekun/pokedex/tree/master/pokedex/data/csv or from `data/v2/csv` here.
You would have to parse csv files.
