### ISSUE TITLE
API down?

### ISSUE THREAD

**Issue by DigitalFlow** [PokeAPI/pokeapi#253]
Hello everyone,

is it possible, that the API is currently unavailable?
I'm receiving 503 - Service temporarily unavailable when trying to retrieve data using the JSON API.
This is when trying to retrieve the api/v2/pokemon/ ressource without specifying an ID, to retrieve all pokemon.
The demo request sender at pokeapi.co is working fine, though.

Kind Regards,
Florian

**Comment by phalt** [comment]
@DigitalFlow please see other issues before posting - we're in DDoS protection mode because a single user is spamming all of our .png, slowing down the service.

**Comment by DigitalFlow** [comment]
Sorry about that, just looked at the open ones.
