### ISSUE TITLE
[Enhancement] VirtualEnv

### ISSUE THREAD

**Issue by Naramsim** [PokeAPI/pokeapi#259]
Hi, it could be great if, before installing anything, a [virtualenv](https://virtualenv.pypa.io/en/stable/) is created.

So we do not override user packages and user python installation.

**Comment by TheTommyTwitch** [comment]
This sounds like a good idea to me 👍

**Comment by phalt** [comment]
virtualenv is standard practice in Python, so 👍 - we could add it to the makefile bootstrap commands?
