### ISSUE TITLE
Error: (503) Service Temporarily Unavailable

### ISSUE THREAD

**Issue by PikaDude** [PokeAPI/pokeapi#262]
Hi! I've been using the PokeApi for a while now and my small project occasionally makes requests to the Api, although recently, when my program tries to make a request, most likely because cloudflare is blocking it for some reason, any ideas how to fix this problem with cloudflare?

**Comment by phalt** [comment]
@PikaDude what resources are you trying to access? From where is your API making calls (IP address location)

**Comment by PikaDude** [comment]
My vps in Singapore

**Comment by phalt** [comment]
Singapore, Indonesia, Thailand and China have been banned. This is due to severely high traffic breaking the website (11 million requests per day, vs 2 million for the rest of the world).

**Comment by PikaDude** [comment]
wow. any ideas on what to do other than move the vps?

**Comment by phalt** [comment]
I'm sorry. I spent a long time tying to find the individual IP addresses causing the huge traffic load and I was unable to, banning the country IP range was the only solution.
