### ISSUE TITLE
Get types for specific Pokemon?

### ISSUE THREAD

**Issue by stingclaw** [PokeAPI/pokeapi#267]
Is there a way (or can you implement one) to get types for a specific Pokemon? I'm developing an Pokedex app but it takes a _long_ time for every single request because the moves take up so much space (even though I don't use them).

Edit: Such as http://pokeapi.co/api/v2/pokemon/721/types/

**Comment by craig-clayton** [comment]
Types are available in the initial response, selecting just these from the response should be simple enough.

Subresourcing is not currently supported and there aren't currently any plans to add this, though I don't believe this would have a significant impact on load times here anyway.

**Comment by sargunster** [comment]
There's a `types` field in the `pokemon` resource: http://pokeapi.co/api/v2/pokemon/1/.

You can check the documentation here: http://pokeapi.co/docsv2/#pokemon.
