### ISSUE TITLE
Pull Pokemon Ken Sugimori from Bulbapedia

### ISSUE THREAD

**Issue by gregdegruy** [PokeAPI/pokeapi#268]
Starting point could be at the Wiki API sandbox https://en.wikipedia.org/wiki/Special:ApiSandbox.

Currently in the process of figuring out if this is even possible [Stackoverflow question](http://stackoverflow.com/questions/39601593/using-wikipedia-api-on-custom-wikis-like-bulbapedia). If not what it be possible to make start a task in uploading all of the pokemon Ken Sugimori to this repo? I'd love to help with it, if it's something you all feel is valuable and can be added to the API.

**Comment by craig-clayton** [comment]
These images are available in the sprites repo:
https://github.com/PokeAPI/sprites

**Comment by gregdegruy** [comment]
Oh, up to gen IV is there awesome. Is there a rest call that provides this artwork?

**Comment by craig-clayton** [comment]
Up to no.720 is there. These assets are provided there as an alternative to making API requests as such requests put unnecessary stress on the service.

**Comment by gregdegruy** [comment]
https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other-sprites/official-artwork/{DEX_NUMBER}.png is all that's needed then.

Sweet, looking forward to playing around with the API and possibly adding my own contributions as I discover more.
