### ISSUE TITLE
Pokemon.location_area_encounters URL is not consistent with other URLs

### ISSUE THREAD

**Issue by jahed** [PokeAPI/pokeapi#270]
Under a Pokemon resource (e.g. /pokemon/427), the URL to the encounters resource is not full. Meaning, unlike other URLs in the API, the client needs to ensure it requests it by prefixing the protocol and host.

For example:

```
{
    location_area_encounters: "/api/v2/pokemon/427/encounters",
}
```

Ideally it should be

```
{
    location_area_encounters: "http://pokeapi.co/api/v2/pokemon/427/encounters",
}
```

**Comment by phalt** [comment]
Nice spot, reckon this could be easily fixed by an eager contributor

**Comment by MestreLion** [comment]
Looks like our friend @dhcrain fixed this in PR #274. Any words on why was this bug (or that PR) both closed?

**Comment by tdmalone** [comment]
@MestreLion Every outstanding issue was closed around mid-year when PokeAPI was due to shut down. Thankfully, it was decided to keep it running! :D I'll re-open this issue for now; I'm not sure why the PR was closed as that was only quite recent, so I'll leave that for @Naramsim to advise on.

**Comment by JvPy** [comment]
Still open? I would like to contribute

**Comment by jahed** [comment]
I don't use this API anymore, but trying it out at https://pokeapi.co/, it looks fixed to me.

I'm going to close this issue.
