### ISSUE TITLE
Not compatible with DRF 3.5

### ISSUE THREAD

**Issue by dhcrain** [PokeAPI/pokeapi#272]
In requirements.txt it calls for djangorestframework>=3.1.0, current version is 3.5.1

Error:
Creating a ModelSerializer without either the 'fields' attribute or the 'exclude' attribute has been deprecated since 3.3.0, and is now disallowed. Add an explicit fields = '**all**' to the PokemonMoveSerializer serializer."

Will submit pull request, with adding the fields attribute to the PokemonMoveSerializer using the fields from here; https://pokeapi.co/docsv2/#moves

**Comment by phalt** [comment]
We should pin the version. Do you know which version of DRF it works with?

**Comment by dhcrain** [comment]
Locally It will work for me with DRF 3.3.0 like stated in the error. 
And works without the fields attribute added to the PokemonMoveSerializer, also works with `fields = '__all__'`  added, but will throw other errors when adding the fields explicitly.
