### ISSUE TITLE
Full translation into spanish

### ISSUE THREAD

**Issue by Luckino** [PokeAPI/pokeapi#278]
I would like to help translate the database data completely into Spanish.

Thanks for reading me

**Comment by leofbernardo** [comment]
So I would like to help translate the db data completely into Portuguese, too.

:D

**Comment by hugmanrique** [comment]
You can create a pull request with your changes, there's no need to create an issue for this

**Comment by Pathsofpain97** [comment]
Hello i have a repository and dont know how change the data language of pokeapi in my job.
https://github.com/Pathsofpain97/SpanishPokedex.github.io
