### ISSUE TITLE
Some pokemon seem to be missing (ie. Giratina, Basculin) Update: Slightly misleading title, read description

### ISSUE THREAD

**Issue by MeLikeChoco** [PokeAPI/pokeapi#283]
I don't know all of them that are missing, but I know for a fact Giratina is missing. It's quite an old pokemon. Some of the multiple form pokemon are missing as well.

Deoxys is missing as well ._.
Update: deoxys found through id

**Comment by MeLikeChoco** [comment]
Aha, some of them can only be searched through id unless you get the name exactly correct. Like Deoxys normal. How would one search with just words then?

**Comment by jdnklau** [comment]
Instead of searching in the `pokemon/` endpoint, use `pokemon-species/`.

That one lists one of each Pokémon, regardless of form. Forms are listed in the varieties field of the respective entry, with one being marked as default.
