### ISSUE TITLE
Get all Pokemon once

### ISSUE THREAD

**Issue by firestar300** [PokeAPI/pokeapi#285]
Hi,

I would like to create a kind of auto-complete input field which match with all Pokemon list by name (not by id).

For example, I wrote `Char` in my field, and two suggestions appears : `Charizard` and `Charmander`. Unfortunately,  I can't get `http://pokeapi.co/api/v2/pokemon/char` and the `http://pokeapi.co/api/v2/pokemon/` get request displays 20 Pkmns.

Do you have suggestions ?

Thank you :)

**Comment by sargunster** [comment]
1. http://pokeapi.co/api/v2/pokemon/?limit=0
2. See count = 811
3. http://pokeapi.co/api/v2/pokemon/?limit=811

**Comment by firestar300** [comment]
Nice ! Thank you.
