### ISSUE TITLE
get all pokemon with its data

### ISSUE THREAD

**Issue by xxryan1234** [PokeAPI/pokeapi#287]
Hi I want to get all the pokemon with its data attached to them.

What I am using right now is `http://pokeapi.co/api/v2/pokemon/?limit=811` but it only shows the name of the pokemon, how can I let it display the pokemons data as well?

**Comment by Gnifle** [comment]
What kind of data are you looking to obtain through this? The amount of data you get for a single Pokemon (e.g api/v2/pokemon/{id or name}) is already rather immense, getting 800+ in one chunk doesn't seem like the best idea.

The specific endpoint you pointed to already gives you a list with the direct endpoint for each Pokemon - why not jut iterate this list and make a call for each?

**Comment by xxryan1234** [comment]
My bad, did not close this issue. I decided to do what you just said @Gnifle . Thanks!
