### ISSUE TITLE
Add Descriptions for v2

### ISSUE THREAD

**Issue by thechief389** [PokeAPI/pokeapi#288]
Add descriptions for the v2 api.

**Comment by tdmalone** [comment]
What do you mean? Add descriptions for what?

**Comment by thechief389** [comment]
Maybe I figured it out already. I found out that the flavor text in v2's species's flavor text was the same as v1's descriptions.

**Comment by tdmalone** [comment]
@thechief389 Glad you figured it out. You can close this issue if so, to help reduce clutter :)
