### ISSUE TITLE
Still missing CORS header

### ISSUE THREAD

**Issue by dwicao** [PokeAPI/pokeapi#289]
Hi! I've used PokeAPI in my [React.js pure client-side app](http://react-pokedex.surge.sh) [[repo](https://github.com/dwicao/react-pokedex)],
any API calls fail because it still missing CORS header,
although I've been set a user agent header `{ 'User-Agent': 'cheese' }`,
any workarounds?

## SOLVED: cloudflare messes up the request.
1. Try add a slash to the end of the request - `http://pokeapi.co/api/v2/`
2. Try change API endpoints from http://pokeapi.co/api/v2 to http://pokeapi.salestock.net/api/v2
It works! 🎉 🎉 🎉  

3. Or as a temporary remedy, you can try cors.now.sh
https://cors.now.sh/https://pokeapi.co/api/v2/

**Comment by Naramsim** [comment]
The app seems to work, on my side.

**Comment by dwicao** [comment]
I don't know why, but now it seems worked 🎉

**Comment by dwicao** [comment]
still don't work 😭 
![image](https://user-images.githubusercontent.com/17260743/30676117-9f3fb7d8-9eae-11e7-93a4-1aa1dd8f927c.png)

**Comment by antilama** [comment]
My app also stopped working few days ago due to similar error.
![cors](https://user-images.githubusercontent.com/31658145/30989614-9207bd68-a49e-11e7-8ddb-0c9def476e03.png)

**Comment by Mjain10** [comment]
I have the same problem, can't seem to find a fix to it

**Comment by Naramsim** [comment]
Probably is something related to our CDN provider, CloudFlare.

Try to make direct HTTPS calls

**Comment by antilama** [comment]
Calling API through HTTPS solved the issue for me, although I don't really understand how.

**Comment by Naramsim** [comment]
@antilama Probably our Cloudflare when redirecting http to https (somebody probably enabled HSTS) strips away our 'Access-Control-Allow-Origin' header.

If this solution work for @Mjain10 we can close

**Comment by Mjain10** [comment]
I'm getting a 504 error instead when using https
<img width="414" alt="issue" src="https://user-images.githubusercontent.com/22925491/31040901-d4732f22-a541-11e7-8797-35a8ffc7c4cf.png">

**Comment by arfianadam** [comment]
I still get this exact problem. Switched to https and still na da. Any fix?

**Comment by arfianadam** [comment]
Https request also requires Cloudflare verification which is not usable on client-side API calls.

**Comment by Naramsim** [comment]
So Cloudflare messes up the request. If anybody could investigate...

**Comment by dwicao** [comment]
Yeah, cloudflare messes up the request.
Change API endpoints from http://pokeapi.co/api/v2 to http://pokeapi.salestock.net/api/v2
It works! 🎉 🎉 🎉

**Comment by krinsane** [comment]
Even with http://pokeapi.salestock.net/api/v2, it works fro sometime and later it stops working with the same CORS as the issue. What can be done?

**Comment by Naramsim** [comment]
As a temporary remedy, you can try cors.now.sh

https://cors.now.sh/https://pokeapi.co/api/v2/pokemon/1/

**Comment by davidnguyen179** [comment]
call via **https** is worked for me

**Comment by Koleja** [comment]
I have the same problem. I created simple app in June and it was working fine with simple $.getJSON request, and now I came back to this app and it just stopped working. Is there any permanent idea how to solve this? HTTPS works with Chrome but error is still on Safari, no clue how with Firefox.

**Comment by Naramsim** [comment]
@Koleja You could try digging on why Cloudflare sometimes strips away CORS headers

@phalt, is cloudflare configured properly?

**Comment by Bingbazaar** [comment]
Oddly enough, it worked for me to just request data with the added / at the end. So like:

https://pokeapi.co/api/v2/pokemon/722/
instead of 
https://pokeapi.co/api/v2/pokemon/722

I don't know if it's gonna fix it for anybody else, but I thought I might as well post it here :)

**Comment by Naramsim** [comment]
@Bingbazaar when putting a slash at the end you are avoiding a 301 redirect. Because pokeapi.co/api/v2/pokemon/722 redirects to pokeapi.co/api/v2/pokemon/722/. That means you gain also in performance

**Comment by terada46** [comment]
I just start to play with this api. 
https://pokeapi.co/api/v2  never work in my client-side app.
With http://pokeapi.salestock.net/api/v2, only the resource lists return, such as pokemon's list. But I can't get any of pokemon by id or name.

**Comment by Neodecadente** [comment]
Having this issue on Firefox Quantum 61.0.1, NOT having this issue on Google Chrome 67.0.3 using  https://pokeapi.co/api/v2/

Weird thing is that  if I make the request from Firefox's console, it works, but not when requesting from my Javascript file.

**Comment by Jace-Beaudoin** [comment]
Was stuck on this for a while @Bingbazaar! Thanks! Sorry this hasn't been fixed for other people, hope it gets resolved soon.

**Comment by bclindner** [comment]
CORS seems to be strange overall - I can get this endpoint to work fine in Firefox and Chrome: 
`https://pokeapi.co/api/v2/pokemon/1/`

But not this one: 
`https://pokeapi.co/api/v2/pokemon/bulbasaur/`

Just adding some info to the pile.

**Comment by cmmartti** [comment]
@bclindner This is a side effect of the outage we had Thursday and Friday. We implemented a quick fix (uploading static JSON files to the server) in anticipation of moving the API to a static host at some point in the near future, but not everything works. Named endpoints only work for pokemon right now, for example. There are still a couple of hurdles to get over, but once we finally move to static hosting on Netlify, all of these issues should be solved.

See #369 for details of the outage, and #350 for the whole story.

**Comment by Naramsim** [comment]
I added the CORS to named res. https://pokeapi.co/api/v2/pokemon/golduck/

**Comment by SilasOtoko** [comment]
Any suggestions for those running a site with HTTPS that doesn't allow for HTTP calls? I tried using the  salestock.net domain for the call and it worked great on my local environment, but my live site is using HTTPS and is blocking the request. There doesn't seem to be a working HTTPS version of pokeapi.salestock.net.

I started using the alternate domain when using the regular pokeapi.co was being blocked. For some reason, even though I am making the call directly to HTTPS://pokeapi.co/api/v2/pokemon/1, I keep getting a CORS error where it seems like its still calling directly to HTTP.

Example: https://vibrant-yonath-715bf2.netlify.com/

**Comment by cmmartti** [comment]
@SilasOtoko Try adding a trailing slash. For some reason, I was getting a CORS error without one. Currently, PokéAPI is hosted on a Digital Ocean server, but we will shortly move to completely static hosting on Firebase, which should fix this.

If adding a trailing slash doesn't work, try using https://pokeapi-215911.firebaseapp.com/api/v2/ instead. That's the temporary Firebase app URL for PokéAPI that we will be moving to at some point. I'm curious to know whether that solves your problem or not.

**Comment by SilasOtoko** [comment]
The Firebase URL worked perfectly, and it seems much faster too! Thanks! :)

**Comment by cmmartti** [comment]
Good to hear. Just be sure to switch back to pokeapi.co once the move to Firebase Hosting is complete.

**Comment by SilasOtoko** [comment]
Good to know. Thanks :)

**Comment by GeraldAburto** [comment]
Hi
I'm creating an angularjs client application that consumes this api
just for didactics purposes.

I getting the same error.

this is what i'm doing:
var getPokemons = function(){
   return $http({
     method: 'GET',
     url: 'https://pokeapi.co/api/v2/pokemon/'
   });
}

**Comment by Naramsim** [comment]
Do you get these headers in the response? If you try from your browser? Or maybe using `curl` or `wget`

```
access-control-allow-headers: Authorization, Origin, X-Requested-With, Content-Type, Accept
access-control-allow-methods: GET, OPTIONS
access-control-allow-origin: *
```

**Comment by GeraldAburto** [comment]
I get these headers only when i make the request from postman
i can't make it works in angularjs

**Comment by cmmartti** [comment]
@GeraldAburto I've never used Angular and don't know how the `$http` function works. Is there any way to set the mode to `cors` like in the `fetch` API?

**Comment by Naramsim** [comment]
You could also consider to use our browser wrapper. https://github.com/PokeAPI/pokeapi-js-wrapper

**Comment by Naramsim** [comment]
Always use HTTPS to avoid CORS issues.

**Comment by emirhanyagci** [comment]
I still get this error i finished project it was working after couple days i checked project for is everything ok ? but i'm getting this error, when i try request postman url working but in my app does not 

![image](https://github.com/PokeAPI/pokeapi/assets/66957950/b53baf1b-dfbd-4b52-ad7b-3db098215cd3)

this is how my code look like like i said it was working greatly until a few days ago
```javascript
import axios from "axios";
import { POKE_PER_PAGE, MAX_POKE_COUNT } from "../helpers/constants";
const axiosInstance = axios.create({
  baseURL: `https://pokeapi.co/api/v2/`,
});
export const getPokemons = (page) => {
  const offSet = POKE_PER_PAGE * (page - 1);

  return axiosInstance.get(`pokemon?offset=${offSet}&limit=${POKE_PER_PAGE}`);
};

export const getPokemonWithId = (pokeId) => {
  return axiosInstance.get(`/pokemon/${pokeId}`);
};
export const getPokemonWithUrl = (url) => {
  return axios.get(url);
};

```
