### ISSUE TITLE
Arceus forms

### ISSUE THREAD

**Issue by Benjymack** [PokeAPI/pokeapi#291]
Hello, I am creating a Pokemon fan game using Pokeapi for data about Pokemon, items etc. I have looked at the [arceus Pokemon data](http://pokeapi.co/api/v2/pokemon/493) and I notices that if different forms are under forms. I would have thought (like with mega evolution) that they are separate Pokemon linked by the [arceus species page](http://pokeapi.co/api/v2/pokemon-species/493). Instead they are under Pokemon forms which don't have separate stats and types. The main reason I am querying this is the fact that Arceus has many different types and I am wondering if they should be in separate Pokemon data files.

**Comment by zaneadix** [comment]
We snag the data from veekun's pokedex repo and my understanding is they rip directly from the games and map pretty much one to one how the games use the data,

**Comment by Benjymack** [comment]
Interesting, thanks for the answer!
