### ISSUE TITLE
pokemon/129/encounters 502 Error

### ISSUE THREAD

**Issue by ace196** [PokeAPI/pokeapi#293]
When trying to access http://pokeapi.co/api/v2/pokemon/129/encounters I get a 502 bad gateway error instead of JSON data. It has been like this for the past few days. Same when trying in browser or clientside script. Others work fine, but when I try to access this one, the whole page stops responding for a few minutes.

**Comment by tdmalone** [comment]
Could someone re-open this one? Still appears to be an issue. Thx!

**Comment by MestreLion** [comment]
Same here! That poor ubiquitous Magikarp seems to be bringing the server down... All hail his mighty splash, struggle, and his billion encounters!

**Comment by tdmalone** [comment]
Haha I have the ability to reopen now, so I've just gone ahead and done that ;)

**Comment by enriquezm** [comment]
Has this been solved? It seems to be fine now.

**Comment by sargunv** [comment]
Yep, the move to static files has solved this.
