### ISSUE TITLE
Encounters por pokemons with id < 10

### ISSUE THREAD

**Issue by TorchwoodPL** [PokeAPI/pokeapi#297]
All the urls: http://pokeapi.co/api/v2/pokemon/[ID]/encounters witch [ID] < 10 returns only:
[ ]

What could be a problem?

**Comment by SidMcLaughlin** [comment]
@TorchwoodPL It looks like there is no data in [encounters.csv](https://github.com/PokeAPI/pokeapi/blob/master/data/v2/csv/encounters.csv) for pokemon_id < 10.  I checked https://veekun.com which seems to be the source of the data and they too have missing locations https://veekun.com/dex/pokemon/bulbasaur/locations

**Comment by Naramsim** [comment]
Closing since we fetch data from Veekun, maybe we could open an issue there.
