### ISSUE TITLE
asking for captcha code 

### ISSUE THREAD

**Issue by arvindsinghtomar** [PokeAPI/pokeapi#298]
when i tried to call Api from retrofit android it is asking me to check captcha code before api response. How to do i bypass captcha code ?

**Comment by Naramsim** [comment]
Where are you? In Asia?

**Comment by arvindsinghtomar** [comment]
yes India , it is working well in real devices but not working on emulators.

**Comment by Naramsim** [comment]
Maybe it is a problem of UA string

**Comment by aldoKelvianto** [comment]
This happens to my devices too. My current solution is to use VPN and connect with United States API

**Comment by phalt** [comment]
About a year ago we had sustained DDOS traffic from East Asia, with no obvious way to figure out the IP address range. Solution was to heavily limit traffic from there through Cloudflare. There isn't much I can do here I'm afraid.
