### ISSUE TITLE
Update to Python 3

### ISSUE THREAD

**Issue by cweeks12** [PokeAPI/pokeapi#301]
I'm working on updating the api to Python 3. I'm not sure how long this will take; it seems simple right now, but I'm just starting on it. I'm opening this issue to let people know I'm working on it. I forked the repo and you can see the progress here: https://github.com/cweeks12/pokeapi.

**Comment by Naramsim** [comment]
Perfect, thanks for your effort.

The main impact on performance will come when upgrading Django dependency. Remember to target Python 3.6

**Comment by Naramsim** [comment]
Also, @cweeks12, if you want you can drop Django, which is a little bit slow, and use [Sanic](https://github.com/channelcat/sanic)

Obviously, you can replace only the API server, not the entire docs server(which uses Django templating)

**Comment by cweeks12** [comment]
I really like what I'm seeing with that Sanic. I think I'll move it all over to that.

I haven't looked at the code a ton yet, but should I move the API v1 to Python 3/Sanic as well? Or should I just focus on moving v2 and dropping v1?

**Comment by Naramsim** [comment]
Nono, v1 is not maintained anymore, just leave as it is now, or remove it, to make things clear

**Comment by cweeks12** [comment]
Okay, I think I've decided that I'm going to use Sanic instead of django for the framework, and then instead of using the built-in django database api, I think I may move over to peewee and just keep the sqlite database intact. Thoughts?

**Comment by cweeks12** [comment]
This [stackoverflow answer](https://stackoverflow.com/questions/39803746/peewee-and-peewee-async-why-is-async-slower) has me leaning towards just regular peewee, instead of the async flavor, but I just want know what everyone else thinks, if I'm on the right track or completely off the rails

**Comment by Naramsim** [comment]
Yep, the important is to have the API working, once it is working we can think about non-API relative things, such as Docs and Landing page. But it will be pretty simple to plug them in since those are HTML pages.

**Comment by Naramsim** [comment]
@cweeks12 keep in mind that on Pokeapi server we are using Postgres, SQLite is just a quick alternative.
https://github.com/PokeAPI/pokeapi/blob/8ce2bedf063207ea45a20143d5d7ac87f800cfbd/data/v2/build.py#L73

**Comment by phalt** [comment]
Few things:

1) Please don't remove V1. It is still the most used part of the API and will break a bunch of old integrations if we remove it. (the price of managing APIs is always maintaining versions).
2) Moving away from Django will be tricky, considering the server configuration is built around it!
3) If you're planning on using SQLite in production you'll have a tricky time with the number of read/writes. As SQLite is basically just a file, so you're blocked by file I/O. Better to use a true DB or maybe even just stick it all in Redis cache.

**Comment by Naramsim** [comment]
Maybe @phalt we can create a totally different API server and run it alongside V1 and V2. Thus creating a new repo with @cweeks12 work.

**Comment by phalt** [comment]
That would work. That type of URL routing/nginx config is beyond me, though! So some contributions there would be useful.

**Comment by cweeks12** [comment]
Ah, I assumed since SQLite built on my machine, that's what was used in production. My bad. I will use PostgreSQL.

I think from what I'm seeing, I am now leaning towards just updating the Django to the latest version and making it compatible with Python 3. That sounds like the simplest fix right now. I don't want to have to have to spin up a completely different server just to support Python 3. That could be a project for the future, but I think for right now, to get off of Python 2, I'll just stick with Django and everything that's existing already in the project.

Thanks for the help and advice, guys.

**Comment by phalt** [comment]
@cweeks12 no problem. Sorry I didn't chime in earlier. I've done a fair few Py2k -> Py3k upgrades in the past. I know PokeAPI has some stuff to be changed to support it, but I think we can get it into a Py3k state with less effort than we assume.

**Comment by cweeks12** [comment]
@phalt That's okay. This is my first upgrade like this, and frankly my first experience with web frameworks/anything web, so I think it's a big learning experience for me, since I saw the [Beginner Friendly] tag. I'll see if I can make those changes quick and get them pulled in for everyone and we'll save the big update for another day.

**Comment by phalt** [comment]
@cweeks12 what I've found with Py3k upgrades is: it's mostly just figuring out how to do the same line of code in the new format, and then all places in the code just need to be copy/pasted to that. It's tedious more than difficult :) But it is a good way to learn!

**Comment by cweeks12** [comment]
I was a lot busier than I thought the second half of my summer, and I wasn't able to do much upgrading, and now I'm back in school, so I can't really do anything on this anymore. Sorry guys, but someone else is going to have to do this.

**Comment by phalt** [comment]
No problem man, life comes first.

**Comment by SiddharthaMishra** [comment]
I'd like to try taking this up in my free time. Any advice before I get started?

**Comment by Naramsim** [comment]
What I would suggest you is to first try to update all the python
dependencies, especially Django since right now a lot of the methods used
here are deprecated and no longer maintained in the latest Django. Then if
every thing works, try to update to python 3. Cheers and thanks!

**Comment by SiddharthaMishra** [comment]
Since max_lengths of the IntegerFields of models has been depreciated, I was adding MaxValueValidators to them instead. I was wondering why the max length of the release year of pokemon.models.Game needed to be 6. I was also curious why hits.models.ResourceView has to have a max length of 1000 (and therefore max value of 10^1001).
Should I just work on a direct translation of the code for now and worry about the confusing values later?

**Comment by Naramsim** [comment]
I think you could just work on anything you want. If limits are too low,
raise them. It is incredible that you are working on it, thanks very much

**Comment by cmmartti** [comment]
Hey, great to hear that somebody's working on updating to Python3. I'm working on adding a GraphQL endpoint, but I didn't bother updating it from Python2. If you get it done, submit a PR. Hopefully @phalt can merge it so I can pull the changes into my code.

As far as the GraphQL endpoint goes, I've figured out how to use the existing v2 models so the same data source can be used, as well as using Dataloader to not hammer the database with every query. I'm working on continuing to flesh out the schema. After that I'll see if I can figure out a way to add some rate-limiting to prevent abusive queries and it should be good to go.
