### ISSUE TITLE
Add Generation 7

### ISSUE THREAD

**Issue by JacobDB** [PokeAPI/pokeapi#303]
It appears that [generation 7 pokemon](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_National_Pok%C3%A9dex_number#Generation_VII) are missing from the API.

**Comment by Naramsim** [comment]
We all know, we take our data from veekun. Apparently, the data was added to their [CSV files](https://github.com/veekun/pokedex/blob/master/pokedex/data/csv/pokemon.csv) as suggested in the slack channel.

@phalt, could you please try to build the new database on the official server and see if it works with no additional changes to the codebase?

Thanks, @JacobDB for pointing that out.

**Comment by Naramsim** [comment]
Tomorrow I will open the PR, everything works 🎆

**Comment by KingDGrizzle** [comment]
_bump_

Any news about this? It would be awesome to get Gen 7, so that we can get any info "required" by our "services" (should we need to :P)

**Comment by Naramsim** [comment]
@KingDGrizzle while waiting for merge, you can spin up a local server with this PR https://github.com/PokeAPI/pokeapi/pull/305
