### ISSUE TITLE
Move flavor_text_entries shows the wrong data type.

### ISSUE THREAD

**Issue by iHaruku** [PokeAPI/pokeapi#304]
On the documentation for Move ([docs](https://pokeapi.co/docsv2/#moves)) the flavor_text_entries shows a data type of Move, but it should be a list of MoveFlavorText. Another thought... MoveFlavorText and VersionGroupFlavorText are the same thing. They have identical properties. Was that intentional?

**Comment by Naramsim** [comment]
> `"flavor_text_entries": [`

flavor_text_entries is an array of MoveFlavorText, note the square bracket.

Yes, it probably was intentional.

**Comment by iHaruku** [comment]
Yes, but if you scroll down it shows flavor_text_entries as type Move.

```
Name                  Description            Data Type
flavor_text_entries    ...                   Move
```

**Comment by Naramsim** [comment]
> Yes, but if you scroll down it shows flavor_text_entries as type Move.

Yeah, but if you click it it will bring you to the correct moveflavortext

So it is just a typo. I'm closing this
