### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by mbapna123** [PokeAPI/pokeapi#306]
This is a very specific question but I am trying to access the PokeAPI V1 and V2 and they seem to behave differently.
My code for both is

$.ajax({
  type:"GET",
  dataType: "jsonp",
  url: (Uone or Utwo)
  success: function(dataone)
  {*somefunction
  }})

. When I put in the url from the pokeAPI V1 it works but when I put in the url from the pokeAPI V2 it gives me an error that Unexpected Error occured: Unexpected Syntax : found. I read about this on StackOverflow and it appears that the file is not truly a JSON file. I tried everything to fix this issue but it didn't work.

In a more general sense, I was receiving error messages that said "NO ACCESS HEADERS. BLOCKED BY CROSS ORIGIN RESOURCE SHARING" or something like that. I downloaded a chrome extension which fixed this issue but it is not a good one. I tried two ways to permanently fix this solution, one which was to add "?/callback?" to the end of my URL, and the other to add datatype JSONP to my ajax call. This worked for the V1 API but not for the V2 API. I have no clue why.

**Comment by Naramsim** [comment]
The issue abaout CORS is related to #289. Discuss the issue there.

dataType in your example should be "json", but I'm not a jQuery master.
