### ISSUE TITLE
Wrong evolution chain for Wurmple?

### ISSUE THREAD

**Issue by HansWurst90** [PokeAPI/pokeapi#307]
[JSON-Response](https://pokeapi.co/api/v2/evolution-chain/135/)

To me it looks like the chain shows:
wurmple -> silcoon -> ( beautifly | cascoon - > dustox )

I hope this visualization makes it clear.

**Comment by Naramsim** [comment]
Refer to #163, when #305 will be merged it will be fixed.

**Comment by HansWurst90** [comment]
Oh, sorry, I did not see that issue. My bad.
