### ISSUE TITLE
animation sprites

### ISSUE THREAD

**Issue by usagi-f** [PokeAPI/pokeapi#311]
I want to use animate sprites, but only the still picture (png) can be referred from the current API.
Can not replace with animation gif ?

### e.g.
**png**
https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/722.png

**gif**
http://www.pkparaiso.com/imagenes/sol-luna/sprites/animados/rowlet.gif

---

The source is listed here.
https://www.pkparaiso.com/pokedex/rowlet.php

**Comment by phalt** [comment]
Let's add them, not replace the existing ones.

**Comment by Naramsim** [comment]
Images should be added to the Sprites' repo

**Comment by usagi-f** [comment]
sounds good 😋

I imagined the following format.

```
"sprites": {
    "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png",
    ....
    "front_animate": "https://example.com/path/to/file.gif"
},
```
or
```
"sprites": {
    "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png",
    ....
},
"sprites_animate": {
     "front_default": "https://example.com/path/to/file.gif"
},
```

Recommend the latter.

**Comment by Naramsim** [comment]
Yep, if somebody wants to scrape them could use this website: http://play.pokemonshowdown.com/sprites/xyani/

I already made a script for scraping on that website 60fps GIFS: https://github.com/Naramsim/PokemonSpritesScraper

**Comment by tdmalone** [comment]
Feel free to make use of the animations in here if you like: https://github.com/tdmalone/pokecss-media

**Comment by Naramsim** [comment]
Closing in favor of: https://github.com/PokeAPI/sprites/issues/12
