### ISSUE TITLE
Documentation shows HTTP instead of HTTPS

### ISSUE THREAD

**Issue by JordanMajd** [PokeAPI/pokeapi#312]
The home page docs show `http://pokeapi.co/api/v2/` as the URL but hitting it returns a `301 Moved Permanently` to `https://pokeapi.co/api/v2/`. 

Normally this is not much of an issue as most tools automatically handle the redirect, but some do not.  `curl` is one of these.  

I normally use `curl` to test out an API and was curious when `curl http://pokeapi.co/api/v2/` did not print anything. I ran `curl -v http://pokeapi.co/api/v2/` which returned:

```
* Hostname was NOT found in DNS cache
*   Trying 2400:cb00:2048:1::6812:3b8f...
* Connected to pokeapi.co (2400:cb00:2048:1::6812:3b8f) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: pokeapi.co
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Date: Sat, 28 Oct 2017 02:34:03 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< Cache-Control: max-age=3600
< Expires: Sat, 28 Oct 2017 03:34:03 GMT
< Location: https://pokeapi.co/
* Server cloudflare-nginx is not blacklisted
< Server: cloudflare-nginx
< CF-RAY: 3b4a7e6b756d5011-DEN
<
* Connection #0 to host pokeapi.co left intact
```

Displaying `https` instead of `http` in the docs would allow the client to directly access the resource without the client needing to redirect the `301` response. 

I'd be happy to submit a PR if this is a desired behavior.

**Comment by tdmalone** [comment]
I _think_ the https was a recent move, so I’m sure updating the docs wouldn’t go astray!

As a side note - and you may know this anyway - you can pass the ‘--location’ switch to curl to cause it to follow redirects.

**Comment by phalt** [comment]
It was very recent. A PR will a grep/replace of http -> https would be easily accepted :)

**Comment by Naramsim** [comment]
Docs now always use HTTPS
