### ISSUE TITLE
pokeapi.co’s server DNS address could not be found.

### ISSUE THREAD

**Issue by darkdrew** [PokeAPI/pokeapi#313]
Hi, is the pokeapi no longer available? Today i tried to enter the page: http://pokeapi.co/ it does not work anymore. Can anyone help me?

**Comment by VidushanK** [comment]
Doesn't work for me as well

**Comment by phalt** [comment]
Lol I forgot to renew the domain

**Comment by phalt** [comment]
Okay paid. Might take a while to come back up.

**Comment by darkdrew** [comment]
thank you!
