### ISSUE TITLE
Pokemon Ultra Sun and Ultra Moon data needed

### ISSUE THREAD

**Issue by Smethan** [PokeAPI/pokeapi#315]
Pokemon Ultra sun and moon added some new pokemon and forms which seem to have yet to be added to the database, like the new forms of necrozma and dusk lycanroc.

**Comment by Naramsim** [comment]
Yep, you are right: even veekun has released that information

We can definitely add them

https://github.com/veekun/pokedex/tree/master/pokedex/data/csv

**Comment by tdmalone** [comment]
Closing as an open PR now handles this:
https://github.com/PokeAPI/pokeapi/pull/317
