### ISSUE TITLE
Missing encounters for Gen 2 (Gold, Silver, Crystal)

### ISSUE THREAD

**Issue by MestreLion** [PokeAPI/pokeapi#318]
data/v2/csv/encounters.csv has no data for version_id 4, 5 or 6

**Comment by Naramsim** [comment]
Thanks for submitting the issue, please open a copy on [Veekun](https://github.com/veekun/pokedex/) since we gather all the data from them

**Comment by MestreLion** [comment]
There is already veekun/pokedex#201, opened more than an year ago. Shall we upvote/voice there or rather open a new issue?

**Comment by Naramsim** [comment]
From my side I added a thumb up on the Veekun issue
