### ISSUE TITLE
Java API - display details of pokemon

### ISSUE THREAD

**Issue by tartreau** [PokeAPI/pokeapi#319]
Hi ! 
I'm working on a (very) little Pokedex thanks to the API. 
 
Thanks to this tuto : 
https://www.youtube.com/watch?v=xQn8u4Htib4
I'm able to display all Pokemon (and there name and there number).

Now I want to display details of a specific Pokémon when I clic on an item but I don't know how to use the API to display some details (like Evolutions, height, weight...)

Thanks for your work, its great by the way !

**Comment by Naramsim** [comment]
Hi @tartreau, it is better to use our Slack channel for this kind of questions. We have a channel named "help" there. 

Check out the instructions in the readme in order to signup
