### ISSUE TITLE
Made an example JsFiddle

### ISSUE THREAD

**Issue by DanLatimer** [PokeAPI/pokeapi#322]
Didn't really know where to post this so sorry if this is a bad spot (feel free to close the issue). Just thought some people might be interested in this JsFiddle I wrote

https://jsfiddle.net/torcp0r3/8/

**Comment by tdmalone** [comment]
We'd love to see it in the #showcase channel on our Slack team! :) See https://pokeapi-slack-invite.herokuapp.com/ to sign up and then log in at https://pokeapi.slack.com/
