### ISSUE TITLE
Asynchronous Python Wrapper?

### ISSUE THREAD

**Issue by AtomToast** [PokeAPI/pokeapi#324]
I was deep into my project when I embarrassingly noticed that the pokeapi wrapper I used ([PokeBase](https://github.com/GregHilmes/pokebase) by Greg Hilmes) is not asynchronous.

Now I have the issue that I am not particularly experienced in this field and the wrapper is already fairly deeply integrated into the project.
So does anybody already have some sort of asynchronous python wrapper or would be willing to create one?

Any help would be greatly appreciated as I don't think that I could create something efficient in a timely manner!

**Comment by Naramsim** [comment]
Hello, this is not the correct place to discuss regarding a wrapper. Better to discuss directly on the wrapper repo. I'm closing this issue and opening a new one on @GregHilmes repo.

https://github.com/GregHilmes/pokebase/issues/7
