### ISSUE TITLE
How can I get all Alola pokémon including alolan forms?

### ISSUE THREAD

**Issue by thechief389** [PokeAPI/pokeapi#327]
I'm working on a command-line Pokémon Sun and Moon game and I'm trying to figure out how to get the alola id and name of all the Pokémon in alola. The entry for the Alolan Raichu has the id 10100 and the name is "raichu-alola", rather than 26 and "raichu".(It would be very confusing for two entries to have the same name)

How can I get the alola id and the species name of all the pokemon?

**Comment by Naramsim** [comment]
https://pokeapi.co/api/v2/pokemon/10100/

**Comment by thechief389** [comment]
That doesn’t have the original name or Id though.

**Comment by thechief389** [comment]
It has the species name though.

**Comment by Naramsim** [comment]
https://pokeapi.co/api/v2/pokemon/raichu-alola/

You can query it even by name

**Comment by haynesherway** [comment]
Are sprites for alolan forms going to be available at any point? They currently return as null.

**Comment by Naramsim** [comment]
Probably not, not soon

**Comment by haynesherway** [comment]
I see that some of the sprites are available and even in the repo, what needs to be done to get that in the right spots?

**Comment by Naramsim** [comment]
Restart the server with all the sprites in the correct location. Anyway, it is recommended to clone this repo locally and serve by yourself the sprites

**Comment by Naramsim** [comment]
To get all the pokemon species of generation7 use https://pokeapi.co/api/v2/generation/7/ `.pokemon_species`

To get all the pokemon species of the updated alola pokedex use https://pokeapi.co/api/v2/pokedex/21/ `.pokemon_entries`

Then for each pokemon you should see if they have an alolan form
