### ISSUE TITLE
Can't get any data from API with emberjs

### ISSUE THREAD

**Issue by cassianpry** [PokeAPI/pokeapi#328]
Hi, I'm studying EmberJS. I downloaded and installed locally to avoid many requests and while I was studying, I used a website that was made emberjs and uses the API to guide me in some parts of the project.

Two weeks ago the site stopped listing the Pokemons. I changed my host to https: // pokeapi and got the same error. Has anything changed in the way to get API data? Because not only in EmberJS does not work anymore, in AngularJS and ReacktJS stopped getting API data

Sorry for my english and thank you for the Pokeapi project.

**Comment by Naramsim** [comment]
Hello, The problem is not with Ember or any other kind of framework. The problem is that Pokeapi might be down or Cloudflare not setting up CORS headers (most likely).

Check in dev tool in the network panel what"s going on.

**Comment by cassianpry** [comment]
Thanks, it was Cloudflare. Problem solved.
