### ISSUE TITLE
Missing location_area_encounters

### ISSUE THREAD

**Issue by jrubinator** [PokeAPI/pokeapi#331]
It appears that at least a few pokemon (seemingly many) are missing entries in their `location_area_encounters` endpoint.

For instance, [Dratini's endpoint](https://pokeapi.co/api/v2/pokemon/147/encounters) does not list silver or gold, though it's definitely catchable in [Dragon's Den](https://bulbapedia.bulbagarden.net/wiki/Dragon%27s_Den) (there may be other locations as well, I'm not sure).

I randomly spot-checked a few others - [Girafarig](https://pokeapi.co/api/v2/pokemon/203/encounters) and [Jynx](https://pokeapi.co/api/v2/pokemon/124/encounters). Gold and silver are also conspicuously absent from their URLs. Looking even more closely, red and blue are missing entirely from Jynx's results, and only point to the Safari Zone for Dratini.

PS. There are some entries for "heartgold", but that's a different set of version details.

**Comment by Naramsim** [comment]
Hi, we don't use our data. 

Can you spot if you can find Dratini's endpoint in Veekun? https://github.com/veekun/pokedex/tree/master/pokedex/data/csv (we take the data from them)

**Comment by Naramsim** [comment]
Good one, I've already thumbed it up 😄 

Closing for https://github.com/veekun/pokedex/issues/201
