### ISSUE TITLE
encounters return is different than other endpoints'

### ISSUE THREAD

**Issue by jrubinator** [PokeAPI/pokeapi#332]
Right now the encounters endpoint lives at `https://pokeapi.co/api/v2/pokemon/{id}/encounters`

For a given id, the URL returns a list, rather than a hash. On the other hand, the endpoint URLs (eg. `/api/v2/pokemon`) return very similar data, but prefix that data with `results:` Would it make sense to do this here? Unfortunately, that's not a backwards-compatible change.

I suggest this because I believe it would make it easier for API clients to handle the response - see eg.
https://github.com/GregHilmes/pokebase/issues/10

**Comment by Naramsim** [comment]
Hello, back in time the encounter endpoint wasn't there, but part of `/api/v2/pokemon/{id}/`. It was created to lighten the responses of this pokemon endpoint. So it was a quick improvement. Right now the repository is in a stalemate state, and probably no one will implement this alignment with `/api/v2/pokemon/`

**Comment by jrubinator** [comment]
Interesting - that migration makes sense.

I guess I was wondering if the following change makes sense at the last line of `pokemon_v2/urls.py`:
```
-        return Response(encounters_list)
+        return Response({'results': encounters_list})
```

I haven't worked with Django before, or I might be able to suggest something more mature (with proper pagination). That sounds like the alignment you doubt will happen though.

Let me know what you think.

**Comment by Naramsim** [comment]
Yeah, probably is that simple fix 😄 So maybe you can open a PR and put me in the 'request review' and one day maybe it will be merged, but this change obviously could break lots of applications. So we have to be careful about deciding what to do.

**Comment by Naramsim** [comment]
Closing this issue and marking it for a future v3 version.

Right now we cannot change the endpoint format since it's used by many people. We acknowledge that your proposed solution would be the best option.
