### ISSUE TITLE
Sun and Moon encouter data missing

### ISSUE THREAD

**Issue by lazyBisa** [PokeAPI/pokeapi#336]
### Expected:
- encounters.csv contains entries with version nr. 27 and 28.

### Observed:
- highest version id in the file is 24 (Pokémon Y)
- 25 and 26 (Omega Ruby and Sapphire) are also missing.

Respective endpoint also doesn't return encounter data for Sun/Moon
E.g:
#### Araquanid (https://pokeapi.co/api/v2/pokemon/752/encounters):
- no encounter information at all
#### Caterpie (https://pokeapi.co/api/v2/pokemon/10/encounters)
- no Sun/Moon encounter information

latest update to encouters.csv (9203a0d2) only made some modifications to firered and leafgreen encouters, PR #317 does not add encounter information since veekun also does not contain it yet (9. May 18)

**Comment by Naramsim** [comment]
There is a PR open.

What does SM mean?

**Comment by lazyBisa** [comment]
PR and veekun do not contain encounter information either

**Comment by Naramsim** [comment]
About Araquanid I don't know what to say. Maybe Veekun updated their entries and we could try re-fetch them and see if Araquanid is updated. Are you sure it can be caught?

We found our API on Veekun, so if Veekun does not have them our API will not have them.

So we have to wait for Veekun to update.
