### ISSUE TITLE
Evolution is hard to show

### ISSUE THREAD

**Issue by alexd99** [PokeAPI/pokeapi#337]
On the evolution endpoint, the evolution id's do not match the pokemon id's making it near impossible to show an evolution chain for the pokemon. It would be awesome to have those id's match up.

**Comment by cmmartti** [comment]
If you're trying to show an evolution chain for a particular Pokémon, you'll have to get the species of that Pokémon first, and then get the evolution chain for the species.

Keep in mind that pokemon-species and pokemon are two different resources. Some species have different Pokémon variations (e.g. red and blue Gyrados), so different endpoints and IDs are needed. Are you sure you don't want the species to begin with?

**Comment by alexd99** [comment]
Either way would work. How I have my project set up is that you can select a pokemon and get all of their moves and stats, I could just use a second API call to pull the species information to get more information about the pokemon, and more importantly the evolution.

**Comment by denisferia** [comment]
> If you're trying to show an evolution chain for a particular Pokémon, you'll have to get the species of that Pokémon first, and then get the evolution chain for the species.
> 
> Keep in mind that pokemon-species and pokemon are two different resources. Some species have different Pokémon variations (e.g. red and blue Gyrados), so different endpoints and IDs are needed. Are you sure you don't want the species to begin with?

Hi!
I am trying to achieve what the OP states. The evolution chain request has an ID as param that is nowhere to be found on the the pokemon species response. E.g.: Charmander's id is "4", but https://pokeapi.co/api/v2/evolution-chain/4/ throws Caterpie's chain. But https://pokeapi.co/api/v2/evolution-chain/2/ throw's Charmander's chain.

Where does that ID come from? Is there way in which I don't need to nest multiple API calls?

**Comment by cmmartti** [comment]
The IDs of different resources have no correlation, and you should generally not be handling IDs directly at all. That is why they are not exposed as values in the results. Instead, treat URLs as opaque values and don't try to split them or assemble them.

The location of the *PokemonSpecies* resource for Charmander is https://pokeapi.co/api/v2/pokemon-species/4. If you inspect this object, you will see the key `evolution_chain` with the value `{"url": "https://pokeapi.co/api/v2/evolution-chain/2/"}`. The `url` string is what you're looking for. Pop that directly into a new `Fetch` call and you will get the resulting *EvolutionChain* resource.

The PokéAPI REST API is not a sophisticated API, and it is based on the original REST tenet that everything is linked, and you only need to follow the links to get what you're looking for. This naturally results in a lot of chained API calls, and that's fine. If you want something more sophisticated, check out the GraphQL API that @Naramsim put together: https://pokeapi.co/docs/graphql

**Comment by cmmartti** [comment]
Here it is in the playground tool on the homepage at pokeapi.co:

![Screenshot_20210919-233159_Firefox Nightly](https://user-images.githubusercontent.com/6448223/133955031-1627352e-a94e-4da0-8411-4d1e76be2170.png)
