### ISSUE TITLE
Several Evolution Chains do not Exist

### ISSUE THREAD

**Issue by KadinTucker** [PokeAPI/pokeapi#338]
Hello,
While iterating through the evolution chains, I found that some of them do not exist and give 404 errors. The ones I found were numbers 211 and 222 (/evolution-chains/211, /evolution-chains/222), though there may be more. 
Thank you,
Kadin Tucker

**Comment by KadinTucker** [comment]
As far as I can tell, these errors are a result of the addition of extra evolutions (#210 is where Budew/Roserade might be, but they are with Roselia, #222 is where Ambipom is). While there do not seem to be any missing evolutions, it's kind of sloppy to have missing ones in between. Plus, not all evolutions added later in the pokedex have this issue:  Crobat and Blissey for example do not cause any errors. 

Thank you for your consideration,
Kadin Tucker

**Comment by KadinTucker** [comment]
Additionally, the count parameter in evolution-chains accurately gives the number of evolutions but the last index is not 415 as the count is, rather 423. This causes some problems when searching through each evolution chain and is a result of the aforementioned issue. 

Thanks,
Kadin Tucker

**Comment by cmmartti** [comment]
Shouldn't you be treating the ID numbers as opaque strings anyway? Primary keys aren't guaranteed to be consecutive and shouldn't be paginated over. That's why the https://pokeapi.co/api/v2/evolution-chain/ endpoint allows you to page through the results using limit and offset.

As an observation, GraphQL-Relay base64 transforms its node IDs specifically to discourage such practices.

**Comment by tdmalone** [comment]
I'm going to close this for the same reason as #329, and as explained by @cmmartti above. IDs are not always guaranteed to be consecutive.

If there's a use-case we're missing or if there's a URL referenced somewhere for an evolution chain that is broken, please feel free to re-open. At the moment my understanding is that the IDs are being guessed, which doesn't indicate a bug :)
