### ISSUE TITLE
Django not waiting Postgres to start up inside the standalone Docker container

### ISSUE THREAD

**Issue by ShinySaana** [PokeAPI/pokeapi#342]
When starting the standalone PokeAPI Docker container (without docker-compose), Django tries to connect to Postgres while it is starting up, which result in an unhandeld exception. Django then does not try to reconnect again.

```
Unhandled exception in thread started by <function wrapper at 0x7f5a969d49b0>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check_migrations()

  [...]

  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql_psycopg2/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: FATAL:  the database system is starting up
FATAL:  the database system is starting up
```

Everytime I launch a docker container with `sudo docker run -d -p 8000:8000 pokeapi`, this error shows up. The pokeapi image was built using a clean repo.

The container should wait for the database to start up then launch Django, or Django should catch the exception, wait a bit, and retry. Using an image like [phusion/baseimage-docker](https://github.com/phusion/baseimage-docker) might be adapted to PokeAPI's case if going for the first solution.

A workaround is to execute Django by hand directly into the containter after waiting for Postgres to start up, i.e `docker exec CONTAINER_NAME python manage.py runserver --settings=config.docker 0.0.0.0:8000`, which then works as expected.

**Comment by Naramsim** [comment]
PLease use our docker compose guide

**Comment by Naramsim** [comment]
Closing since the Docker standalone container is deprecated.

I'll remove the Dockerfile from the repo, also.
