### ISSUE TITLE
MultipleObjectsReturned get() returned more than one ResourceView

### ISSUE THREAD

**Issue by dcantah** [PokeAPI/pokeapi#343]
This has now happened twice. Once when I initially set up the api following the standard instructions and using sqlite. And just now a second time when setting it up on postgres. Both times the api works fine for about a day and then starts displaying this randomly. This is the full error with the meaningless info taken off at the bottom. This error displays on any endpoint with an id or name that needs to be entered. For example /api/v2/pokemon/ will work but api/v2/pokemon/1 will not. Same with all of the rest with similar setups. 

MultipleObjectsReturned at /api/v2/pokemon-form/23/
get() returned more than one ResourceView -- it returned 3!

Request Method: GET
Request URL: http://localhost:8000/api/v2/pokemon-form/23/
Django Version: 1.8.14
Python Executable: /Users/MacUser/pokeapitest/pokeapi/bin/python
Python Version: 2.7.10
Python Path: ['/Users/MacUser/pokeapitest/pokeapi/pokeapi', '/Users/MacUser/pokeapitest/pokeapi/lib/python27.zip', '/Users/MacUser/pokeapitest/pokeapi/lib/python2.7', '/Users/MacUser/pokeapitest/pokeapi/lib/python2.7/plat-darwin', '/Users/MacUser/pokeapitest/pokeapi/lib/python2.7/plat-mac', '/Users/MacUser/pokeapitest/pokeapi/lib/python2.7/plat-mac/lib-scriptpackages', '/Users/MacUser/pokeapitest/pokeapi/lib/python2.7/lib-tk', '/Users/MacUser/pokeapitest/pokeapi/lib/python2.7/lib-old', '/Users/MacUser/pokeapitest/pokeapi/lib/python2.7/lib-dynload', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/Users/MacUser/pokeapitest/pokeapi/lib/python2.7/site-packages']
Server time: Sat, 16 Jun 2018 06:59:18 +0100
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.humanize',
 'corsheaders',
 'rest_framework',
 'markdown_deux',
 'cachalot',
 'tastypie',
 'pokemon',
 'pokemon_v2',
 'hits',
 'alerts')
Installed Middleware:
('corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')

Traceback:
File "/Users/MacUser/pokeapitest/pokeapi/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/MacUser/pokeapitest/pokeapi/lib/python2.7/site-packages/django/views/decorators/csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)
File "/Users/MacUser/pokeapitest/pokeapi/lib/python2.7/site-packages/rest_framework/viewsets.py" in view
  90.             return self.dispatch(request, *args, **kwargs)
File "/Users/MacUser/pokeapitest/pokeapi/lib/python2.7/site-packages/rest_framework/views.py" in dispatch
  489.             response = self.handle_exception(exc)
File "/Users/MacUser/pokeapitest/pokeapi/lib/python2.7/site-packages/rest_framework/views.py" in handle_exception
  449.             self.raise_uncaught_exception(exc)
File "/Users/MacUser/pokeapitest/pokeapi/lib/python2.7/site-packages/rest_framework/views.py" in dispatch
  486.             response = handler(request, *args, **kwargs)
File "/Users/MacUser/pokeapitest/pokeapi/pokeapi/pokemon_v2/api.py" in retrieve
  61.         ResourceView.objects.increment_view_count(version=2)
File "/Users/MacUser/pokeapitest/pokeapi/pokeapi/hits/models.py" in increment_view_count
  12.             date=date.today()
File "/Users/MacUser/pokeapitest/pokeapi/lib/python2.7/site-packages/django/db/models/manager.py" in manager_method
  127.                 return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/Users/MacUser/pokeapitest/pokeapi/lib/python2.7/site-packages/django/db/models/query.py" in get_or_create
  405.             return self.get(**lookup), False
File "/Users/MacUser/pokeapitest/pokeapi/lib/python2.7/site-packages/django/db/models/query.py" in get
  338.             (self.model._meta.object_name, num)

Exception Type: MultipleObjectsReturned at /api/v2/pokemon-form/23/
Exception Value: get() returned more than one ResourceView -- it returned 3!
Request information:
GET: No GET data

POST: No POST data

FILES: No FILES data

COOKIES:
tabstyle = 'html-tab'
csrftoken = 'U01dwaVGWNkIrPzDtJLS36dEcsADW8Tw'
_ga = 'GA1.1.2259402.1528584149'
-----------------------------------------------------------------------------
The error when it initially happened on sqlite only listed that 2 ResourceViews were returned however. If anyone has any insight into what's going on I would appreciate it.

**Comment by Cantasaurus** [comment]
If anyone else is having this issue, I've found a somewhat temporary fix. As you can see in the traceback the only traceback related to anything in the actual program is in line 61 of api.py located in the pokemon_v2 folder. If you comment out     

ResourceView.objects.increment_view_count(version=2)

it started to work for me. I'm not going to close this yet as I'd like some insight into why this might be happening. Thanks in advance if anyone has any info!

**Comment by terada46** [comment]
Actually I got almost the same error. 
https://pokeapi.co/api/v2/ ← This url would get my browser being checked and never work in my app built with react native.
 
http://pokeapi.salestock.net/api/v2 ← So I have to use this and have the same issue just like you second day. Thank you for posting this issue. But I still don't understand how to fix it. Could you write more details?

**Comment by Cantasaurus** [comment]
@terada46 I'm running my own version of the api locally as I added the Ultra Sun/Moon Pokemon so if you're just using the already hosted website I can't give any advice :(. If you are running it locally all I did was comment out `ResourceView.objects.increment_view_count(version=2)` on line 61 of the file api.py located in the pokemon_v2 folder. Hope that helped, and just email me if you have anymore questions to keep from flooding this. dannycanter123@gmail.com

**Comment by terada46** [comment]
@Cantasaurus   I see. I am not running it locally.. I am just trying to build an app with this  api for practice.  Thank you for prompt reply  m(._.)m

**Comment by Naramsim** [comment]
Try to update the code and use the compose version. 

Thanks
