### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by MBoberski** [PokeAPI/pokeapi#344]
When I try to import csv do postgress i get:

```
bin/python manage.py shell --settings=config.local
Python 3.5.5 (default, Feb  6 2018, 10:57:32)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from data.v2.build import build_all
Traceback (most recent call last):
  File "/var/www/subdomains/django/pokeapi/lib/python3.5/site-packages/django/core/management/commands/shell.py", line 69, in handle
    self.run_shell(shell=options['interface'])
  File "/var/www/subdomains/django/pokeapi/lib/python3.5/site-packages/django/core/management/commands/shell.py", line 61, in run_shell
    raise ImportError
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/var/www/subdomains/django/pokeapi/data/v2/__init__.py", line 1, in <module>
    from build import *  # NOQA
ImportError: No module named 'build'
```

Any idea why?

**Comment by cmmartti** [comment]
You're probably running into this error because PokéAPI uses Python 2.7, not 3. The "Python2.7" tag is easy to miss (I ran into the same problem).

**Comment by TorchwoodPL** [comment]
I was working I change few thinks to work with pythin 3.5. Issue here is that it do not find module build...

**Comment by cmmartti** [comment]
The first exception looks to be a problem with Django. I don't know what it is though.

The second exception is caused by the use of an implicit relative import in `data/v2/__init__.py`, which is [not supported in Python3](https://www.python.org/dev/peps/pep-0404/#imports). This one won't solve the main problem, but you can fix it by turning it into an explicit relative import:

```
from .build import *
```

**Comment by TorchwoodPL** [comment]
I told you, it was working before a move between VPSes... From python 3.5 to python 3.5...
