### ISSUE TITLE
Documentation API endpoints missing trailing forward slash

### ISSUE THREAD

**Issue by crazycat9x** [PokeAPI/pokeapi#347]
#### api/v2/pokemon/{id or name} should be api/v2/pokemon/{id or name}/

Some HTTP client doesn't follow redirect by default so this could potentially cause issues? And it's probably better if the user requests the correct endpoints in the first place instead of following redirects

**Comment by cmmartti** [comment]
Hi @crazycat9x, thanks for bringing this up. This will be fixed in the [new website](https://github.com/PokeAPI/pokeapi.co).

**Comment by cmmartti** [comment]
[Done!](https://pokeapi.co/docs/v2.html)
