### ISSUE TITLE
Whoops! That's not allowed!

### ISSUE THREAD

**Issue by Fr33dan** [PokeAPI/pokeapi#348]
I have been writing an application that uses the pokeapi. I was working on the project when it started to fail. I went to the site and noticed I get a page saying "Whoops! That's not allowed!" when I try to load anything but the documentation. 

At first I thought maybe I went over the limit as I didn't have caching written yet but I only request one pokemon at random per use. I may have run the debugger enough to request 300 pokemon entries (although it's likely closer to 50-100) but there is no way that I reached 300 requests for the same pokemon this way by myself. I used this as an impetus to write the planned caching code (didn't think my debugging the basics would come anywhere close to the limit) but I can't test it.

I then realized that I could check if it was the limit this with my phone. I detached from the wifi and tried to load a page using my cell service and got the same message with a fresh IP.

**Comment by Naramsim** [comment]
Where are you located? Asia?

**Comment by Fr33dan** [comment]
I am in the US. Turns out I wasn't doing anything wrong. Minutes after I filed this issue this tweet was made about the service being down: https://twitter.com/phalt_/status/1035886294008774656?s=20 . They said they couldn't do anything but followed it up with a message that they tried some things. A little while later it was back up and running. I'm guessing there is possibly still a bug that took it down in the first place so I won't close this myself and leave that to y'alls discretion.

**Comment by JovianPug** [comment]
Yeah I'm having same problem too, what strange everything was working for me 4 hours ago. I'm from EU.

**Comment by Defiled** [comment]
I'm running into this as well when trying to access any endpoint where a name or ID are specified.

**Comment by phalt** [comment]
Hey folks. I was away at a wedding when this happened, and I'm always incredibly busy with my life and day job, so I can't keep responding to these issues. 

If you really need PokéAPI; fork it and spin up a local copy. 
I am not planning on maintaining the service anymore, as whenever people complain about it being down or suggest improvements, I ask for help, but I do not get it.
