### ISSUE TITLE
API Calls do not work any more.

### ISSUE THREAD

**Issue by Foetus6907** [PokeAPI/pokeapi#349]
Hello,

I figure that calls does not work any more.
Example : 
https://pokeapi.co/api/v2/pokemon/1/
if i call this url directly in my browser i do not get the json as reponse. Instead the pokeapi App show a web page with a message saying : Whoops! That's not allowed!

![capture](https://user-images.githubusercontent.com/40607644/44976904-d59a8a00-af66-11e8-8d73-3d8aeaa28d76.PNG)

**Comment by phalt** [comment]
I'm aware. I have no time to fix this. If you need PokéAPI, fork it and spin up your own instance.
