### ISSUE TITLE
Should we reopen unresolved issues & unmerged PRs?

### ISSUE THREAD

**Issue by tdmalone** [PokeAPI/pokeapi#357]
In #350, we've spoken extensively about plans to get support behind PokeAPI now that Paul can no longer actively support it. We've got a good community around this project!

At some stage last year (I think on 12 Jun 2017), Paul started winding down the project before it was revived again, and at this time a number of unmerged pull requests or unresolved issues were closed.

From a comment in #350:
> By coincidence, I am already working on this, though I wasn't aware that there was a closed PR for it...

In the spirit of avoiding duplication of work, I am wondering whether it is worth us reviewing old issues and PRs to reopen those which would be worth further investigation. Doing so will need some commitment to help work through the issues raised within.

Some examples:
- https://github.com/PokeAPI/pokeapi/issues/242
- https://github.com/PokeAPI/pokeapi/issues/259
- https://github.com/PokeAPI/pokeapi/issues/269
- https://github.com/PokeAPI/pokeapi/issues/271
- https://github.com/PokeAPI/pokeapi/issues/272
- https://github.com/PokeAPI/pokeapi/pull/273
- https://github.com/PokeAPI/pokeapi/pull/274
- https://github.com/PokeAPI/pokeapi/issues/276

Thoughts?

**Comment by tdmalone** [comment]
As part of this we could also add new labels and categorise issues etc

**Comment by sargunv** [comment]
Definitely worth doing. Once the optimization PR lands, building and testing these changes should become a breeze.

However, I think it's best to hold off on actually merging anything unrelated to the optimization until the handover is complete and the updated API is live.

**Comment by phalt** [comment]
Probably worth closing this now?
