### ISSUE TITLE
Long-term: static file generation

### ISSUE THREAD

**Issue by neverendingqs** [PokeAPI/pokeapi#358]
Current plan for a short-term solution:

* Host a local version of pokeapi
* Run `ditto` to extract all the JSON files
* Host the JSON files

Long-term, the ideal would be to have a more direct conversion (e.g. convert the CSV files to JSON files).

Before we close off the [PokeAPI - Migration to Static files / Serverless](https://github.com/orgs/PokeAPI/projects/1) project, we should either resolve this or spin up a new issue / project for a more straightforward solution.

**Comment by Naramsim** [comment]
Our current strategy is:
- use docker compose and spin up PokeAPI
- use ditto to scrape all the data
- move the data to api-data
- circleci uploads to firebase all our data
