### ISSUE TITLE
How do we know who to request for code reviews?

### ISSUE THREAD

**Issue by neverendingqs** [PokeAPI/pokeapi#361]
For example, I know #351 is looking for another reviewer, but it is not obvious to me who the second person should be. Is there a way to mark off certain parts of the code so that we know who to ask for a review to meet the two reviewer requirement?

One option could be to use [CODEOWNERS](https://help.github.com/articles/about-codeowners/).

**Comment by sargunv** [comment]
I don't think the number of people in this org has grown enough yet that we need to formalize this, but CODEOWNERS is not a bad solution if/when we're larger. IMO anyone with write access in the org should be fine to review PRs to the main PokeAPI repo, while each of the client repos can have an informal owner.

**Comment by neverendingqs** [comment]
I like the idea of adding all contributors (as you did with #351). However, I am a bit worried that adding the whole group leads to some sort of bystander effect, where no one offers a review because they are thinking someone else might do it.

I plan to leave this issue open for now, but am happy to close it if that's what we want or once I see that the next few PRs naturally get picked up by two reviewers.

**Comment by tdmalone** [comment]
@neverendingqs You asked this question on Slack but I’ll repeat it here too as it is relevant: is requiring 2 reviews too much? If we drop that back to 1, it will be easier to find people. I’d like to get @naramsim’s thoughts on that too.

Other than that - I think just let it happen organically to start with and see how we go? We might start to see over time who is better at different parts of the code. I don’t know Python so my usefulness is limited, but I’ll happily review other things.

**Comment by Naramsim** [comment]
Yes, I would say that everybody with the write access should be able to review PRs. Once a PR is opened one can also suggest reviewers.

If the limit is too high right now we can decrease it to 1.
