### ISSUE TITLE
Licensing change

### ISSUE THREAD

**Issue by tdmalone** [PokeAPI/pokeapi#366]
As raised in #355, in the context of the new static pokeapi.co site:

> The main PokéAPI repo uses the 'BSD 3-Clause "New" or "Revised" License' with copyright attributed solely to Paul Hallet. I plan on using the same BSD licence with the copyright as "Paul Hallet and PokéAPI contributors" as suggested [here](https://ben.balter.com/2015/06/03/copyright-notices-for-websites-and-open-source-projects/).

The current PokeAPI license is located [here](https://github.com/PokeAPI/pokeapi/blob/master/LICENSE.rst).

As well as modifying the license for the pokeapi.co static site (which will be in a new repo), I think we should also do the same for the main pokeapi repo, and I propose that we do so in exactly the same way: that is, by changing 'Paul Hallet' to 'Paul Hallet and PokéAPI contributors'.

Thoughts? Objections? Ping @phalt too.

**Comment by Naramsim** [comment]
@phalt, ping

**Comment by phalt** [comment]
LGTM, go for it

**Comment by phalt** [comment]
Oh my name is spelled wrong on this :laughing: I will correct it
