### ISSUE TITLE
Parsing failed SyntaxError: Unexpected token < in JSON at position 0, GET status500 at https://pokeapi.co/api/v2/pokemon/1/

### ISSUE THREAD

**Issue by annieannie** [PokeAPI/pokeapi#370]
Hi,
 Please see below screenshots:
![parsing failed er1](https://user-images.githubusercontent.com/31458661/45849474-51c6f880-bcef-11e8-81a0-774d09396ed0.PNG)
![parsing failed er2](https://user-images.githubusercontent.com/31458661/45849480-59869d00-bcef-11e8-8fab-10abb0c8fde2.PNG)

- fetch request to  https://pokeapi.co/api/v2/pokemon/11/ , https://pokeapi.co/api/v2/pokemon/14/, etcetera gives Parsing failed SyntaxError: Unexpected token < in JSON at position 0

Please see request headers in attachment. Why no json is returning from the requested url? Please suggest a solution.
Thank You

**Comment by tdmalone** [comment]
Hi Annie, this is related to a current outage - see #369.
The parsing error is because the outage is causing HTML to be returned rather than JSON.

**Comment by Tylertron1998** [comment]
@tdmalone any ideas how long this might take to fix? Sorry to seem inpatient haha, just good to get an idea as I'm planning to use this for a project.

**Comment by tdmalone** [comment]
@Tylertron1998 Pls see #369 to follow this discussion, so we can keep it all in the one place. :)
