### ISSUE TITLE
Website API Explorer example links don't work

### ISSUE THREAD

**Issue by Anu6is** [PokeAPI/pokeapi#371]
Outside of issue with named api endpoints not currently working, the example links provided on the website, that encourage users to "Try it now!", all return `null`. Manually adding a forward slash `/` to the URL successfully returns the expected results.

Issue: [https://pokeapi.co/api/v2/pokemon/1](https://pokeapi.co/api/v2/pokemon/1) returns null in the [API explorer](https://pokeapi.co/)

**Comment by cmmartti** [comment]
Oh, that's why it doesn't work. I'll correct the sample links to end in slashes and see if we can fix the server to redirect to the correct URL.

**Comment by cmmartti** [comment]
The sample links in the API explorer have been fixed, as have the URLs in the documentation (#347).

**Comment by Anu6is** [comment]
Confirmed
