### ISSUE TITLE
Limit doesn't work

### ISSUE THREAD

**Issue by benjaminledet** [PokeAPI/pokeapi#372]
Hi, when I call an api endpoint like "https://pokeapi.co/api/v2/pokemon/", I'm getting the full list of Pokemon or the doc says : 
"Calling any API endpoint without a resource ID or name will return a paginated list of available resources for that API. By default, a list 'page' will contain up to 20 resources. If you would like to change this just add a 'limit' query parameter, e.g. limit=60."

I tried to set the limit too but it doesn't work neither.
Am I doing something wrong?
thanks

**Comment by tdmalone** [comment]
Related: #365

**Comment by tdmalone** [comment]
I'm going to close this issue as there is nothing actionable for us at the moment. As @cmmartti mentioned, it will be fixed as soon as we move to Netlify. Apologies in the meantime!

**Comment by sargtier1** [comment]
so what does this mean?

**Comment by cmmartti** [comment]
@sargtier1 It means that queries that include either `?limit=100` or `?offset=100` (any numbers) will not respect the requested page and will instead return the entire result set, however large it is. This is temporary and will probably be fixed by the end of the week or next week.

**Comment by sargtier1** [comment]
> @sargtier1 It means that queries that include either `?limit=100` or `?offset=100` (any numbers) will not respect the requested page and will instead return the entire result set, however large it is. This is temporary and will probably be fixed by the end of the week or next week.

thanks for the feed back brother!

**Comment by cbouwense** [comment]
Is this still an issue

**Comment by tdmalone** [comment]
@cbouwense Yes it is - it will be until we complete our move to static hosting, which is hopefully going to be shortly!

**Comment by Kronopt** [comment]
This shouldn't be closed as it is still an issue.

**Comment by Naramsim** [comment]
No, sorry

**Comment by cmmartti** [comment]
@slothenly This will be fixed by tomorrow if things work out. We've finally figured out an automatic deploy process for static hosting on Firebase and just need to set up HTTPS and switch the DNS settings.

**Comment by sargunv** [comment]
Don't forget cloudflare caching and rate limiting, we don't want the cost
of Firebase to explode from requests that would've been limited.

**Comment by slothenly** [comment]
Update? Hoping to use this API to build out a project by the end of the week, wondering if I should swap to a different resource.

**Comment by brenopanzolini** [comment]
Any updates? I know the effort of all you guys, just asking because I would like to know if you have any prediction of when this problem will be solved :).

Thanks!

**Comment by Naramsim** [comment]
Limit works now: https://pokeapi.co/api/v2/pokemon?offset=0&limit=3
