### ISSUE TITLE
Availability of named resources (for current hosting)

### ISSUE THREAD

**Issue by tdmalone** [PokeAPI/pokeapi#373]
This issue is to consolidate updates for the current outage of named resources (eg. /pokemon/bulbasaur) into one place.

See also #374 for work on getting named resources working when we move to Netlify.

**Comment by sargunv** [comment]
[_dist.tar.gz](https://github.com/PokeAPI/pokeapi/files/2408212/_dist.tar.gz)

This archive contains all the static files we need for current hosting. It contains the api-data files processed to include the base url and named resources.

**Comment by tdmalone** [comment]
@Naramsim is now sorting this out live.

**Comment by tdmalone** [comment]
Fixed by @Naramsim:

https://pokeapi.co/api/v2/item/old-rod/
https://pokeapi.co/api/v2/berry/chesto/

Just need to confirm CORS is all good still.

**Comment by Tylertron1998** [comment]
https://pokeapi.co/api/v2/pokemon/charmander/ - doesn't seem to work for pokemon, unless I am maybe using the api wrong?

**Comment by Naramsim** [comment]
On my side it is fine

**Comment by sargunv** [comment]
It's working for me in Chrome at least. How are you making the request?

**Comment by cmmartti** [comment]
It didn't work for me, then a minute later it did.

**Comment by Tylertron1998** [comment]
strange, I get a 500

**Comment by tdmalone** [comment]
Oh, it's working now - a moment before it didn't!

**Comment by Tylertron1998** [comment]
Oh, hmm yeah it's back up. Yay? Haha, good job guys!

**Comment by tdmalone** [comment]
Ok, so named resources are mostly back up, except for encounters, which get a 404.
eg. https://pokeapi.co/api/v2/pokemon/magikarp/encounters/

https://github.com/PokeAPI/ditto/issues/33 has been re-opened to add this feature to the upstream, when that's done, we can redeploy.

**Comment by sargunv** [comment]
Generated the fixed archive: https://github.com/PokeAPI/api-data/releases/download/2018-09-22/_dist.tar.gz

**Comment by sargunv** [comment]
https://pokeapi.co/api/v2/pokemon/magikarp/encounters/
