### ISSUE TITLE
Missing Pokedex numbers for Gen 7 pokemon-species requests

### ISSUE THREAD

**Issue by bclindner** [PokeAPI/pokeapi#375]
Hey! Looks like Pokedex numbers are missing from some or all of the Gen 7 Pokemon species, at least on the `https://pokeapi.co/api/v2/` endpoint. [Here's an example](https://pokeapi.co/api/v2/pokemon-species/incineroar/) - you'll find the entire `pokedex_numbers` entry is just an empty array on the `pokemon-species` request for Incineroar, Mimikyu, etc. 

For other Pokemon outside of Gen 7, you still seem to be able to get the usual array with entry numbers and the corresponding Pokedex name/URL.

Thanks!

**Comment by Naramsim** [comment]
Hi, Veekun does not provide this kind of data for pokemons with an ID above 721

https://github.com/veekun/pokedex/blob/master/pokedex/data/csv/pokemon_dex_numbers.csv

Incineroar has the ID 727
