### ISSUE TITLE
Flick the pokeapi.co domain over to our new static hosting

### ISSUE THREAD

**Issue by tdmalone** [PokeAPI/pokeapi#376]
This is an issue to track the 'flicking over' of pokeapi.co to our new static hosting, which is highly likely to be Firebase!

Note that a few things need completion first:
- [x] Deployment of the API (https://pokeapi-215911.firebaseapp.com/api/v2/)
- [x] Deployment of the documentation site (PokeAPI/pokeapi.co#13)
- [x] Set up and verification of pokeapi.co and www.pokeapi.co as custom domains + redirect on Firebase
- [x] HTTPS provisioning (in progress, waiting)
- [x] Setting the DNS to `151.101.1.195` and `151.101.65.195` (IPs provided by Firebase)

**Comment by Naramsim** [comment]
We can close
