### ISSUE TITLE
Poke Api limit query

### ISSUE THREAD

**Issue by charliejcook** [PokeAPI/pokeapi#378]
Hi,
I am parsing this URL but the limit query isn't working and returns all 800 pokemon?
https://pokeapi.co/api/v2/pokemon/?limit=150
Is this known or is there a work around?

**Comment by cmmartti** [comment]
Pagination using `offset`/`limit` is temporarily broken until we complete the move to static hosting, which should happen within a few days. Check the outage alert message on the https://pokeapi.co home page.

If it has already been dismissed, it says:

> Outage Alert: Pagination with offset/limit for PokéAPI v2 is temporarily broken. [Read more...](https://github.com/PokeAPI/pokeapi/issues/372)
