### ISSUE TITLE
https URLs sometimes return a 301 "Permanently Moved" to an http equivalent

### ISSUE THREAD

**Issue by armadsen** [PokeAPI/pokeapi#381]
When I hit `https://pokeapi.co/api/v2/pokemon/bulbasaur`, I get a 301 to `http://pokeapi.co/api/v2/pokemon/bulbasaur`. Is there a a reason for the redirect to the insecure http URL?

Interestingly, `https://pokeapi.co/api/v2/pokemon/` does not redirect, and works fine.

**Comment by cmmartti** [comment]
That's odd; I'm not seeing the same behaviour. In any case, we will soon be moving to static hosting on Firebase, so it shouldn't be an issue once that happens.

**Comment by Naramsim** [comment]
I'm experiencing the same behaviour described by @armadsen, to avoid it you could just use by default https and add the ending slash

**Comment by s-Hale** [comment]
Same; I'm using Codepen and it's automatically blocking the link now, due to a redirect from https to http. Using https and the slash isn't fixing it. Hope the Firebase move helps.

**Comment by s-Hale** [comment]
Any updates or workarounds for this?

I'm using `fetch("https://pokeapi.co/api/v2/pokemon?limit=151/")` in one place and `fetch("https://pokeapi.co/api/v2/pokemon?limit=100&offset=151/")` in three others. Both now fail due to being redirected to a `http`. Are there any alternatives at this time?

**Comment by magical** [comment]
@s-Hale the correct URLs would be `https://pokeapi.co/api/v2/pokemon/?limit=151` and `https://pokeapi.co/api/v2/pokemon/?limit=100&offset=151` (the trailing slash goes before the `?`)
