### ISSUE TITLE
Search for a pokemon

### ISSUE THREAD

**Issue by renatoi** [PokeAPI/pokeapi#383]
I'm trying to find a way to search for pokemons based on name (not exact search), for example, Star Wars API has this:

https://swapi.co/api/people/?search=sk

Is there anything like that in Poke API?

**Comment by sargunv** [comment]
I recommend just getting the entire list and filtering for name on the client side, it's only <1000 elements in the list.

**Comment by cmmartti** [comment]
@renatoi Unfortunately, without caching every Pokémon resource, @sargunv's suggestion will only work in English. However, I am building a GraphQL API for PokéAPI that will allow complex filtering, including by name in any language, as well as by other criteria. Work on that is currently paused, but I hope to get back into it soon.

**Comment by SirSkaro** [comment]
What I currently use is a MySQL database and a hand full of spell checkers for each language. Each table includes the names of a resource in each language as well as the "PokeAPI-friendly" name. As long as the guess is close enough, you can get the Pokemon by any of its names. The tables are pretty easy to generate, though the spell checkers can be a bit more time consuming.

The GraphQL API sounds super cool. I'm excited to see it completed.

**Comment by matt3224** [comment]
Will the GraphQL API allow for searching across resources?

**Comment by bragonya** [comment]
Any update on this?

**Comment by phalt** [comment]
It looks like some progress was made here but there are no currently active GraphQL plans: https://github.com/cmmartti/pokemon-finder

**Comment by Naramsim** [comment]
Closing in favor of #474 

If anybody would like to spin up Charles' graphQL pokeapi server, [here](https://github.com/cmmartti/pokeapi/tree/graphql) you find his code.
