### ISSUE TITLE
Set global langs for all endpoints

### ISSUE THREAD

**Issue by remy-poirier** [PokeAPI/pokeapi#384]
Hello,

I want to know if it's possible to set a default language for the endpoints responses, like in query params ?

I would like to display the full pokemon List in French in my example, but the only way for me to get french names is to get it in the pokemon species or to create a local object of names like : 

```
{
    bulbasaur: "Bulbizarre"
}
```

Would it be possible to do something like `https://pokeapi.co/api/v2/pokemon/1/?lang=fr`

**Comment by Kronopt** [comment]
Several resources have their names translated to other languages (like Location, Region, Move).
But Pokemon endpoint resources do not, unfortunately.

**Comment by Naramsim** [comment]
Hi @remy-poirier, no currently the list is stricly in english. You would have to make 800 calls to know all the translated names of Pokemons.

If you want to know their translated names, query https://pokeapi.co/api/v2/pokemon-species/bulbasaur/ and look and the `names` property

**Comment by Kronopt** [comment]
Sorry...
I searched the docs for `list (Name)` and only a few resources came up...
Some resources are described as `list (Name)` others as `list Name`...
My bad

**Comment by cmmartti** [comment]
@Kronopt Yep, that's a bug that's fixed in PokeAPI/pokeapi.co#24 but hasn't been pushed to the server yet.

**Comment by remy-poirier** [comment]
Thanks you all guys, I am doing something to get it done on my own :)
