### ISSUE TITLE
What units are being used for the height and weight values?

### ISSUE THREAD

**Issue by SilasOtoko** [PokeAPI/pokeapi#387]
I noticed that I was pulling in values for the pokemon without units and was about to add them, but I can't figure out which units the values are measured in. For example, Bulbasaur's height value pulls in as 7, but his height is neither 7 inches, 7 feet, 7 meters, or 7 yards. The official Pokemon website says that Bulbasaur's height is 2 feet 4 inches, so I feel like either I'm missing something obvious (very possible) or the heights are wrong.

**Comment by cmmartti** [comment]
It's decimetres. It's the values the games used, supposedly so they could store it as an integer. Just divide by 10 for centimetres. Someone else had this question a few weeks ago in #380, so the documentation was updated to show the values in Pokeapi/pokeapi.co#19.

**Comment by SilasOtoko** [comment]
Thanks! I didn't realize that I had my GitHub search filtering out closed issues when I looked to see if anyone else had asked.

**Comment by cmmartti** [comment]
Actually, it looks like the fix in PokeAPI/pokeapi.co#19 was accidentally over-written in a later commit, so the docs site didn't have the units. I have since re-applied those commits in PokeAPI/pokeapi.co#27 and updated the server.

**Comment by Aaron-Quickstart** [comment]
I believe weight is in hectograms.
