### ISSUE TITLE
Domain pokeapi.co may have expired

### ISSUE THREAD

**Issue by cmmartti** [PokeAPI/pokeapi#389]
@phalt @tdmalone @Naramsim 

It looks like the pokeapi.co domain may have expired. Some browsers bring up the Namecheap ad page.

**Comment by cmmartti** [comment]
The page displays this message:

>This domain is registered at Namecheap
>This domain was recently registered at Namecheap. Please check back later!

I don't know what that's supposed to mean...

**Comment by lukejpreston** [comment]
You can get it here... http://pokeapi.salestock.net

**Comment by Dyleee** [comment]
The JSON endpoints there are not properly formatted

**Comment by phalt** [comment]
Resolved!
