### ISSUE TITLE
Ultra Sun & Ultra Moon Pokémon Missing

### ISSUE THREAD

**Issue by arthursb** [PokeAPI/pokeapi#390]
Database is missing every Pokémon numbered between 803 (Poipole) and 807 (Zeraora)

**Comment by shilangyu** [comment]
Meltan and Melmetal (808 & 809) also missing

**Comment by shilangyu** [comment]
absolutely, they are currently moving to static file hosting so probably thats why they didnt add new pokemons yet

**Comment by Dyleee** [comment]
Oh I see, so far I love the API.

**Comment by MonAaraj** [comment]
As far as i know, i think they moving finished, though the pokemon are still not added, what happened that makes them so behind with Pokemon?

**Comment by Naramsim** [comment]
I can try today.

**Comment by Naramsim** [comment]
https://pokeapi.co/api/v2/pokemon/?offset=800&limit=30

**Comment by cmmartti** [comment]
PokéAPI has been updated with new data, bringing it fully up-to-date.

**Comment by Naramsim** [comment]
(we still lack of 808 and 809)

https://bulbapedia.bulbagarden.net/wiki/Meltan_(Pok%C3%A9mon)

**Comment by shilangyu** [comment]
Opened a new issue for meltan and melmetal as they are not Sun/Moon pokemons: #414
