### ISSUE TITLE
docker build failed with "Unsupported Python version"

### ISSUE THREAD

**Issue by nest-aka-swan** [PokeAPI/pokeapi#393]
docker build fails on pip install step ([full log](https://pastebin.com/naub2Zr6)):
```
Step 9/13 : RUN pip install --no-cache-dir -r requirements.txt
 ---> Running in 8d89803d00c0
Collecting Django==2.1.2 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/8b/03/4c74d3712919613f2c611e6689522df507a2753a92049009661a81b4b72f/Django-2.1.2.tar.gz (8.6MB)
    Complete output from command python setup.py egg_info:

    ==========================
    Unsupported Python version
    ==========================

    This version of Django requires Python 3.5, but you're trying to
    install it on Python 2.7.

    This may be because you are using a version of pip that doesn't
    understand the python_requires classifier. Make sure you
    have pip >= 9.0 and setuptools >= 24.2, then try again:

        $ python -m pip install --upgrade pip setuptools
        $ python -m pip install django

    This will install the latest version of Django which works on your
    version of Python. If you can't upgrade your pip (or Python), request
    an older version of Django:

        $ python -m pip install "django<2"

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-AD6pqy/Django/
You are using pip version 8.1.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c pip install --no-cache-dir -r requirements.txt' returned a non-zero code: 1
```

I've tried to replace `python-dev`, `python-pip` pacakges with `python3-dev`, `python3-pip` and replaced `pip`, `python` with `pip3`, `python3` calls, but it crashed on migrations step [full log](https://pastebin.com/CfpA5zYb).

Looks like it is related to #385 

I am running `docker build -t pokeapi .` on Windows 10 via WSL and Docker Desktop.

**Comment by chrislennon** [comment]
@nest-aka-swan I bumped into the same issue recently but haven't got around to fully testing things enough to make a PR yet. 

Just dropped my monkey patch into a [gist](https://gist.github.com/chrislennon/8fd1d54601838a1066e72e7919c933f5) that may get the image building for you.

Like you, after changing the python version I got errors at subsequent steps.

- I _think_ the 'CacheKey' error in migrations was related to this django-redis [issue](https://github.com/niwinz/django-redis/issues/342) 
- postgres not being started/ready was also an issue I experienced.

Let me know if that helps, I will attempt to formalise my fix at some point 😅

**Comment by nest-aka-swan** [comment]
@chrislennon Thanks for the gist! Unfortunately, patched docker container exits immediately with `docker run -d -p 8000:8000 pokeapi`.

Problem with django-redis was fixed in 4.9.1.

 I am going to dig into the problem today and start a PR if you don't mind :)

**Comment by chrislennon** [comment]
@nest-aka-swan thats unfortunate that it didn't work straight away, it seems to build for me with those 3 files changed - but again there was a lot of hacking to get a build, not 100% sure what I changed beyond those files though.

Good luck with the digging, I will try to get to it this weekend if you haven't cracked the case by then 😄

**Comment by ChristianIvicevic** [comment]
@chrislennon I got it working after tweaking your shell script as follows:

    #!/bin/sh
    # wait-for-postgres.sh

    set -e

    host="$1"
    shift
    cmd="$@"

    service postgresql start
    service redis-server start

    until PGPASSWORD=pokemon psql -h "$host" -U "ash" -d "pokeapi" -c '\q'; do
    >&2 echo "Postgres is unavailable - sleeping"
    sleep 1
    done

    >&2 echo "Postgres is up - executing command"
    exec $cmd

Unfortunately the server is returning escaped HTML rather than pure JSON on requests. Since I don't know Python at all, I cannot fix this issue. In the meantime I will be using the raw data in a small Node-based server hosted here: https://github.com/PokeAPI/api-data/tree/master/data/api/v2

The downside to my method will be that everything has to be accessed via numeric IDs while your official Python implementation allows unique names as well.

**Comment by Naramsim** [comment]
Please, use our docker-compose
