### ISSUE TITLE
Berry Endpoint

### ISSUE THREAD

**Issue by alexd99** [PokeAPI/pokeapi#396]
I feel like it is missing some information on the berry endpoint. When I check bulbapedia for the berry information there seems to be a lot more information if you check out the resource for the oran berry (https://bulbapedia.bulbagarden.net/wiki/Oran_Berry) there is specific information about generation 3 and 4, as well as some more information about ice scream scoops, there are sprites for the trees, and more. I would be really interested in having the information updated to just include the differences from generation 3 and 4, but I don’t know if there is any interest for this. I could also not understand the api, and that information could already be housed somewhere on the api already. If anyone could help me out it would be greatly appreciated, thanks in advance.

**Comment by Naramsim** [comment]
The very first thing you should do is to check if your data is contained inside our provider: https://github.com/veekun/pokedex.

**Comment by alexd99** [comment]
I looked through that link, and I found this file (https://github.com/veekun/pokedex/blob/master/pokedex/data/csv/berries.csv), which looks like the current berry endpoint, I could not find any other useful berry files. 

I am assuming that this means that the information that I would like added currently does not exist, does that sound correct?

**Comment by Naramsim** [comment]
Yeah, exactly! So if you want more feature you should ask to the guys of Veekun.

I will close this issue, thanks.

**Comment by alexd99** [comment]
Thank you for answering that question. I did not know that you guys pulled your data for someone else.
