### ISSUE TITLE
Documentation for FlavorText is missing Version object in response

### ISSUE THREAD

**Issue by ChristianIvicevic** [PokeAPI/pokeapi#399]
This is a quick error in the documentation wherein it says `FlavorText` only returns `flavour_text` and `language`, but it returns `version` as well as `NamedAPIResource` to `Version`. Just got confused while rewiring your schema for use in GraphQL until I noticed the documentation isn't up to date.

**Comment by cmmartti** [comment]
I assume you're calling the REST API in your resolvers? My Python implementation is built on the original codebase alongside the REST API, so it can directly access the database and do stuff like [DataLoader](https://github.com/syrusakbary/aiodataloader) batch-fetching and complex filtering. These features complicate the codebase somewhat, so I plan to write a short document explaining how the code is structured and anything to watch out for. So much to do, so little time...

**Comment by ChristianIvicevic** [comment]
@cmmartti Sorry for going offtopic for the time being, but I finally came up with a consistent schema and implementation of type safe resolvers. Currently I am using a small subset of the actual PokeAPI, but I will consider publishing the revised and fully implemented server after finishing my pet project in the weeks to come.
