### ISSUE TITLE
Pokemon location  CORS

### ISSUE THREAD

**Issue by gellel** [PokeAPI/pokeapi#400]
Was exploring the API (which is awesome BTW! 🥇 👍) and tried reaching the Pokemon.location_area_encounters endpoint. Out of the box there appears to be a difference in headers leading to a CORS issue client side. Just checking whether this route is deliberately configured this way or if it's a potential issue due to the API implementation as per this line: 

https://github.com/PokeAPI/pokeapi/blob/master/pokemon_v2/api.py#L227

```
Access to XMLHttpRequest at 'http://pokeapi.co/api/v2/pokemon/10/encounters/' (redirected from 'https://pokeapi.co/api/v2/pokemon/10/encounters') from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Thanks for the awesome project. Apologies if this has been addressed in another thread; I searched and wasn't able to see if anyone had covered it from this angle.

**Comment by Naramsim** [comment]
Use HTTPS
