### ISSUE TITLE
Weird pokemon_species order in /v2/generation/{id}

### ISSUE THREAD

**Issue by shilangyu** [PokeAPI/pokeapi#404]
## What happens:
When i call `https://pokeapi.co/api/v2/generation/1/` and access `pokemon_species` property they are returned in a weird order (two blocks of descending pokedex numbers)

## What i am expecting:
Getting a result where `pokemon_species` are sorted ascendingly by their pokedex number

**Comment by cmmartti** [comment]
I'm seeing the issue you describe. However, the order of the results is unspecified, so the current behaviour is correct and probably won't be changed. I recommend sorting the results list on the client if a specific ordering is desired.
