### ISSUE TITLE
API doesn't return anything.

### ISSUE THREAD

**Issue by krisScript** [PokeAPI/pokeapi#408]

**Comment by Kronopt** [comment]
Also

> Instead of returning 404 response nothing is being returned.

If you're talking about the 'Not Found' page, that's actually a 404 page

**Comment by krisScript** [comment]
> > https://pokeapi.co/api/v2/pokemon/mega-punch
> 
> mega-punch is not a pokemon.
> correct endpoint would be: https://pokeapi.co/api/v2/move/mega-punch
> 
> > https://pokeapi.co/api/v2/berry/master-ball
> 
> master-ball is not a berry.
> correct endpoint would be: https://pokeapi.co/api/v2/item/master-ball
> 
> > https://pokeapi.co/api/v2/berry/pikachu
> 
> pikachu is not a berry.
> correct endpoint would be: https://pokeapi.co/api/v2/pokemon/pikachu
> 
> > https://pokeapi.co/api/v2/pokemon/chariza
> 
> "charizard"

**Comment by krisScript** [comment]
I
