### ISSUE TITLE
New Java wrapper

### ISSUE THREAD

**Issue by iAmGio** [PokeAPI/pokeapi#410]
Hi! I'm opening this issue to have my new Java wrapper linked into the documentation page, as Naramsim told me via e-mail. 
Repo: https://github.com/iAmGio/pokedex-java-api
It supports Pokémon only at the moment, other components such as Berries will be supported as soon as possible.

Thanks!

**Comment by cmmartti** [comment]
Hi, this looks great. If you can add it to the page yourself (just click the edit button at https://github.com/PokeAPI/pokeapi.co/blob/master/src/pages/docs/v2.html.js) and create a pull request, I'll be able to merge it in.

**Comment by tdmalone** [comment]
Closing this issue; @iAmGio please feel free to send us a PR when you’re ready!
