### ISSUE TITLE
Pokeapi endpoint is not complete

### ISSUE THREAD

**Issue by HajarElkoumikhi** [PokeAPI/pokeapi#411]
Hello, 

I'm using Alamofire to fetch data from Pokeapi. 
The issue that I'm encountering is when I lunch a webCallService, I get only 20 Pokemon's data. 

This is the link that I'm using : https://pokeapi.co/api/v2/pokemon/ 
is this normal ? or is there any other endpoint link that can provide me with the +900 Pokemon's data ? 

Thank you!

**Comment by Naramsim** [comment]
Yes of course, you should have read our docs.

https://pokeapi.co/api/v2/pokemon/?offset=0&limit=99999999

**Comment by HajarElkoumikhi** [comment]
Thank you so much @Naramsim
