### ISSUE TITLE
400 Code Error

### ISSUE THREAD

**Issue by MBoberski** [PokeAPI/pokeapi#413]
Hi,

I used docker-composer to run poekapi, I changed gunicorn from 8000 to 7001 in docker files as well as nginx vhost anc gunicorn ini file. Also I modify ports as:

```
    ports:
      - "85:80"
      - "445:443"
```

When I do docker-compose up --build and try to open webpage I get: Bad Request (400).

My apache vhost is like:

```
<VirtualHost *:80>
    ServerName pokeapi.expij.h-y.eu
	ServerAlias pokeapi.expij.h-y.eu
	ServerSignature Off

	ProxyPreserveHost On
	AllowEncodedSlashes Off

	ProxyVia On
	ProxyRequests Off
	ProxyPass / http://127.0.0.1:85/
	ProxyPassReverse / http://127.0.0.1:85/
	ProxyPreserveHost on
 
    #Set up apache error documents, if back end goes down (i.e. 503 error) then a maintenance/deploy page is thrown up.
	ErrorDocument 404 /404.html
	ErrorDocument 422 /422.html
	ErrorDocument 500 /500.html
	ErrorDocument 503 /deploy.html

	LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b" common_forwarded
	ErrorLog  /var/www/sites/*.expij.h-y.eu/logs/pokeapi.expij.h-y.eu/error.log
	CustomLog /var/www/sites/*.expij.h-y.eu/logs/pokeapi.expij.h-y.eu/forwarded.log common_forwarded
	CustomLog /var/www/sites/*.expij.h-y.eu/logs/pokeapi.expij.h-y.eu/access.log combined env=!dontlog
	CustomLog /var/www/sites/*.expij.h-y.eu/logs/pokeapi.expij.h-y.eu/com.log combined
</VirtualHost>
```

**Comment by cmmartti** [comment]
It doesn't say this anywhere, but you need to add your host to the `ALLOWED_HOSTS` list in `config/settings.py`. Then run
```sh
docker-compose down
docker-compose up --build -d
```
to rebuild the container and restart as a daemon.

**Comment by TorchwoodPL** [comment]
`ALLOWED_HOSTS = ['.pokeapi.expij.h-y.eu', 'localhost', '127.0.0.1']`

This is what I have, and I get "Not Found" on url http://pokeapi.expij.h-y.eu/ and "Bad Request (400)" on http://expij.h-y.eu:85/ (url without proxy pass)

**Comment by cmmartti** [comment]
Try putting just `.expij.h-y.eu` (or `.h-y.eu`) in the `ALLOWED_HOSTS`, without the subdomain. That's what I had to do on my server and it worked.

**Comment by TorchwoodPL** [comment]
I have other services on the same VPS and for me port 8000 is allocated already, same as 80 and 443. And I need everythink to be at easy to use domainnames, without port numbers.

**Comment by Naramsim** [comment]
Ahh, so you use Apache as a reverse proxy!

Ok, still you can have your compose mapping to different ports:

```yml
web:
    build: 
      context: ./Resources
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "10080:80"
      - "10443:443"
    volumes_from:
      - app:ro
    links:
      - app
```

Then you say to your apache httpd to forward some calls to localhost:10080 and to localhost:10443.

But I want to say that this is not an issue related to PokeAPI, it is just a reverse-proxy question.
