### ISSUE TITLE
Wurmple Evolution Chain only lists Silcoon as an evolution

### ISSUE THREAD

**Issue by poastertoaster** [PokeAPI/pokeapi#420]
- Provide a clear description of the issue.

Wurmple is only listed as evolving into Silcoon, while Veekun lists Wurmple as evolving into both Silcoon and Cascoon. Cascoon is listed as a possible evolution of Silcoon erroneously. Dustox is not listed as a possible evolutionary step of Wurmple.

- Provide a clear description of the steps to reproduce.

https://pokeapi.co/api/v2/evolution-chain/135/

- Provide a clear description of the expected behaviour.

Wurmple's first evolutionary stage should list both Silcoon and Cascoon. Cascoon should not be an evolution of Silcoon. Cascoon should have Dustox as an evolution.

**Comment by tdmalone** [comment]
Hi @poastertoaster, thanks for this report. This is a longstanding issue that we haven't been able to properly solve yet.

I'll close this in favour of the existing issue at https://github.com/PokeAPI/pokeapi/issues/163 - if you able to assist with solving this please feel free!
