### ISSUE TITLE
get french language pokemon list and data

### ISSUE THREAD

**Issue by tartreau** [PokeAPI/pokeapi#421]
Hello. I can't find in the docs the right way to call the api and get data in french

Is there something like this ?
https://pokeapi.co/api/v2/region/1/language/5 ?

**Comment by tartreau** [comment]
So what should I do if I wanted to display a list of Pokemon in the french language ?

**Comment by cmmartti** [comment]
> use the `/species/` resource instead.

Also, some Pokémon names are on the default Pokémon form (such as Mega forms), so you'll have to check there for a name first, then fall back to the species name if there isn't a form name. Alternatively, just use the species to begin with, as I suggested yesterday. Don't ask me why it's like this; I didn't design it.

For the difference between a Pokémon, a Pokémon species, and a Pokémon form, read #401.
