### ISSUE TITLE
Duplicated pokemon-species in evolution-trigger #1

### ISSUE THREAD

**Issue by Adrian-26-Isotope** [PokeAPI/pokeapi#423]
Dear PokeAPI team,

**https://pokeapi.co/api/v2/evolution-trigger/1/** contains Magnezone 4 times. At index 192, 262, 294 and 298.
Some others like leafeon and glaceon do also exist more than once.
Is it possible to reduce the linked species that every species appears only once?

**Comment by cmmartti** [comment]
Yep, that's clearly an error. If anyone wants to fix it, the faulty code is [here](https://github.com/PokeAPI/pokeapi/blob/85103d24aeec480c6f01728a7ed309d0dae269f5/pokemon_v2/serializers.py#L2663). The species list just needs to be de-duplicated before looping over it.

**Comment by Kronopt** [comment]
@Adrian-26-Isotope, I can do it if you don't want to do it yourself.

**Comment by Adrian-26-Isotope** [comment]
@Kronopt please go ahead.
