### ISSUE TITLE
Strip whitespace from sprites

### ISSUE THREAD

**Issue by b3u** [PokeAPI/pokeapi#431]
I noticed that the sprites have a great deal of unnecessary white-space. It is difficult to use the images provided as is, because the size of the images being greater than the actual picture, it is difficult to position in properly. I'm sure there is some build tool which could strip all of the white-space in one go.
Thank you!
(Note: The only images I checked were Bulbasaur and Pikachu.)

**Comment by cmmartti** [comment]
The images are all the exact same size, except for generation 7, which are slightly bigger. It doesn't make sense to start cropping them, especially since so many people are already using them as they are now.

**Comment by b3u** [comment]
Wow, that was quick! Thank you.

**Comment by cmmartti** [comment]
You can find sprites elsewhere on the Internet. Check out Veekun on GitHub; I think they might have the raw assets.

https://github.com/veekun/

**Comment by sargunv** [comment]
You could also include some cropping login in your client application.
