### ISSUE TITLE
Retrieve Info on Important Trainers

### ISSUE THREAD

**Issue by blaiddyd** [PokeAPI/pokeapi#432]
Hello!

I was wondering whether the API supports searches for important trainers (aka Champions, Elite Four, Gym Leaders, etc.) such as their Pokemon, the games they appear in, and so on. If not, would this an appropriate feature to add to the API?

Thanks!

**Comment by Kronopt** [comment]
It does not.

Whether it would be an appropriate feature, it's debatable.
Also we would have to get that information elsewhere as our data source (veekun) has no such data... And that's most likely a deal breaker
