### ISSUE TITLE
Publish as a JS package

### ISSUE THREAD

**Issue by arcanis** [PokeAPI/pokeapi#433]
As a tool author, I'd like to rely on your data without directly querying your endpoint (it might be because I don't want to rely on third-party websites, or because I don't want to eat your bandwidth, or because I want to have a finer control on the API layout).

What would you think of publishing a npm package containing the csv bundled as an sqlite database after each update to the `csv` directory? This could be automated fairly easily using the GitHub actions (or an Azure job in the worst case if we can't find out how to give Actions access to this repository).

Generating the sqlite database is as simple as:

```bash
DATA_DIR=v2/csv
cd "${DATA_DIR}"

(
    echo .mode csv

    for TABLE in *.csv; do
        echo .import "${TABLE}" "$(basename "${TABLE}" .csv)"
    done
) | sqlite3 pokemon.db
```

The end result is ~30MB, but we can decrease it by providing a few different partial databases (for example one that would only contain the pokedex data).

**Comment by Naramsim** [comment]
Hm, will the package be portable? Would you install SQLite3 as a dependency?

**Comment by phalt** [comment]
Is the Veekun CSVs good enough for this already?

**Comment by phalt** [comment]
This data: https://github.com/veekun/pokedex

**Comment by arcanis** [comment]
> Hm, will the package be portable? Would you install SQLite3 as a dependency?

Yes, SQLite3 would be a dependency in this scenario, but it's a very standard tool supported by pretty much everything. It has even been compiled down to WebAssembly to be used within browser. That would imo be a safe candidate for the most portable database format around here - even csv requires different parsers for each language.

> Is the Veekun CSVs good enough for this already?

Yep (they're the same ones as the ones in data/v2/csv, right?). However the current shape of the repository doesn't allow it to be easily published, and the csv format isn't as easy to work with as an SQLite database (cf previous point).

**Comment by cmmartti** [comment]
@arcanis Something like [this](https://github.com/cmmartti/pokemon-database)?

I just split it out of another project I'm working on at the moment. It's an exact copy of Veekun's database schema that can build a database and load in all the CSV data. 

There's a copy of the SQLite database in the repository that can be used directly, or you can plug in your database config details and build your own database (Postgres, MySQL, or anything that [Knex](https://knexjs.org/) supports).

Also, TypeScript types that are generated using [schemats](https://github.com/SweetIQ/schemats). You can only re-generate TypeScript types from a Postgres or MySQL database, but you only need to do that if you change the database schema.

**Comment by arcanis** [comment]
@cmmartti I don't have much experience with Knex, but something like this is what I have in mind, yes - although one important difference is that I'd prefer it to be provided by the PokeAPI org, as I would have a higher confidence that it would always be maintained up-to-date.

**Comment by Naramsim** [comment]
Closing since this is a stale issue. 

Feel free to re-open it @arcanis, or even better to come up with a solution :) 

Posting here a resource that could be helpful for you: 

https://github.com/PokeAPI/api-data : all our data in JSON format, if you want to query it locally.
