### ISSUE TITLE
pokeapi needs access to https

### ISSUE THREAD

**Issue by MonAaraj** [PokeAPI/pokeapi#434]
so, while using pokeapi to try to fetch female front pikachu, I saw that it used http, which is not secure, and trying to use https made a 404 error, (the link i was using came from the documentation), which is this: https://pokeapi.co/media/sprites/pokemon/female/25.png 

Thanks in advance

**Comment by cmmartti** [comment]
Image sprites are not served from our servers. The correct link for the Pikachu front female sprite is https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/female/25.png

Examples used in the documentation are just examples and are not meant to be used directly.
