### ISSUE TITLE
Translations to PT_BR

### ISSUE THREAD

**Issue by avelinocneto** [PokeAPI/pokeapi#435]
Can I help you to translate the resources to PT-BR? How To?

**Comment by Naramsim** [comment]
You should open a PR on Veekun https://github.com/veekun/pokedex

**Comment by Naramsim** [comment]
You should open a PR on Veekun https://github.com/veekun/pokedex

**Comment by avelinocneto** [comment]
Sorry by delay.. 
you still need help ?
I asked about the file locations on the project...

**Comment by Naramsim** [comment]
If you are willing to contribute it will be really appreciated. I guess your contribution works better over at https://github.com/veekun/pokedex (we use their data)

So try to see if they accept it over there. If not, come back here :)

**Comment by magical** [comment]
We always welcome translations :)
