### ISSUE TITLE
Go Wrapper

### ISSUE THREAD

**Issue by mtslzr** [PokeAPI/pokeapi#436]
Wrote a wrapper for PokeAPI v2 in Go: [pokeapi-go](https://github.com/mtslzr/pokeapi-go). Per #410, sounds like it starts with opening an issue. Let me know what I can do to help get it on the website. Thanks!

**Comment by mtslzr** [comment]
Created an MR, as I'd seen with others, at https://github.com/PokeAPI/pokeapi.co/pull/62. Let me know if I'm out of order, or if there's anything else I can do to help. Thanks!

**Comment by tdmalone** [comment]
PR is all that’s needed :) I’ve approved your PR and will leave it for another maintainer to double-check and merge.
