### ISSUE TITLE
New Flutter wrapper

### ISSUE THREAD

**Issue by prathanbomb** [PokeAPI/pokeapi#440]
I've published a wrapper for Flutter
https://pub.dev/packages/pokeapi/versions/1.0.0

**Comment by Naramsim** [comment]
Hi @prathanbomb, thanks for the contribution but I was wondering if you could you add some tests. Thanks

**Comment by prathanbomb** [comment]
Hi @Naramsim you can find the unit test in pokeapi -> test -> test-api.dart
Thanks

**Comment by Naramsim** [comment]
Nice, so you can set up a CI on Travis or Circle to have them automated. Then open a PR here and add your wrapper

**Comment by prathanbomb** [comment]
I'm gonna try GitHub CI that has just been announced.

**Comment by thosakwe** [comment]
I don't think the wrapper should depend directly on Flutter, as that means Dart on the server and Web can't use it.
