### ISSUE TITLE
Egg Group Missing: Field

### ISSUE THREAD

**Issue by bausshf** [PokeAPI/pokeapi#441]
As described here:

https://bulbapedia.bulbagarden.net/wiki/Egg_Group

https://bulbapedia.bulbagarden.net/wiki/Field_(Egg_Group)

The field group is missing (or does not seem to work.)

Its other group name would be **ground** but that does not seem to work either.

Ex.

I've tried both **egg-group/field** and **egg-group/ground**.

Neither of them yields a result.

**Comment by magical** [comment]
Looks to me like ground works: https://pokeapi.co/api/v2/egg-group/ground/

**Comment by Naramsim** [comment]
@bausshf, is the solution of @magical working for you? Or it's a problem with the data returned not being sufficient?

**Comment by bausshf** [comment]
It works now with ground. I tried that yesterday as well but it just gave an error so assumed it was not implemented either :)

Thank you.
