### ISSUE TITLE
Wrong Variable mapping in JSON output for move endpoint

### ISSUE THREAD

**Issue by yashwanthkorla** [PokeAPI/pokeapi#442]
Endpoint : https://pokeapi.co/api/v2/move/246/

"effect": "Inflicts regular damage. Has a **$effect_chance%** chance to raise all of the user's stats one stage.",
![image](https://user-images.githubusercontent.com/4706215/62755354-3e508780-ba91-11e9-9b1e-a50c5df23e2c.png)

**Comment by caerulius** [comment]
This is by design. You need to map the `effect_chance` value into the effect or short_effect string after querying the API. You can see the value in your screenshot, for Ancient Power (move id 246), the value is 10. A simple regex for any move you query should suffice.
