### ISSUE TITLE
Missing Pokemons

### ISSUE THREAD

**Issue by AzazelHD** [PokeAPI/pokeapi#443]
You are missing the 2 latest pokemons. 

808 = Meltan
809 = Melmetal

Please add them soon

**Comment by Kronopt** [comment]
I can confirm they are both missing from veekun.

Also:

> - If your issue is one of outdated API data, please note that we get our data from [veekun](https://github.com/veekun/pokedex/) without modifying it. If they are not up to date either, please look for or create an issue there. Otherwise, feel free to create an issue here. 

It might be best/faster to open an issue on [veekun](https://github.com/veekun/pokedex/) directly
