### ISSUE TITLE
Differing url for sprites in the API vs. what's shown in documentation

### ISSUE THREAD

**Issue by dillonp23** [PokeAPI/pokeapi#448]
<img width="1434" alt="Screen Shot 2019-09-16 at 6 32 21 PM" src="https://user-images.githubusercontent.com/52013691/65004198-6e6d2080-d8b0-11e9-9b5b-73d9a603c56b.png">
<img width="1437" alt="Screen Shot 2019-09-16 at 6 31 44 PM" src="https://user-images.githubusercontent.com/52013691/65004199-6e6d2080-d8b0-11e9-96bf-e4958f71d615.png">

The documentation needs to be updated with the correct URL for sprite images (correct url shown on the homepage for the API).

**Comment by phalt** [comment]
Yep, it's out of date. But also if you're hard coding this kind of stuff you're making a mistake. Consider the API format to be the truest format and just read the values you get back.

**Comment by dillonp23** [comment]
Thanks for the advice! I'm brand new to programming and I discovered this while completing a project. It was a learning lesson though, so now I can apply this knowledge to future projects. Thanks for the response!

**Comment by phalt** [comment]
Nice one @dillonp23 - glad it helped! Good luck with your future programming endeavours
