### ISSUE TITLE
Add possibility to get Pokemon evolution easier

### ISSUE THREAD

**Issue by ks129** [PokeAPI/pokeapi#452]
Please add possibility to make requests like this:
https://pokeapi.co/api/v2/evolution/{pkmn ID or name}/

This would return:
evo_from
evo_from_reqs
evo_to
evo_to_req
evo_mega
evo_form

Please add this. Currenly it's so hard to get specific pokemon evo from and evo to.

**Comment by Selim042** [comment]
Something like this? (probably more fleshed out objects)
```json
{
	"mega": null,
	"from": {
		"name": "Cosmog",
		"form": null,
		"reqs": [{
			"level": 43
		}]
	},
	"to": [{
			"name": "Lunala",
			"form": null,
			"reqs": [{
				"level": 53
			}]
		},
		{
			"name": "Solgaleo",
			"form": null,
			"reqs": [{
				"level": 53
			}]
		}
	]
}
```

**Comment by Naramsim** [comment]
Hello, currently no one is developing new features. We are currently a bit blocked. If you want new features you have to build them by yourself and then submit a PR.

Sorry

**Comment by ks129** [comment]
Yes, I mean something like @Selim042 writed. I try to make this myself, but I think this fail, due I don't know coding enough good for this.

**Comment by Naramsim** [comment]
Stale issue, closing it.
