### ISSUE TITLE
Missing some Sprites 

### ISSUE THREAD

**Issue by seelker** [PokeAPI/pokeapi#454]
Hello all,

It seems that some sprites ressources are missing:

Tested from:
https://pokeapi.co/api/v2/pokemon/806/

![image](https://user-images.githubusercontent.com/2650089/67531976-f7a02000-f6c4-11e9-9af7-a1d8b509316e.png)

Is this a source issue?

**Comment by Dillonzer** [comment]
I imagine this should go under the https://github.com/PokeAPI/sprites repo. It's a seperate repo that houses all the sprites.

**Comment by leobetosouza** [comment]
looks like the api isnt updated since the sprites repo looks okay...

my application found other missing sprites in `/pokemon`and `/pokemon-form`... you can see on the second sheet of this link: https://docs.google.com/spreadsheets/d/1wfERnZdH3DfLeGtB_4rvoirC37I7WHKNILPcGwhXRmM/edit?usp=sharing

**Comment by Naramsim** [comment]
Yeah, true. We should refresh the API.

**Comment by Naramsim** [comment]
The API got refreshed way back. We have some more sprites now.
