### ISSUE TITLE
PokeAPI blocks user-agent "lwp" (i.e. perl)

### ISSUE THREAD

**Issue by Sec42** [PokeAPI/pokeapi#456]
Using the API from within perl is met with an error, instead of returning content.

```
>lwp-request -U https://pokeapi.co/api/v2/pokemon/95
GET https://pokeapi.co/api/v2/pokemon/95
User-Agent: lwp-request/6.31 libwww-perl/6.31

error code: 1010
```

This block seems to be based on the "User-Agent" string - if i manually set any other user-agent, it works:

```
>lwp-request -H "User-Agent: foo" https://pokeapi.co/api/v2/pokemon/95 |jq .forms
[
  {
    "name": "onix",
    "url": "https://pokeapi.co/api/v2/pokemon-form/95/"
  }
]
```

**Comment by Naramsim** [comment]
That seems a bit weird. We don't do anymore any UA check since now we are on Firebase+Cloudflare. Maybe it's one of the two that doesn't like your UA string.

**Comment by phalt** [comment]
This is truly weird, perhaps it is a firebase or cloudflare thing?

**Comment by Naramsim** [comment]
I seriously doubt it's a problem of Firebase/Cloudflare. Maybe it's just the Perl client used which is a bit old and does. 

Considering also that 99% of the requests are handled directly and only by Cloudflare I think we cannot do anything about it. There are no settings there that could be linked with this UA problem. 

Maybe @Sec42 has some news about this issue.
