### ISSUE TITLE
How to get info on Weakness for Pokemon?

### ISSUE THREAD

**Issue by ansonfoong** [PokeAPI/pokeapi#467]
Is there Weakness listed anywhere? I don't see it as a field in the Pokemon.

**Comment by Naramsim** [comment]
Hi, knowing the type/types of the pokemon and the multiplier of a specific type you should be able to understand weaknesses and super-effectiveness.

Here you get the multipliers for every type: 
- https://pokeapi.co/docs/v2.html#types
- https://pokeapi.co/api/v2/type/2 (fighting type)

**Comment by Naramsim** [comment]
[Here](https://github.com/Naramsim/Colosseum/blob/master/src/scripts/helpers/getMultipliers.js) is the function I came up with when I developed https://naramsim.github.io/Colosseum/

But it doesn't return all the multipliers, only the one different from `x1`

**Comment by ansonfoong** [comment]
> [Here](https://github.com/Naramsim/Colosseum/blob/master/src/scripts/helpers/getMultipliers.js) is the function I came up with when I developed https://naramsim.github.io/Colosseum/
> 
> But it doesn't return all the multipliers, only the one different from `x1.0`

Thank you
