### ISSUE TITLE
Provide phalt with firebase / netlify access

### ISSUE THREAD

**Issue by phalt** [PokeAPI/pokeapi#477]
Please allow me to join the firbase/netlify orgs.

Two reasons:

1) security and redundancy

2) there is a small amount of USD (about $30) that I want to pipe into these hosting services.

**Comment by Naramsim** [comment]
Hi @phalt,

will do it. Anyway, we have a Pokeapi Google account and that has access to the Firebase hosting, I think. The account and password can be found in our private 'core-team' Slack chat. Anyway, I'll try to add your personal email to both

**Comment by Naramsim** [comment]
Added @phalt (personal email) as an owner of the Firebase project. This allows him also to see costs.

**Comment by Naramsim** [comment]
Sent to @phalt (personal email) the request to become an owner of our Netlify organization.

**Comment by phalt** [comment]
Amazing. Thanks @Naramsim Let's see how I can get these funds over to help keep the project running.
