### ISSUE TITLE
Many species with missing `pokedex_numbers`

### ISSUE THREAD

**Issue by leobetosouza** [PokeAPI/pokeapi#484]
I'm building an app and I found some inconsistencies on the API data.

My app is trying to get the `pokedex_numbers` of each pokemon specie and looks like many Alolan species are missing this data.

This is a spreadsheet that my app populates when it encounters this inconsistency: https://docs.google.com/spreadsheets/d/1wfERnZdH3DfLeGtB_4rvoirC37I7WHKNILPcGwhXRmM/edit?usp=sharing

Each row has a link and you can just click it to see the API without the data on the key `pokedex_numbers`

(the second sheet is populated when it encounters a pair of pokemon-form/pokemon without a `front_sprite`... there's already an issue for it: #454).

For the sake of your curiosity, the app is: https://pokememo.now.sh/ (it's a work in progress and the repo is [leobetosouza/pokememo](https://github.com/leobetosouza/pokememo))

**Comment by Bruncky** [comment]
Not just that, but it seems that many Pokémon are still missing altogether, as far as I remember the last Pokémon is Zeraora (807).

For my app I'm implementing my own methods to get information about any Pokémon after Zeraora, when I have some time on my hands and all that is finally done, I'd love to help out and provide any data I can to the API to help complete it.

**Comment by leobetosouza** [comment]
> Not just that, but it seems that many Pokémon are still missing altogether, as far as I remember the last Pokémon is Zeraora (807).

For the Galar pokédex (and Meltan/Melmetan), we need to (sadly) wait Veekun to update its database: #460 :(

I

**Comment by Naramsim** [comment]
Sorry for having come back only now. Yeah, we lack data. We are trying to involve the community to fill in as much data as possible, but it takes time.

**Comment by Naramsim** [comment]
Closing since we added gen-8 pokemon
