### ISSUE TITLE
Error when using large integers and proposed fix

### ISSUE THREAD

**Issue by mikesol** [PokeAPI/pokeapi#487]
Hi PokeAPI team!

Thanks for your awesome API.

My company is developing a service for automated testing of GitHub apps, and while testing it out on some public repos we found the following bug [in the `get_object` function from `api.py`](https://github.com/PokeAPI/pokeapi/blob/3c1115cf0c1bfab21c3900f26b9535e558d510bf/pokemon_v2/api.py#L41). Because sqlite does not support large integers, using a too-large integer as an `id` (ie `/api/v2/version-group/9223372036854775808/`) will cause the server to `500`.

There are a few possible fixes for this on the db-level (ie [this stack-overflow one](https://stackoverflow.com/questions/12150973/django-id-integer-limit)) and an app-level one would be to validate any integers in the query before sending in `get_object` and returning a sensible error code if the integer is too big or small.

We really enjoyed testing PokeAPI with Meeshkan, and if you find this bug report useful, I'd encourage you to sign up for free alpha access at https://meeshkan.com. Thanks again for your great work!

**Comment by Naramsim** [comment]
Hello @mikesol, thanks for sharing your results with us. Do you know if this bug is also present when running on Postgres, rather than SQLite?

**Comment by mikesol** [comment]
Hi, unfortunately I'm not sure if the bug is present on Postgres.

Mike Solomon
C.E.O., Meeshkan Machine Learning
https://www.meeshkan.com

Sent via Superhuman ( https://sprh.mn/?vip=mike@meeshkan.com )

**Comment by Naramsim** [comment]
@mikesol, would you be able to open a PR with one of the proposed fixes? Maybe the app-level one?

Thanks a lot!

**Comment by aitorres** [comment]
@Naramsim I might be able to do so! I can work on a PR with the app-level validation that the integer is not too large.
