### ISSUE TITLE
Is it possible to get a list of all pokemon of a specific species?

### ISSUE THREAD

**Issue by Urganot** [PokeAPI/pokeapi#489]
Is it possible to get a list of all pokemon of a specific species?

something like .../v2/pokemon?species=15

Or is my only option to get every pokemon and do the filter myself?

**Comment by Kronopt** [comment]
Hi Urganot,

Is [this ](https://pokeapi.co/docs/v2.html#pokemonspecies)not what you want?

ex: https://pokeapi.co/api/v2/pokemon-species/15

**Comment by Urganot** [comment]
Is there a face-palm-emoji?

yeah, thats exactly whaat i need. I overlooked that field.

thanks for your help
