### ISSUE TITLE
Missing moveset information

### ISSUE THREAD

**Issue by Tails0630** [PokeAPI/pokeapi#492]
The database doesn't provide information about Pokemon's egg and event moves such as island scan or global distributions.

**Comment by HybridShivam** [comment]
Yes I realised this as well, most egg and tutor moves are missing.

**Comment by jennie-quinton** [comment]
Is there any update on this. I have found some examples, like Ribombee and Hydreigon are missing move tutor moves,

**Comment by Naramsim** [comment]
Hi, it all depends on Veekun. If you find that kind of information on `Veekun/pokedex`, then we should also have it. If they don't provide it, then we don't do either.
