### ISSUE TITLE
Descriptions for moves 560  to 728 return various languages

### ISSUE THREAD

**Issue by klandaghi** [PokeAPI/pokeapi#501]
When pulling data via the API the default responses are in English for moves 1 through 559.  After that they start to vary.  Here is the code I'm using to pull the information for my google sheet.

function mv_desc(x) {
  // Function to pull move Description
  var req = 'https://pokeapi.co/api/v2/move/' + x;
  var response = UrlFetchApp.fetch(req, {'muteHttpExceptions': true});
  var resjson = response.getContentText();
  var res = JSON.parse(resjson);
  var pmAns = res.flavor_text_entries[2].flavor_text;
  return pmAns;  
  
}

x is a passed in variable that uses the move name of "first-impression", but you can use the move ID  of "660" and will get the same result.  I will also chase this at veekun's github in case this is just the data that is provided and not something screwy in the API.  I tried finding a way to force the desired language but have failed to be successful thus far.

Any help appreciated!
![PokeAPI-560+_random_lang](https://user-images.githubusercontent.com/6185740/85307568-4a58f400-b46d-11ea-9806-41680065b00a.png)

**Comment by HybridShivam** [comment]
As a rule of thumb whenever there's multi language text just loop through them all and select only those which match your required language rather than hardcoding the index for that language.
flavorTextEntry['language']['name']=='en'

**Comment by klandaghi** [comment]
When I had originally developed the code I'm working on, there wasn't multi language support, so I'm working to learn and figure that out.  Thanks for the point in the right direction.  I'm guessing that my hard code to the 2nd entry in the array is the issue and that after 559 it was no longer as uniform as the prior 559 entries.  Thank you for your assistance! 👍

**Comment by HybridShivam** [comment]
Glad to help, 
Please close the issue if it solved your problem. : )

**Comment by klandaghi** [comment]
function mv_desc(x) {
  // Function to pull move Description
  var req = 'https://pokeapi.co/api/v2/move/' + x;
  var response = UrlFetchApp.fetch(req, {'muteHttpExceptions': true});
  var resjson = response.getContentText();
  var res = JSON.parse(resjson);
  var num1 = -1;
  do {
    num1++;
  }while (res.flavor_text_entries[num1].language.name != "en");
  var pmAns = res.flavor_text_entries[num1].flavor_text;
  return pmAns;
  
}

**Comment by Naramsim** [comment]
@klandaghi no worries for hitting the server!

Glad that you came to a conclusion. 😄
