### ISSUE TITLE
Missing Back_Default Sprites

### ISSUE THREAD

**Issue by zekinah** [PokeAPI/pokeapi#506]
I did some research on the web, and I can't see any back sprites yet starts with Generation VI and up to the latest generation. since this API is depending on veekun updates so if he already got it. For the future update, I suggest including the back sprites of other pokemon since the other has that sprite. The last one we have is Genesect, I trust Chespin and others should have too. Thank you.

**Comment by magical** [comment]
There are no back sprites in gen VI or later, since the games started using 3d models.

**Comment by zekinah** [comment]
Yup, I know, but just maybe someday, since there are still 2d models set in  `front_default` that created for them.
Example:
https://pokeapi.co/api/v2/pokemon/amaura
`front_default:"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/698.png"`

Hoping we can have 2d models sprites for the `back_default` too for the gen VI to latest.
