### ISSUE TITLE
Unable to fetch data of some pokemons

### ISSUE THREAD

**Issue by FirezzzZ** [PokeAPI/pokeapi#507]
i cant get data of pokemons starting from 10001 till the last number. it returns me an error, though i use the same code to fetch 1-807 pokemons and they return data successfuly
help please.

**Comment by Naramsim** [comment]
https://pokeapi.co/api/v2/pokemon/10001 is working on my side. Can you please provide a broken URL?

**Comment by HybridShivam** [comment]
are you sure you are not using the `pokemon-species`endpoint ?

**Comment by FirezzzZ** [comment]
the url is working if u search it on the browser, but i get a bunch of errors when i fetch it with `node-superfetch` package.
ill send the error, in a few minutes

**Comment by FirezzzZ** [comment]
@HybridShivam you were right, i was fetching the species too.. thanks now i have figured the error.
