### ISSUE TITLE
is pokemon-species endpoint case sensitive?

### ISSUE THREAD

**Issue by FirezzzZ** [PokeAPI/pokeapi#510]
![image](https://user-images.githubusercontent.com/55920870/87672284-5a27d780-c790-11ea-885e-bc9c2f67e670.png)

![image](https://user-images.githubusercontent.com/55920870/87672314-6449d600-c790-11ea-8c30-a468a4669cd0.png)

**Comment by Naramsim** [comment]
I guess all our named endpoints are case-sensitive. This is something we can surely change. I guess the trick would be to modify our Firebase function.

https://pokeapi.co/api/v2/pokemon/Eevee

**Comment by Naramsim** [comment]
The best thing would be to add a `.lowercase()` on `target` here:

https://github.com/PokeAPI/deploy/blob/af42acbf0325a28c1c66946a2acb5ea42b3b4e6b/functions/src/index.ts#L15

**Comment by FirezzzZ** [comment]
ohk thanks

**Comment by FirezzzZ** [comment]
im using `.toLowerCase()` in my code
