### ISSUE TITLE
error "500" on endpoint 'pokemon/10150' only

### ISSUE THREAD

**Issue by FirezzzZ** [PokeAPI/pokeapi#511]
![image](https://user-images.githubusercontent.com/55920870/87869842-a8bbb880-c9c0-11ea-8764-8b6021a4dfba.png)

**Comment by Naramsim** [comment]
That's strange on my side both the website and the API work.

https://pokeapi.co/api/v2/pokemon/10150

Could you please re-try?

**Comment by FirezzzZ** [comment]
![image](https://user-images.githubusercontent.com/55920870/87873181-fa723c00-c9dc-11ea-95c0-c199b25b8bd0.png)
nope

**Comment by FirezzzZ** [comment]
![image](https://user-images.githubusercontent.com/55920870/87873188-11189300-c9dd-11ea-8899-c38be963c4c5.png)
this works though

**Comment by FirezzzZ** [comment]
![image](https://user-images.githubusercontent.com/55920870/87873246-83897300-c9dd-11ea-9e8c-42db1e4daced.png)
lmao now it worked

**Comment by FirezzzZ** [comment]
closing this as its fixed for me
