### ISSUE TITLE
Certain aspects (possibly USUM) incomplete

### ISSUE THREAD

**Issue by Amaterasu5** [PokeAPI/pokeapi#532]
It looks like some new abilities/moves introduced in ultra sun and moon are still incomplete. The few I've encountered so far are **Neuroforce**, Ultra Necrozma's ability, and move descriptions for **Plasma Fists** and **Light That Burns The Sky**, Ultra Necrozma'z Z-Move. This may apply to other USUM data as well.

**Comment by Naramsim** [comment]
Could you list some missing abilities?

**Comment by Amaterasu5** [comment]
Ah it looks like the "short_effect" field is what's wrong. Not missing, just the data is incomplete. 

For example, Neuroforce's description is "XXX new effect for neuroforce" and Plasma Fists' description is "inflicts regular damage with no additional effect", but the move also makes all normal moves used for the duration of the turn into electric moves.

**Comment by Amaterasu5** [comment]
@Naramsim hey so I know this is probably super low priority for you guys. Would I be able to just fix the issue?

**Comment by phalt** [comment]
@Amaterasu5 you can make a pull request, that would really help!

**Comment by Amaterasu5** [comment]
sure thing!
