### ISSUE TITLE
Slack workspace requires account.

### ISSUE THREAD

**Issue by parkerault** [PokeAPI/pokeapi#534]
Since the slack workspace is linked from the new issue template, it should be open to the public, no? As far as I can tell there isn't a way to create a new account for the pokeapi workspace.

**Comment by Naramsim** [comment]
Hi @parkerault, doesn't our [invitation app](https://pokeapi-slack-invite.herokuapp.com/) work anymore?

Let us know!

**Comment by parkerault** [comment]
@Naramsim looks like it does, but if one is coming to the new issue screen without knowing about the invite app (as I did), then one hits a dead end. Perhaps updating the new issue template would help.

**Comment by Naramsim** [comment]
Yep, I will do it! Thanks a lot for spotting this issue!

**Comment by Naramsim** [comment]
I've done it. :) What do you think?
