### ISSUE TITLE
Normalized entities in JSON data?

### ISSUE THREAD

**Issue by parkerault** [PokeAPI/pokeapi#536]
I asked about this in the Slack channel but didn't get any responses. I looked through the documentation but couldn't find any mention of this; is it possible to ask an endpoint for normalized entity data? Currently the entity relationships are eagerly fetched, so, for example, a berry has a list of flavors, and the flavor entities are included in the json payload for the berry entity.
```jsonc
{
  "id": 1,
  "name": "cheri",
  /*... snip ... */
  "flavors": [
    {
      "potency": 10,
      "flavor": {
        "name": "spicy",
        "url": "https://pokeapi.co/api/v2/berry-flavor/1/"
      }
    }
  ],
}
```
I would like to be able to send a query parameter or header that asks the endpoint to return references to relations instead of nesting them:
```jsonc
{
  "id": 1,
  "name": "cheri",
  /*... snip ... */
  "flavors": [
    "https://pokeapi.co/api/v2/berry-flavor/1/",
  ],
}
```
Of course this requires more API requests to fetch the data the client requires, and I know PokeAPI relies heavily on cacheing. However, it's easier to parse if you are using a stateful client UI (since the client state should already be normalized), and it uses less bandwidth. If the service is using HTTP2 the latency issue from multiple requests is mostly mitigated. Is this something that is supported, or that could possibly be supported in the future? I'd like to use PokeAPI in examples when I'm coaching, but normalizing json payloads adds complexity that I'd rather not focus on (payload normalization is its own topic of study).

**Comment by Naramsim** [comment]
Hi @parkerault, no we don't support what you are asking for :( 

The API is as you see it. There are not hidden ways of customizing what's returned.

**Comment by sophiebushchak** [comment]
Is it not mostly normalized already? Aside from berries having BerryFlavorMap for its flavors field, many endpoints such as _pokemon/{id}_ for example have a field like _pokemon-species_ which then do simply contain a reference to the data.
I think the reason
