### ISSUE TITLE
Weight not correct

### ISSUE THREAD

**Issue by LachlynR** [PokeAPI/pokeapi#538]
When I go to "https://pokeapi.co/api/v2/pokemon/charizard".

Charizards weight says 905, but it is 90.5kg (according to [pokemondb.net](https://pokemondb.net/pokedex/charizard). I am assuming that kilograms is the unit of measurement since the numbers are correct, just no decimal point. Haven't checked other pokemon yet.

**Comment by infmja** [comment]
The weight is in hectograms according to the [documentation](https://pokeapi.co/docs/v2#pokemon), therefore it is correct.

**Comment by LachlynR** [comment]
Oh ok yes that makes a lot of sense, thank you
