### ISSUE TITLE
API's slow response

### ISSUE THREAD

**Issue by AryanXdProYT** [PokeAPI/pokeapi#542]
I am using this api since some weeks and it was working perfectly and i am using Pokepy moduke of it but today the api response time is taking 6min to get a pokemon or anything i have tested alot i used pokebase and pokepy to check but noth taking time to get the data from website please check to it since my discord bot is totally shutdown due to this. Here is the Proof of output when i try in console it takes 6 Minutes to response
![Screenshot_2020-12-02-16-15-56-92_c759c44d10a956b96f85cc66750ff86e](https://user-images.githubusercontent.com/74323090/100862890-c4c87e00-34b9-11eb-86f5-636922f6266c.jpg)

Thank you

**Comment by AryanXdProYT** [comment]
Please Fix to it asap

**Comment by Naramsim** [comment]
@AryanXdProYT Hi.

I experienced also a slowdown followed by a 504. But that happened only once. [Our monitoring page](https://updown.io/akzp) didn't log any downtimes nor slowdowns.

I strongly suspect that Cloudflare, for some of the requests, is having some troubles. 

We cannot really do anything about it.

**Comment by Naramsim** [comment]
Also, are you sure that it's not your network that's slow?

**Comment by AryanXdProYT** [comment]
I has been using it in my mobile since 2-3 weeks working perfectly with max 5 seconds response but from today its response is taking time now the time is like 15min per response

**Comment by Naramsim** [comment]
Well, first of all, the API should reply back in max 500ms, not 5 seconds. So if you're getting those times something is slow on your end. 

I don't know how to help you, tbh. Let's keep this issue open for some days to see if other users are experiencing the same.

**Comment by phalt** [comment]
> Please Fix to it asap

This is not a good attitude, we're volunteers, and humans. Please be polite!

Fifteen minutes is an insane response time given that most HTTP clients time out after 60 seconds, I suspect something is up with your network configuration.

This is a great reminder to always cache results and don't rely on third party APIs!

**Comment by AryanXdProYT** [comment]
I am really sorry for that but i didnt mean rude to you but forgive me for
that , and today its was working fine so i think to tell you , and also i
want to ask ine more thing in pokepy
pokepy.V2Client().get_pokemon(limit=100,offset=0) only showing first 20 can
u help me with this
Thank you and really srry but i didnt mean to be rude to you

**Comment by Kronopt** [comment]
What you're doing is not specified in the pokepy documentation.

Pokepy doesn't actually implement the `limit` and `offset` parameters.
You're basically calling the API with the default pagination parameters of `limit=20` and `offset=0`.

**Comment by Naramsim** [comment]
Thanks @Kronopt for pointing it out. @AryanXdProYT, I suggest you to read the [documentation of pokepy](https://pokeapi.github.io/pokepy/usage/) before using it.

I'm closing this issue since no one else reported the API being slow and also because it has diverged from the original question.

**Comment by AryanXdProYT** [comment]
Ohk So can u tell how can i get the pokemons list sorted by dex through pokepy or any module in python

**Comment by Naramsim** [comment]
Apparently, you cannot retrieve a root endpoint using that wrapper. I checked also https://github.com/PokeAPI/pokebase but no luck. 

Your best bet right now is to:

- Use a Python module to make HTTP requests
- Open a feature request in one of those two repositories
- Use the [dex endpoint](https://pokeapi.co/api/v2/pokedex/1/) to list all pokemons belonging to a specific `pokedex`
