### ISSUE TITLE
pokemon #821(Rookidee) evolution tree is incorrect

### ISSUE THREAD

**Issue by shovanshahi373** [PokeAPI/pokeapi#544]
the actual evolution tree is rookidee -> corvisquire -> corviknight,
but this resource https://pokeapi.co/api/v2/evolution-chain/433/ infers that tree to be rookidee -> (corvisquire || corviknight), 
which is incorrect.

**Comment by Naramsim** [comment]
You are right! I'll see if I can release a fix
