### ISSUE TITLE
https://pokeapi.co/api/v2/pokemon/878 returns 404 on linux, but not on windows (browser and postman)

### ISSUE THREAD

**Issue by Disco-Chef** [PokeAPI/pokeapi#546]
https://pokeapi.co/api/v2/pokemon/878 returns 404 on linux.

Steps to Reproduce:

Hit the api from Ubuntu or whatever linux distro you like. Browser, postman, curl etc

For some weird reason, it works on windows (browser, postman) 🤷‍♂️

**Comment by Naramsim** [comment]
Hmm, I strongly suspect that it's a specific issue with your Linux machine. We serve data through Cloudflare and it seems to me extremely unlikely that Cloudflare blocks Linux UA. 

Have you modified your `/etc/hosts`? Which DNS are you using?

Consider that most of our callers are cloud servers, which means Linux distributions.

**Comment by Disco-Chef** [comment]
I am not on linux, however my colleagues are. We are making requests, up to id of 893, and 878 specifically gives a 404 on my colleagues' machines and on heroku, but not on my machine. I admit, i may have jumped the gun a bit. Will close and investigate further

**Comment by Disco-Chef** [comment]
In the case of our project, hosted on heroku cloud server:

![image](https://user-images.githubusercontent.com/49205098/102768474-879d3080-4381-11eb-8ac8-a08d3d8dd825.png)

**Comment by Naramsim** [comment]
Can you try this: https://pokeapi.co/api/v2/pokemon-species/878

**Comment by Naramsim** [comment]
Moreover, can you try with `curl` or `wget`? 

What's your `RestClient`?

**Comment by Disco-Chef** [comment]
I can as I am on windows and it returns the right json. not so for my colleagues though. 
Same for curl: it works for me but not for colleagues, they get Not Found%

A ruby gem: 
https://github.com/rest-client/rest-client

But if it works with anyone else on linux, then I dunno, must be something else on our end

**Comment by Kronopt** [comment]
I tested with wsl and it works ok.
I don't have a proper linux machine handy for testing, though.

Can you provide more details on the linux machines your colleagues used to query the API?

**Comment by Naramsim** [comment]
I tried from my Linux machine and both with `wget` and `curl` it works fine. 

If you are behind a proxy/VPN, that might affect it. Maybe it's a Heroku thing. Other than that I don't know what to say.

**Comment by Naramsim** [comment]
Or maybe you are behind a cache like Squid that doesn't update.
