### ISSUE TITLE
i cant find the pokemon wishiwashi

### ISSUE THREAD

**Issue by emiloogi** [PokeAPI/pokeapi#547]
help

**Comment by Naramsim** [comment]
Hi @emiloogi, sorry for it :( 

We mapped it with the name `wishiwashi-solo`.

You can find it here:

https://pokeapi.co/api/v2/pokemon/746
https://pokeapi.co/api/v2/pokemon/wishiwashi-solo

A cool strategy for the future: to get rid of this problem you could fire two HTTP requests, the first one for getting the species for wishiwashi: https://pokeapi.co/api/v2/pokemon-species/wishiwashi/

Which returns the two varieties for this pokemon (`solo` and `school`)

```json
...
"varieties": [
    {
        "is_default": true,
        "pokemon": {
            "name": "wishiwashi-solo",
            "url": "https://pokeapi.co/api/v2/pokemon/746/"
        }
    },
    {
        "is_default": false,
        "pokemon": {
            "name": "wishiwashi-school",
            "url": "https://pokeapi.co/api/v2/pokemon/10127/"
        }
    }
]
...
```

And then get both of those two Pokemon :smile:, pretty cool, right?
