### ISSUE TITLE
missing sprites and artwork

### ISSUE THREAD

**Issue by aabeborn** [PokeAPI/pokeapi#550]
Hi, using the pokeapi as Pokédex I see some sprites and artwork are missing. 

For pokemon ids: 896 and 897 all sprites, artwork are missing 
For pokemon ids:894-895-896-897-898
and for these one(probably not all of them as an official artwork) 10027-10028-10029-10030-10031-10032-10061-10080-10081-10082-10083-10084-10085 and from 10091 to 10219 official artwork are missing

I can search for artwork or sprites if they are missing but you have to guide me a little (I am a frontend dev)

**Comment by C-Garza** [comment]
Hello @aabeborn, there is actually a separate repository for [sprites linked here](https://github.com/PokeAPI/sprites) where you can contribute sprites. 

For 894-898 you could probably find official artwork on the pokemon site. The 10000 id's are for different pokemon forms, so they might not have official artwork. I think that the pikachu one's (10080 - 10085) have official artwork, you could try checking [Veekun](https://veekun.com/dex/media/pokemon/sugimori/).

**Comment by aabeborn** [comment]
Thanks, I have created a merge request with some artworks which are missing. 
I have also some points about some pokemon forms:
- Arceus (which has different forms based on instruments)
- Minior has different colours on core form, but all of them are present also in the meteor form which has only one form
- Miss all forms of furrow
- Miss all falbebe,Floette, Florges forms
- Miss all vivillion forms
- Miss all genesect forms 
- Miss shellos and gastrodon forms
- Miss cherrie form
- Miss Burmy form
- All castform forms artworks are wrong
- Darmanitan zen artwork Is wrong
- Miss different unknown forms 
- Miss Pichu form with special ear
- Miss pickachu world cup
- Miss rotom phone and pokedex
- Miss deerling and sawsbuck forms
- Miss silvally forms
- Miss cramorant forms
- Miss alcremie forms\
- Miss sinistea and polteageist forms
- Miss morpeko angry mode
- Miss marshadow form
- Miss solgaleo and lunala alternative form

Also Not found any pickachu cosplay, eiscue, darmanitan zen and gala zen mode mimikyu busted artworks and is Colette eternal a real Pokemon ? 


Not sure if this list is right to be here but before creating issue without any sense I prefer to ask, also because I've found all of this forms scrolling on bulbapedia :)

**Comment by Naramsim** [comment]
Let's think later about forms.

For the items you listed as 'wrong', can you clarify a bit? Maybe opening separate issues over at PokeAPI/sprites?

**Comment by aabeborn** [comment]
Darmanitan zen it is used the artwork of normal darmanitan which is wrong or at least different

About castform... it has the various forms based on weather, but all the artworks are the same of the standard form

**Comment by Naramsim** [comment]
Ok, I closed the PR over at the sprites repo. Now we can start with the errors one by one.

**Comment by GuserHub23** [comment]
Hola, un error, o amenos yo lo veo así, es que hay un " - " en el official artwork, entonces ya no puedo acceder al dato.

**Comment by Naramsim** [comment]
Hello @GuserHub23, yes, we are aware of dashes (`-`) in our keys. Which language are you using to fetch the sprites? 

There should be a way of quoting the URL you are fetching so that you can have dashes in it.
