### ISSUE TITLE
Add a property "can_be_held" for holdable items like berries, mega stones, etc.

### ISSUE THREAD

**Issue by ChrisMGeo** [PokeAPI/pokeapi#551]
This feature request is for adding a boolean property for items to know whether or not it can be held by a pokemon.

**Comment by Naramsim** [comment]
Hello, this feature is already present in our API.

https://pokeapi.co/api/v2/item-attribute/5/ lists all `holdable` items.

You also have here the items that will do _something_ when in battle: https://pokeapi.co/api/v2/item-attribute/7/
