### ISSUE TITLE
Mimikyu not found by name!

### ISSUE THREAD

**Issue by Kerilet** [PokeAPI/pokeapi#555]
Good night! I was looking for Mimikyu, however, when I tried to search for it, I was greeted by a blank page with the text "Not Found". At first, I went and tested other gen 7 Pokémon such as Turtonator and Komala to see if it wasnt a problem with the whole generation, but it seems to me that it is a problem only related to Mimikyu's name, as when you try to search it by it's dex number, you get the corresponding page with all the correct info. 

Steps to Reproduce:

1. Go to the page : https://pokeapi.co/api/v2/pokemon/778
2. Replace "778" with "mimikyu"
3. "Not Found"

**Comment by andreferreiradlw** [comment]
That Pokemon is under a different name, I believe you're looking for this: 
https://pokeapi.co/api/v2/pokemon/mimikyu-disguised

**Comment by Naramsim** [comment]
Yeah, the Pokemon itself is called `mimikyu-disguised`.

You can query for it's species by the name of `mimikyu`. https://pokeapi.co/api/v2/pokemon-species/mimikyu
