### ISSUE TITLE
Electric Type link doesn't work with forward slash in the end.

### ISSUE THREAD

**Issue by ChrisMGeo** [PokeAPI/pokeapi#557]
Every type URL works with/without a forward slash in the end, however for some reason electric-type doesn't work with the forward slash.
Steps to Reproduce:
1. Go to https://pokeapi.co/api/v2/type/13 to compare with error.
2. Go to https://pokeapi.co/api/v2/type/13/ to see error.

**Comment by Naramsim** [comment]
These days we are having some issues with our cache provider: Cloudflare.

Which part of the world are you from? From central EU both the endpoints are returning `200`

**Comment by ChrisMGeo** [comment]
I live in the US, but it may be something wrong with my PC or browser.

**Comment by ChrisMGeo** [comment]
Nope my PC or browser doesn't seem to be it. Maybe my ISP?

**Comment by ChrisMGeo** [comment]
This got fixed on my end!

**Comment by Naramsim** [comment]
Yeah, the issue was really on our Cloudflare end.
