### ISSUE TITLE
Vaporeon not found by id

### ISSUE THREAD

**Issue by ericksvaguilar** [PokeAPI/pokeapi#560]
Searching Vaporeon by the ID (134) is retriving "Not Found"

Steps to Reproduce:

1. Go to: https://pokeapi.co/api/v2/pokemon/134
2.  "Not found"

**Comment by Naramsim** [comment]
Can you check also now?

I purge twice the Cloudflare cache.

**Comment by ericksvaguilar** [comment]
It's working, thanks 😉
