### ISSUE TITLE
Jolteon URL returns a 404 (#135)

### ISSUE THREAD

**Issue by WoetDev** [PokeAPI/pokeapi#561]
Hi

I noticed since today the URL mentioned for Jolteon is returning a 404 error. 

Steps to Reproduce:

1. Follow url from Jolteon mentioned here: https://pokeapi.co/api/v2/pokemon?limit=1&offset=134
2. Returns a 404 Not Found error.
3. It only returns the JSON after removing the ending '/' (i.e. https://pokeapi.co/api/v2/pokemon/135/ --> https://pokeapi.co/api/v2/pokemon/135)

**Comment by Naramsim** [comment]
I worked for me. Anyway, I'm purging the cache.

Can you come back with an update?

**Comment by WoetDev** [comment]
Seems to still occur in any browser for me as well as with a cleared cache, I'm running on Windows 10. 

I've exported the logs of a failed request to https://pokeapi.co/api/v2/pokemon/135/ and a successful one to https://pokeapi.co/api/v2/pokemon/135. Don't know if that could help? 

Anyways, since it's just the last '/' that causes it to not work for me, I can work around it so it's not blocking. 

[failed_request_pokeapi.co.har.txt](https://github.com/PokeAPI/pokeapi/files/5857020/failed_request_pokeapi.co.har.txt)
[successful_request_pokeapi.co.har.txt](https://github.com/PokeAPI/pokeapi/files/5857021/successful_request_pokeapi.co.har.txt)

**Comment by Kronopt** [comment]
We should find out what is causing all these caching issues.
We've been having quite a few of these issues lately.

**Comment by xavierLowmiller** [comment]
I'm seeing a similar issue with a generations endpoint:

* `https://pokeapi.co/api/v2/generation/6` works
* `https://pokeapi.co/api/v2/generation/6/` doesn't

In this case, I find that clearing the cache doesn't help. I've tried different scenarios (browser,`httpie`, `cURL`) with identical results.

**Comment by Naramsim** [comment]
Yeah, we are having a lot of issue with cloudflare. It's cloudflare serving invalid results

**Comment by setsuya** [comment]
Chiming in to say that there are cases of the opposite... The resource returns correctly *with* the trailing `/` and returns a `404` without it. For example:

https://pokeapi.co/api/v2/move/111 returns a `404`on my end...
while https://pokeapi.co/api/v2/move/111/ returns correctly with the data for Defense Curl.

On my end I can always retry once in case of an error anyways but it would be nice if at least the "error" was uniform and I could just use the url with or without the trailing slash.

**Comment by Naramsim** [comment]
Yeah, it's not an issue with our code. It's a Cloudflare issue, right now I don't have any idea on how to overcome it.

**Comment by Salad7** [comment]
This issue is still going on

**Comment by Naramsim** [comment]
I don't see any issues on my side

**Comment by Salad7** [comment]
Thanks, i fixed the issue
