### ISSUE TITLE
Sprite links missing from API for non-default varieties, even though the sprites exist in the repo

### ISSUE THREAD

**Issue by zacbullard** [PokeAPI/pokeapi#565]
Hi All,

Let's take Alolan Raichu for example, his sprite front_default is here... 

https://github.com/PokeAPI/sprites/blob/master/sprites/pokemon/26-alola.png

... And while his variety call is here... 

https://pokeapi.co/api/v2/pokemon/raichu-alola/

... The link on the call is null, even though the sprite indeed exists. Only the other official-artwork front_default file is linked for Alolan Raichu, but that's a different image of course.

I have a complete list of 129 pokemon missing their front_default sprites, all of them non-default varieties (galarian, totem, gmax, etc.):
[missing_sprites.txt](https://github.com/PokeAPI/pokeapi/files/5861465/missing_sprites.txt)

I'm not sure what the best way to help insert these links would be, but if you want this list in another format (their id numbers, or their pokemon api urls, etc.), I'd be happy to provide them.

**Comment by C-Garza** [comment]
The sprites are built from that `pokemon` endpoint using their id's. Raichu-alola has an id of `10100`, but it doesn't have a corresponding `10100.png`. A fix would be to make a copy of that image and then rename the copy `10100.png` and the api should then find it. If you want to make a pull request, you can do it in the [sprites repo](https://github.com/PokeAPI/sprites).

**Comment by zacbullard** [comment]
Thanks for the clarification, I'll see if I rename those files using the appropriate IDs.

**Comment by zacbullard** [comment]
Ok, just I updated the names and put in a pull request. If it all goes well I'll close out this issue.
https://github.com/PokeAPI/sprites/pull/42

**Comment by Naramsim** [comment]
Ok, we can close this one
