### ISSUE TITLE
Bibarel url not working with '/'

### ISSUE THREAD

**Issue by rodrigoantas** [PokeAPI/pokeapi#569]
Hello! i'm having a issue with pokemon 400, bibarel. If the URL is https://pokeapi.co/api/v2/pokemon/400, it works, but if it's https://pokeapi.co/api/v2/pokemon/400/ it doesn't.
Steps to Reproduce:

1. enter: https://pokeapi.co/api/v2/pokemon/400/ , it doesn't work
2. then, enter: https://pokeapi.co/api/v2/pokemon/400 , it works fine

I'm having trouble with this because i'm using axios do get the data from the api, and axios returns the url with the slash.

**Comment by Naramsim** [comment]
This is a Cloudflare issue.

Read more here:

https://github.com/PokeAPI/pokeapi/issues/561
https://github.com/PokeAPI/pokeapi/issues/553

**Comment by Naramsim** [comment]
This should be a temporary issue with your closest Cloudflare datacenter. In theory after maximum 24 hours it should resolve.
