### ISSUE TITLE
Type weaknesses listed on Pokémon and dual-types

### ISSUE THREAD

**Issue by jwhunt19** [PokeAPI/pokeapi#570]
I can't find a way to easily tell the type weaknesses of dual-typed Pokémon. I see there is a separate set of endpoints for types individually but I don't see any resource in this API for the weaknesses of dual-typed pokemon.

Beyond that issue, I think it would just be easier to list the type weaknesses for every Pokémon right on their data.

**Comment by Naramsim** [comment]
hi @jwhunt19, you can compute the multipliers by using a formula. Basically, you need to multiply the two types.

**Comment by Naramsim** [comment]
https://www.quora.com/In-Pokemon-how-is-weakness-calculated-for-dual-type-Pokemon-such-as-a-rock-ghost-type-when-hit-with-a-fighting-attack-Is-the-attack-still-negated-due-to-the-ghost-typing-or-does-the-Pokemon-still-take-double-damage#:~:text=When%20it%20comes%20to%20dual,damage%20to%20Fire%20type%20attacks.

**Comment by jwhunt19** [comment]
@Naramsim I have played Pokémon regularly for 24 years and I never realized that is how dual-types were calculated!

I would still love to see type weaknesses on Pokémon data, but this revelation is extremely helpful. I'm working on a time-sensitive school project so your hasty response is incredibly appreciated. Thank you.
