### ISSUE TITLE
Pokédex entries

### ISSUE THREAD

**Issue by raphaelwilker** [PokeAPI/pokeapi#573]
Hi !
I'd like to suggest a feature request for Pokédex entries conforms by generation.
Thanks for all folks !

**Comment by Naramsim** [comment]
Hi, could you explain a bit more, maybe also with an example?

**Comment by raphaelwilker** [comment]
Yes, I will try to explain.
Each pokedex has a Pokémon Entries that description about that pokémon.
For example Bulbasaur, at Pokémon Red and Blue your Pokémon Entrie is:
"A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon."
At the Pokémon Yellow:
"It can go for days without eating a single morsel. In the bulb on its back, it stores energy."
In case my explanation ins't clear I will post two links for explain better.
https://bulbapedia.bulbagarden.net/wiki/Bulbasaur_(Pok%C3%A9mon)
https://www.youtube.com/watch?v=KGuRt7Mla-Q&list=PLmsMGFIWAJdJgfKNpqukhevp6ebcm2-p7&index=16
Thanks for the attention.
Sorry my bad English.

**Comment by Naramsim** [comment]
Ok, I sort of understood what you are saying. 

I think we already provide such functionality. 

If you query the `/pokemon-species/{id}` endpoint you get a JSON (ex: https://pokeapi.co/api/v2/pokemon-species/1). In the property `.flavor_text_entries[]` you get all the flavor text entries for all Nintendo games.

Was this what you were asking?

**Comment by raphaelwilker** [comment]
Hi !
Thank you so much !
This is not clear to me before, but now I can understand.
Thank you so much again !
