### ISSUE TITLE
/move/371/ returns a 404, but /move/371 works

### ISSUE THREAD

**Issue by richard-yin** [PokeAPI/pokeapi#574]
Steps to Reproduce:

1. Try to query /move/371/ with any browser or application.

/move/371, /move/370/, and /move/372/ all seem to work properly. This broke the wrapper I was using since /pokemon/amoonguss has the affected URL in its move list.

**Comment by evayde** [comment]
Same with 

`location-area/168/` and `location-area/168`

**Comment by blfunex** [comment]
Same with `https://pokeapi.co/api/v2/pokemon/4/` and `https://pokeapi.co/api/v2/pokemon/4`.

![image](https://user-images.githubusercontent.com/11468624/110213492-95eaeb00-7ea0-11eb-829c-7e18851f5d0a.png)
![image](https://user-images.githubusercontent.com/11468624/110213501-a1d6ad00-7ea0-11eb-8d32-c969c6b1d29b.png)

**Comment by efoerster** [comment]
Found the opposite behavior: `/item/antidote` returns 404 but `/item/antidote/` works.

**Comment by Naramsim** [comment]
Hello,

this issue was resolved by https://github.com/PokeAPI/deploy/pull/23
