### ISSUE TITLE
Missing legendary Pokemon encounters.

### ISSUE THREAD

**Issue by SimplyBLGDev** [PokeAPI/pokeapi#576]
There are no entries for any legendary encounters in the API despite other event encounters (like starters) being present, legendaries should be included.

**Comment by phalt** [comment]
Hey @SimplyBLGDev thanks for your astute observations - we didn't even know that data was missing.

Until about a year ago, we relied on 3rd parties for our data, so if theirs was missing it - ours was too.

We've started to update and include our own data now as many people wanted to contribute.

Would you like to start contributing?

**Comment by SimplyBLGDev** [comment]
I would like to start contributing, I tried to do so like a year ago but ran into some problems setting up the environment, I'll be trying again, however there's a couple of fairly large necessary changes to fix some issues with the database (Mostly referring to the encounters tables) and I'd need to discuss these changes with the core team first, is there any channel of communication that we could use? I noticed the Slack channel is pretty deserted.

**Comment by Naramsim** [comment]
We can discuss here :)

**Comment by SimplyBLGDev** [comment]
We'll need a couple extra encounter methods, one for static Pokémon like Snorlax, another for legendaries and other one-fight only and another for roaming Pokémon. On the topic of roaming Pokémon we'll need additional locations to house these.
Also new encounter conditions:

- The Legendary beasts were awakened (For GSC HGSS, Raikou Entei and Suicune)
- Bulbasaur Starter (For FR LG Entei)
- Squirte Starter (For FR LG Raikou)
- Charmander Starter (For FR LG Suicune)
- Picked red on the TV at the start of the game (For E Latias/Latios)
- Picked blue on the TV at the start of the game (For E Latios/Latias)
- Visited Lake Verity after defeating Team Galactic at Mt. Coronet (For DPPt Mesprit)
- Cured Eldritch's son (For DPPt Cresselia)
- Talked to Professor Oak in Eterna City (For Pt Articuno/Zapdos/Moltres)
- Visited the Vermilion City Pokémon Fan Club with Copycat's doll (For HGSS Latios/Latias)
- The complex conditions for BW Tornadus and Thundurus
- Chespin Starter (For XY Zapdos)
- Fennekin Starter (For XY Moltres)
- Froakie Starter (For XY Articuno)

The new encounter methods should be:
- Pokéflute (For Snorlax in RBY FRLG XY...)

The new location and location areas should be:
- All of Johto (For Raikou Entei Suicune in GSC HG SS)
- All of Kanto (For Latias Latios in HG SS and Raikou Entei Suicune in FR LG)
- All of Hoenn (For Latios Latias in RSE)
- All of Sinnoh (For Articuno Zapdos Moltres Mespirit Cresselia in DPPt)
- All of Unova (For Tornadus and Thundurus)
- All of Kalos (For Articuno Zapdos Moltres in XY)
- Gen 2's Kanto Victory road (it has different areas to the other Kanto Victory roads so it'll probably need a different location)

The new encounters should be:
- Snorlax in Routes 12 and 16 (FR LG RBY)
- Snorlax in Routes 11 and 12 (HG SS)
- Snorlax in Vermilion City (GSC)
- Every Headbutt encounter for GSC (A comprehensive list exists in [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Headbutt_tree))

If I can setup the environment correctly I'll be opening a PR with these fixes.

**Comment by SimplyBLGDev** [comment]
While working on my branch I noticed a few notable problems:

- Headbutt encounters are a complex mechanic and it requires more than one method slot, without mined data I can't know for certain the slot rates.
- Mt. Silver is very strange, areas don't seem to match up with their encounter, all of it's floors are out of order and I can't figure out which is which, it's probable that we'll have to re-import that entire area.
- The location areas table is about 50% junk data, a query should be run to eliminate all unused areas.

Anyways, I was wondering if you have the mined data for the headbutts or something and if you can re-import Mt. Silver, in the meantime I'll open a PR with what I've done so far, all of RBY, GSC, RSE, FRLG and HGSS updated with special encounters (except for Mt. Silver).

**Comment by Naramsim** [comment]
Hi @SimplyBLGDev, we cannot re-import the data. We take the data from `veekun/pokedex`. Moreover, I'd suggest you go step by step with the PR so we can properly review them. So forget about headbutt and mt. silver for now.

**Comment by SimplyBLGDev** [comment]
I've written PR #583, it addresses some but not all of the missing legendary Pokémon, another future PR will be written with the rest of the missing information.

**Comment by cyrillelegrand** [comment]
Hi @SimplyBLGDev, did you make any further progress on this? Notably, I've found that lengendaries still have no encounters in ROSA (eg. Kyogre, Groudon and Rayqyaza only have encounters in RS).

**Comment by SimplyBLGDev** [comment]
Yes, I do have a list of missing encounters and I'll add them at some point, there's some work to be done first
