### ISSUE TITLE
No encounter information for scripted item battles.

### ISSUE THREAD

**Issue by mylogon341** [PokeAPI/pokeapi#577]
Go to Mew or Zaptos encounters. Gen 1 has these encounters, but you need to tap action on a poke ball on the ground. They are not listed here.
Some encounters are marked as "gift" (ie starters) so I can't see why these can't be added as something similar. 
Also, trades aren't listed. ie Mr Mime can be traded for an Abra. This seems like useful information.
Can this information be found elsewhere in this api? 
Thanks a lot.

ps
Sorry for poor formatting/ lack of examples. I'm on mobile.

**Comment by mylogon341** [comment]
Also, snorlax is another example in gen 1

**Comment by Naramsim** [comment]
> Go to Mew or Zaptos encounters. Gen 1 has these encounters, but you need to tap action on a poke ball on the ground. They are not listed here.

True, we need someone to add those. And also to properly discuss how to call this encounter method.

> Also, trades aren't listed. ie Mr Mime can be traded for an Abra. This seems like useful information.

About this one, I'm not sure. You can trade a pokemon for any other pokemon. Do you mean that we aren't exposing data about pokemon evolutions through the use of trading? If so we have it here: https://pokeapi.co/api/v2/evolution-trigger/2/

**Comment by mylogon341** [comment]
Sorry for the missing detail on that last point. 
In Gen 1, to obtain a Mr. Mime, you need to trade an Abra (red/ blue) or Clafairy (yellow) with someone off route 2. This could be formatted much the same as a gifted pokemon with chance being 100%, and method being just "Trade".

**Comment by SimplyBLGDev** [comment]
I've written PR #583, which addresses this issue.

On the topic of trading I think we'd need a brand new table for this since NPC trades require a specific requested Pokémon, which could not be reflected in the encounters table and it also brings additional information (such as nickname of the received Pokémon, held item) which wouldn't appear in the encounters table.

**Comment by mylogon341** [comment]
10/10
My son is going to be very pleased with this :D 

I'll close this for now as it's off-topic for the trades data.
