### ISSUE TITLE
https://pokeapi.co/api/v2/pokemon/65/  -returns 404, but just first of

### ISSUE THREAD

**Issue by pfeihun** [PokeAPI/pokeapi#582]
First of: 
Thank you soo much! This is an awesome API!
Steps to Reproduce:

1. Follow the url : https://pokeapi.co/api/v2/pokemon/?offset=60&limit=20
2. try  "alakazam"
3. A first of 404 Not Found ( 404 )
4. Then refresh and all of the data is there

Best Regards
Zoli

**Comment by Naramsim** [comment]
We've just rolled out a new version of our API. Could you tell us if, in the future, you'll see again this kind of error?

**Comment by pfeihun** [comment]
Yes of course, if I find something that I tell for you. 

Thank you so much!
