### ISSUE TITLE
Add encounter condition to encounter details

### ISSUE THREAD

**Issue by SimplyBLGDev** [PokeAPI/pokeapi#584]
It would be useful for sorting and to avoid querying the encounter-condition-value
![image](https://user-images.githubusercontent.com/61010688/110241491-f2e1b200-7f2f-11eb-94b2-ceb50088c875.png)

**Comment by Naramsim** [comment]
We cannot do this, our API is architected in this way, and if we allow this change then we would need to allow it for every other resource.
