### ISSUE TITLE
basculin is not found

### ISSUE THREAD

**Issue by Whisperyraptor** [PokeAPI/pokeapi#585]
- Provide a clear description of the issue.
There is no entry for basculin - pokemon number 550.

- Provide a clear description of the steps to reproduce.
1. Search for basculin https://pokeapi.co/api/v2/pokemon/basculin
2. Returns undefined

- Provide a clear description of the expected behavior.
I expected info on basculin.

**Comment by Naramsim** [comment]
Basculin exists:

https://pokeapi.co/api/v2/pokemon-species/basculin

The pokemon has a different name though: basculin-red-striped https://pokeapi.co/api/v2/pokemon/550/

You also have a second variety: basculin-blue-striped https://pokeapi.co/api/v2/pokemon/10016/

**Comment by phalt** [comment]
There is no "search" in the sense of matching a pattern. Due to the weirdness of Basculin (having two formes) it appears as a different name string. Best to use the hypermedia links in the API to find this, or wrap a mini search function of your own around the all pokemon endpoint.

**Comment by Naramsim** [comment]
The best thing would be to use the `/pokemon-species/` endpoint.
