### ISSUE TITLE
GraphQL implementation

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [PokeAPI/pokeapi#587]
I am willing to try out implementing GraphQL with graphene-django. Does it seem like a good/useful idea?

**Comment by Naramsim** [comment]
We already had a member trying it. https://github.com/cmmartti/pokeapi/tree/graphql

I'm also working on it. So feel free to try something out 😄

**Comment by Naramsim** [comment]
GraphQL was added and it's in beta phase
