### ISSUE TITLE
Location 230 returns 404

### ISSUE THREAD

**Issue by SimplyBLGDev** [PokeAPI/pokeapi#588]
For some reason [Mahogany Town (location 230)](https://pokeapi.co/api/v2/location/230/) is returning 404, although it still appears in the [region location list (Entry 48)](https://pokeapi.co/api/v2/region/2/) and it still is present in the locations CSV table.

The last commit didn't modify this area but it did create a new location-area for it, this location area [is still available](https://pokeapi.co/api/v2/location-area/800/), despite it's location being a 404.

Very strange, maybe the database requires a re-build?

**Comment by Naramsim** [comment]
Nono @SimplyBLGDev, it's because of our Issue with Cloudflare. Randomly they serve 404 instead of 200. For example, on my side, the request works as expected. I'll try to purge the cache.

**Comment by SimplyBLGDev** [comment]
It's working now, weird
