### ISSUE TITLE
404 On Vibrava GET

### ISSUE THREAD

**Issue by mariotee** [PokeAPI/pokeapi#592]
Steps to Reproduce:

1. GET "https://pokeapi.co/api/v2/pokemon/329/" (with trailing slash)
2. 404 is returned

test against https://pokeapi.co/api/v2/pokemon/329 (without trailing slash) and that works fine
test against https://pokeapi.co/api/v2/pokemon/328/ (with trailing slash) and that works fine too

**Comment by Naramsim** [comment]
Yep, It's an issue with Cloudflare. Random. It should fix in less than 24h

**Comment by mariotee** [comment]
sounds good. i guess i can also trim my urls of the trailing slash to be safe. 

thank you!
