### ISSUE TITLE
Eevee is missing female sprite

### ISSUE THREAD

**Issue by LuziferSenpai** [PokeAPI/pokeapi#595]
Hey,

since Lets Go Eevee/Pikachu Eevee posses a female sprite and yes, in SW/SH too.

![Eeevee female](https://www.pokewiki.de/images/thumb/3/39/Pok%C3%A9monsprite_133_Weiblich_HOME.png/192px-Pok%C3%A9monsprite_133_Weiblich_HOME.png)

![Eeevee female shiny](https://www.pokewiki.de/images/thumb/a/a6/Pok%C3%A9monsprite_133_Weiblich_Schillernd_HOME.png/192px-Pok%C3%A9monsprite_133_Weiblich_Schillernd_HOME.png)

These above are the sprites from home.

**Comment by Naramsim** [comment]
Nice, Smogon didn't yet create a gen-5 sprite. So we cannot add it yet. 

We could add HOME sprites. I think veekun got them all.

**Comment by LuziferSenpai** [comment]
Wouldnt it be better to use the home sprite for now? Just scaling it down?

And you can find all the home sprites on pokedex, they got them all.

**Comment by Naramsim** [comment]
We won't replace the art we serve with the HOME one. We serve gen-5 sprites at the root of our `.sprites` property for the `pokemon` endpoint.
