### ISSUE TITLE
pearl, diamond and platin dex - wormadam not correctly added

### ISSUE THREAD

**Issue by LuziferSenpai** [PokeAPI/pokeapi#596]
Hey,

if you go throw the pokemon_entries inside both sinnoh dex, wormadam(46) is named normal, but the api cant get the pokemon with it: [Wormadam](https://pokeapi.co/api/v2/pokemon/wormadam/)

**Comment by Naramsim** [comment]
Same issue as before. You need to search in the pokemon-species.

https://pokeapi.co/api/v2/pokemon-species/wormadam/

**Comment by LuziferSenpai** [comment]
Yea, but for every other pokemon we dont need todo that o.O So, why here? And then I would need todo 3 instead of 2 api calls, why?

**Comment by Naramsim** [comment]
Yep, for every other pokemon, you should do it. All the real pokemon have an entry under `pokemon-species`
