### ISSUE TITLE
pokedex/12 is missing 3 entries

### ISSUE THREAD

**Issue by LuziferSenpai** [PokeAPI/pokeapi#597]
Hey,

pokedex/12 -> pokemon_entries has only 150, but the dex goes up to 153.

Missing is:

151. Diancie
152. Hoopa
153. Volcanion

**Comment by Naramsim** [comment]
I see,

Bulbapedia and pokemondb have those. Serebii doens't. Who do we trust? :smile: Is there an official document from pokemon.com?

**Comment by LuziferSenpai** [comment]
https://www.pokewiki.de/Liste_der_Pok%C3%A9mon_nach_Kalos-Pok%C3%A9dex Has it too.

**Comment by LuziferSenpai** [comment]
Update to this, Bulbapedia and pokewiki probably took the entries from the official strategy guide book.

**Comment by Naramsim** [comment]
So, their info is official.

You can fill in a PR and we'll review it :)

**Comment by LuziferSenpai** [comment]
The problem is, I dont even know how to work with .csv files etc. So yea ...

**Comment by Naramsim** [comment]
@LuziferSenpai I ping you here.

I deployed a custom pokeapi trying to get rid of the `/` problem. Could you try it in your project and see if the problem happens again?

You can use this URL: https://staging.pokeapi.co/api/v2/

**Comment by LuziferSenpai** [comment]
@Naramsim Thanks! After redoing the code a bit and using resource, I was able to catch errors and then when that happens, use the staging side!

**Comment by Naramsim** [comment]
Nono, @LuziferSenpai could you be our tester and only use staging.pokeapi.co for a day or two and do some extensive testing? Trying to trigger the very same errors `/` you encountered in the past?

**Comment by LuziferSenpai** [comment]
@Naramsim It works like a charm! No real errros, other then timeouts!

**Comment by Naramsim** [comment]
Hmm, okok, can you test also tomorrow? 

What do you mean by timeout?

**Comment by LuziferSenpai** [comment]
Just a time expired thing I think. Yea, will test it tomorrow too.

**Comment by LuziferSenpai** [comment]
<img width="439" alt="chrome_h3f77mf65x" src="https://user-images.githubusercontent.com/38015859/112653152-6e0ef780-8e4e-11eb-8aa0-5c7f4364239c.png">

That is what I get, but otherwise it works today too like a charm.

**Comment by Naramsim** [comment]
ok, so you have many timeouts. I need to investigate that. But thanks a lot @LuziferSenpai for your testing!

**Comment by LuziferSenpai** [comment]
@Naramsim Always there to help.

**Comment by Naramsim** [comment]
@LuziferSenpai the timeouts you were experiencing made me think that it's our function that has a timeout of 10s. So maybe in production, it timeouts and a 404 is returned and cached by Cloudflare. 

I increased the timeout from 10s to 30s, in production. I also purged all the cache. For the next day, could you go back to using https://pokeapi.co? And inform me if you encounter any new `\` errors?

**Comment by LuziferSenpai** [comment]
@Naramsim will be done tomorrow ^^

**Comment by LuziferSenpai** [comment]
@Naramsim Sry it took so long.

Here is the test with the normal api.

<img width="442" alt="chrome_SQLIg8OOGO" src="https://user-images.githubusercontent.com/38015859/112867843-abc48800-90bb-11eb-8c28-518b39dbf685.png">

**Comment by Naramsim** [comment]
Hi @LuziferSenpai, can you try using again https://staging.pokeapi.co/api/v2/?

I made some modifications and I believe the issue could be fixed now. Can you please report all the errors you'll encounter? Thanks a lot!

**Comment by LuziferSenpai** [comment]
@Naramsim Still getting a single timeout error, thats all.

**Comment by Naramsim** [comment]
Closing
