### ISSUE TITLE
Pokemon 90 is missing

### ISSUE THREAD

**Issue by gabsschrodinger** [PokeAPI/pokeapi#598]
Steps to Reproduce:

1. Access https://pokeapi.co/api/v2/pokemon/90
2. Output should be shellder json, but it is status of 404

In my local file it is working, but in the vercel app it is not.

**Comment by Kronopt** [comment]
Probably cloudflare related.
I can access it

**Comment by phalt** [comment]
Same here. It's likely a cloudflare global caching issue.
