### ISSUE TITLE
3 urls returning a 404

### ISSUE THREAD

**Issue by KingInktvis** [PokeAPI/pokeapi#599]
The following 3 urls return a 404:
- https://pokeapi.co/api/v2/move/192/
- https://pokeapi.co/api/v2/pokemon/219/
- https://pokeapi.co/api/v2/pokemon/321/

Meanwhile their counterpart without a trailing slash seems to be working normal:
- https://pokeapi.co/api/v2/move/192
- https://pokeapi.co/api/v2/pokemon/219
- https://pokeapi.co/api/v2/pokemon/321

**Comment by Naramsim** [comment]
We are having issues with cloudflare. It should be resolved in 24 hours or so.

**Comment by Lunnen** [comment]
Direct link to pokemon 'Paras' isn't working.
https://pokeapi.co/api/v2/pokemon/paras
