### ISSUE TITLE
It appears that pokemon/105 is down

### ISSUE THREAD

**Issue by joshullman** [PokeAPI/pokeapi#601]
<img width="926" alt="Screen Shot 2021-03-23 at 1 32 31 PM" src="https://user-images.githubusercontent.com/10538498/112200404-30576800-8bdd-11eb-8533-f7a28b030ff4.png">

Steps to Reproduce:

1. Hit https://pokeapi.co/api/v2/pokemon/105
2. Get undfined

**Comment by Kronopt** [comment]
This is a cloudflare cache issue.
We are aware that this has been happening, as people have been reporting it for different pokeapi endpoints.
We don't seem to have a solution for this yet, but the problem usually goes away in a few hours.

**Comment by Rotciv18** [comment]
I'm getting _almost_ the same problem.
I'm trying to pokemon/5, and it returns 404. But when I try to get it from a browser, the api returns the data normally. But both my application and Postman can't get pokemon/5

**Comment by Naramsim** [comment]
Hello,

this issue was resolved by https://github.com/PokeAPI/deploy/pull/23
