### ISSUE TITLE
Missing species 79 data

### ISSUE THREAD

**Issue by omarhoumz** [PokeAPI/pokeapi#607]
### Description
It seems that the species id `79` ​is missing

### Steps to Reproduce:

1. Go to https://pokeapi.co/api/v2/pokemon-species/79/
2. returns a not found 404 error

### Expected behavior
This endpoint https://pokeapi.co/api/v2/pokemon-species/79/ to return species data

**Comment by omarhoumz** [comment]
This could be related https://github.com/PokeAPI/pokeapi/issues/601

**Comment by Naramsim** [comment]
It's related for sure. you just need to wait ~24h

**Comment by Naramsim** [comment]
Hello,

this issue was resolved by https://github.com/PokeAPI/deploy/pull/23
