### ISSUE TITLE
Does the api have stats about the speed of a Pokémon?

### ISSUE THREAD

**Issue by BlackBearFTW** [PokeAPI/pokeapi#608]
I am trying to figure out the speed of a Pokémon, does the api have this data?

**Comment by C-Garza** [comment]
Is this what you're looking for? The `stats` on this endpoint? [Pokemon](https://pokeapi.co/docs/v2#pokemon)

**Comment by BlackBearFTW** [comment]
Well that is embarrassing, I totally looked over that. Thanks for the help @C-Garza, ill close this issue now
