### ISSUE TITLE
Missing 97 data

### ISSUE THREAD

**Issue by alvin-dev** [PokeAPI/pokeapi#609]
Steps to Reproduce:

1. Go to https://pokeapi.co/api/v2/pokemon/97
2. returns a not found

![image](https://user-images.githubusercontent.com/14022991/113525814-6f969900-958d-11eb-8ad1-f2a1cc8f1eec.png)

**Comment by Naramsim** [comment]
Cloudflare, thanks @Kronopt 

@Kronopt maybe you could take a quick look at the PR over at PokeAPI/deploy. Maybe we have a fix for this problem

**Comment by Naramsim** [comment]
Hello,

this issue was resolved by https://github.com/PokeAPI/deploy/pull/23
