### ISSUE TITLE
[Feature request] A way to only get all Pokémon's that aren't duplicates of an original

### ISSUE THREAD

**Issue by BlackBearFTW** [PokeAPI/pokeapi#612]
Hello,

I would like to see a feature that basically allows you to filter the Pokémon results to only have original Pokémon's (and not some special duplicate edition of that Pokémon), currently if we get all Pokémon from [here](https://pokeapi.co/api/v2/pokemon/?limit=1118) it also has a list of cosplay's and other special sprites and stuff. 

For example:
- Pikachu (og)
- Pikachu-rock-star
- Pikachu-belle
- Pikachu-pop-star
- Pikachu-phd
- Pikachu-libre
- Pikachu-cosplau
- Pikachu-original-cap
.... etc

Since they all have the same stats as the original Pikachu, I would like a way to ignore those cosplays (and others with the same stats as the original pokemon) and only get the original Pikachu.

Thank you!
- Bear

**Comment by Naramsim** [comment]
Here you go! https://pokeapi.co/api/v2/pokemon-species/?limit=20000

The answer is to always use the `pokemon-species` endpoint. I think it's better to change the example on our homepage at pokeapi.co to use it.

**Comment by BlackBearFTW** [comment]
@Naramsim Awesome!

I however have an issue with that, if you look at the specific information of a pokemon-species endpoint, it doesn't hold the same information as the normal https://pokeapi.co/api/v2/pokemon/pikachu pokemon endpoint, for example base stats and sprites aren't on the pokemon-species. 

This is an issue in my case, since I am building a pokédex (here)[https://blackbearftw.github.io/React-Pokedex/] (WIP)

I thought I could get around this by getting all the species names from the pokemon-species endpoint and then make a call to pokemon/pikachu pokemon endpoint to get the correct information about those pokemon's.

But for some pokémons you cant use the pokemon/<name> endpoint since they have some suffix, for example mimikyu does exist on the pokemon-species endpoint, but it doesn't exist on the pokemon endpoint (there its mimikyu-disguised).

This means that sometimes the needed information cannot be pulled from the pokemon endpoint

**Comment by Naramsim** [comment]
Yep, this is how pokemon work. You have different forms and varieties, every species has a `default` variety. If you want you can present to your users data about the default variety.

**Comment by Naramsim** [comment]
basically, first, you query the species and then the specific variety. Two HTTP calls

**Comment by BlackBearFTW** [comment]
@Naramsim thank you for helping me, I actually used a different trick, I just extracted the id from the url of each pokemon-species and then used that id to call the pokemon endpoint
