### ISSUE TITLE
Graph QL pagination

### ISSUE THREAD

**Issue by martipello** [PokeAPI/pokeapi#613]
Hi first thank you for the pokeApi what im doing wouldnt be possible without it many thanks, 
I've been looking at the beta graphQL and it looks amazing i really want to use it but i have to have pagination am i right in saying it doesnt currently support this? and assuming i am right ask when/if this might be coming? 
currently i just get a data field so I'd be looking for something like: 
totalDocs, offset, limit, totalPages, page, pagingCounter, hasPrevPage, hasNextPage, prevPage, nextPage

**Comment by Naramsim** [comment]
Hi @martipello, pagination is already present in the form of `offset`s and `limit`s

```graphql
query MyQuery {
  pokemon_v2_pokemonspecies(order_by: {id: asc}, limit: 3, offset: 3) {
    name
  }
}
```

You need to iterate by yourself the `limit` and `offset`. No links are returned. 

Keep in mind also that our entire Graqphql endpoint is but with Hasura. So you can check their docs: https://hasura.io/docs/latest/graphql/core/databases/postgres/queries/pagination.html

**Comment by martipello** [comment]
Ok cool I do use the limit and offset so I need to handle the rest, thanks I'll let you.know how I get on
