### ISSUE TITLE
ARM Builds

### ISSUE THREAD

**Issue by MusicDev33** [PokeAPI/pokeapi#624]
I've been trying to build PokeAPI for Raspberry Pi, and I finally reached the point where I just decided to use Docker Compose, but I realized that the builds on Docker Hub were all Linux amd64, and there were no ARM builds. Are ARM builds planned any time soon?

**Comment by Naramsim** [comment]
Hi, what would be the requirement for building an ARM build?

An ARM base image?

We can try together, I'll start looking into it

**Comment by Naramsim** [comment]
Alright, coming in handy Buildx can build images for various platforms!

I tested initially arm64: https://hub.docker.com/layers/pokeapi/pokeapi/staging/images/sha256-661a50833a0632d857cf5e84273a49f5fa001d89ef5d81700ef3f700cd1ababd?context=explore

@MusicDev33, is that the platform (arm64) you needed?

**Comment by MusicDev33** [comment]
Yep! arm64 is exactly what I needed, and yeah, if you need help with that I can definitely help out!

**Comment by Naramsim** [comment]
Well, then you could try to use that image: `pokeapi/pokeapi:staging` and report back if it works (can migrate, load data and expose the APIs)

**Comment by MusicDev33** [comment]
It works and I didn't need to do any wack workarounds either. Thank you!

**Comment by Naramsim** [comment]
Great, when this PR https://github.com/PokeAPI/pokeapi/pull/623 will be merged in the `master` branch, you will be able to use the image `pokeapi/pokeapi:master`
