### ISSUE TITLE
Missing species data 

### ISSUE THREAD

**Issue by lipecss** [PokeAPI/pokeapi#625]
there are so many new pokemons that we get error if pass endpoint with name for example

Go to https://pokeapi.co/api/v2/pokemon/indeedee
returns a not found

but if pass `https://pokeapi.co/api/v2/pokemon/876` works

**Comment by Kronopt** [comment]
Well, there's an Indeedee species, yes: https://pokeapi.co/api/v2/pokemon-species/indeedee

But, regarding the `pokemon` endpoint, some pokémons have multiple varieties, and varieties usually have their own suffix in PokeAPI.
This is one of those cases:
https://pokeapi.co/api/v2/pokemon/indeedee-male
https://pokeapi.co/api/v2/pokemon/indeedee-female

Take Deoxys as another example:
https://pokeapi.co/api/v2/pokemon/deoxys-speed
https://pokeapi.co/api/v2/pokemon/deoxys-defense

In these cases, you probably want to check the `pokemon-species` endpoint first for existing varieties

**Comment by shovanshahi373** [comment]
In that case, why doesn't these endpoint return a default variety? It used to do it before.

**Comment by Naramsim** [comment]
The `/pokemon/id`  endpoint has the property `is_default: boolean`
