### ISSUE TITLE
certain characteristic (highest IV) endpoints are missing a value

### ISSUE THREAD

**Issue by fissionprime** [PokeAPI/pokeapi#628]
There are 30 characteristics, which correspond to a pokemon's highest IV, the stat that IV is in, and the value of that IV mod 5.
https://bulbapedia.bulbagarden.net/wiki/Characteristic

in pokeAPI, these characteristics are indexed numerically from 1-30.  If a pokemon's highest IV is 31 in any stat, its characteristic will be 7-12, depending on which stat that 31 IV is in. This is the second row on the bulbapedia table.

If we request the endpoint for any characteristic, for example, characteristic 7, "Takes plenty of siestas" at url https://pokeapi.co/api/v2/characteristic/7 . The object the endpoint returns contains a field 'possible_values' with the possible values of that IV. In the case of our example, this field should be [1,6,11,16,21,26,31], however, 31 is missing.

This is not true only for characteristic 7. Each characteristic between 7-12, inclusive, is missing 31 in the 'possible_values' field.

The likely cause seems to be that range(31) may have been used instead of range(32) when either looping through, or checking membership in the range.

**Comment by fissionprime** [comment]
I believe I have located the issue. At line 486 in serializers.py we have the function get_values.

    def get_values(self, obj):

        mod = obj.gene_mod_5
        values = []
        while mod <= 30:
            values.append(mod)
            mod += 5

        return values

Simply changing "while mod <= 30:" to "while mod <=31:" should do the trick.

**Comment by Naramsim** [comment]
Cool, thanks for finding this issue!
