### ISSUE TITLE
some of the endpoints are broken

### ISSUE THREAD

**Issue by shovanshahi373** [PokeAPI/pokeapi#631]
these are some of the endpoints that returns "not found", at least on my machine.

[https://pokeapi.co/api/v2/pokemon/deoxys](https://pokeapi.co/api/v2/pokemon/deoxys)
[https://pokeapi.co/api/v2/pokemon/giratina](https://pokeapi.co/api/v2/pokemon/giratina)
[https://pokeapi.co/api/v2/pokemon/creselia](https://pokeapi.co/api/v2/pokemon/creselia)

**Comment by Kronopt** [comment]
Please refer to this [comment](https://github.com/PokeAPI/pokeapi/issues/625#issuecomment-858161332)
