### ISSUE TITLE
Return pokemon with it species / categories

### ISSUE THREAD

**Issue by Hinaka** [PokeAPI/pokeapi#638]
Hi all.

Please excuse me if this has already been asked before. I tried looking for it but to no avail.

Is there any where to get the pokemon's species / categories? For example, Bulbasaur and Ivysaur are a Seed Pokemon.
Currently the `species` returned from the api provided the same name of that pokemon: Bulbasaur is `bulbasaur`, Ivysaur is `ivysaur`.

**Comment by C-Garza** [comment]
Are you looking for the `genera` property in the species endpoint?
[https://pokeapi.co/api/v2/pokemon-species/bulbasaur](https://pokeapi.co/api/v2/pokemon-species/bulbasaur)

**Comment by Hinaka** [comment]
Wow thank you, it seem like I totally miss this field when looking at the document.
