### ISSUE TITLE
Move "Branch Poke" is missing

### ISSUE THREAD

**Issue by programgames** [PokeAPI/pokeapi#641]
The new move "Branch Poke" is missing in move datas

**Comment by Naramsim** [comment]
Can you open a PR and fill in the move?

**Comment by programgames** [comment]
Well, I started to add it in the moves.csv file, but I saw that it is already present. i think, the graphql console is not up-to-date as i didn't find it in the result https://gyazo.com/5efc0e8bbcc157099addfb001ef0f0e8 , We can close the issue.
