### ISSUE TITLE
official_artwork is currently official-artwork

### ISSUE THREAD

**Issue by OliverHeward** [PokeAPI/pokeapi#644]
Hi - I was working with the API yesterday and noticed the API began to fail on my end of the application.
I noticed that after going back onto pokeapi.co that the response from a pokemon's official artwork sprite has changed from `official_artwork` to `official-artwork` which was causing the error, not sure if this was an intentional change or not but just flagging it :)

**Comment by Naramsim** [comment]
Mm, I did a git blame and the lines governing that property didn't change since 7 months ago.

Are you sure it was `official_artwork`? And how long ago?

**Comment by OliverHeward** [comment]
Yeah, I did take a look to see if there were any releases recently but didn't see any, am 90% sure I was using `official_artwork` and it's the only key within the object that doesn't currently use an underscore at the moment. I noticed it yesterday when I came back to work on my application that the images weren't loading and were causing the app to break.

This was the code I had working before I noticed that it suddenly broke the next day
`pokemon.image = pokemon.sprites.other.official_artwork.front_default;`

**Comment by OliverHeward** [comment]
Although have just realised - I was initially sourcing the API and then applying it into gatsby via node and fetching with GQL so you may be correct with this always being as `official-artwork` 😳

**Comment by Naramsim** [comment]
Nice, ok! Anyway, the naming convention is a little broken on our side as well. We mixed dashes and underscores...

But we cannot standardize it right now.

**Comment by OliverHeward** [comment]
No problem, apologies for the issue opening but thought it best to flag, will create a work around for now :)
