### ISSUE TITLE
Flavored text for #236 Tyrogue

### ISSUE THREAD

**Issue by technicity1** [PokeAPI/pokeapi#646]
The flavored text at index 0 for Tyrogue has the word energy written as "en ergy". Please correct the typo.

Fix: "en ergy" -> "energy"

**Comment by Naramsim** [comment]
Can you submit a Pull Request?

**Comment by technicity1** [comment]
I'm unable to find the typo in pokemon_species_flavor_text.csv.

**Comment by stormonster** [comment]
Should be fixed and merged now in #648. There was a soft hyphen lurking in the middle of the word that was the most likely culprit.

**Comment by technicity1** [comment]
Thank you. It's perfect now
