### ISSUE TITLE
Inclusion of Evolution Chain ID in Pokemon endpoint

### ISSUE THREAD

**Issue by stormonster** [PokeAPI/pokeapi#647]
Currently there does not seem to be any way of distinguishing which evolution chain any given pokémon is part of, making it hard to show show the pokemons relationship to it's other evolutions in for example a web frontend.
Is it possible to add something like evolution_chain_id to the response on the pokemon endpoint?

Thanks

**Comment by Kronopt** [comment]
Hi @stormonster,
You have the `evolution_chain` field on the [pokemon-species](https://pokeapi.co/docs/v2#pokemon-species) endpoint.
Is this not what you want?

**Comment by stormonster** [comment]
Actually, that's exactly what I was looking for but I was hitting the base "pokemon" endpoint rather than "pokemon-species" endpoint.
I missed it in the documentation and can rewrite my application to utilize the pokemon-species endpoint instead (is actually gonna be better).
However, is there a reason the `evolution_chain` field isn't in the base [pokemon](https://pokeapi.co/docs/v2#pokemon) endpoint?

**Comment by Kronopt** [comment]
That I don't know how to answer.
Maybe @Naramsim can?

**Comment by C-Garza** [comment]
I remember coming across an old blog post that talked about the schema that Veekun uses. [(Here is the link)](https://eev.ee/blog/2016/08/05/storing-pok%C3%A9mon-without-sql/#the-current-approach)

They summarize that:
`“Species” is supposed to be the pure essence of the name, so it contains stuff like “is this a baby” or “what does this evolve from/into”. pokemon_forms contains every form imaginable, including all 28 Unown, and tries to loosely categorize them — but it also treats Pokémon without forms as having a single “default” form. And then pokemon contains a somewhat arbitrary subset of forms and tacks other data onto them.`

**Comment by stormonster** [comment]
Wow, thanks that was actually a very interesting read (personally, I think a linked data approach using semantic triplets could've done wonders, but that's a different discussion).
It does indeed seem like the `pokemon` endpoint is an arbitrary subset of data fields that could cover most basic cases, whereas `-species` and `-forms` are more aligned with applications that want more accuracy or data in general.

At this point, my problem of not getting the evo chain has been solved by swapping endpoint, so if y'all wanna close the issue that's more than fine with me, though I still think the question of why it's not included in the base endpoint would be interesting to hear :)

**Comment by Naramsim** [comment]
Thanks a lot, @Kronopt and @C-Garza!
