### ISSUE TITLE
Add extra data to "/pokemon/{id or name}"

### ISSUE THREAD

**Issue by andreas-hub** [PokeAPI/pokeapi#653]
Hello,

I would like to suggest adding gender ratio and pokemon color to the resource of "/pokemon/{id or name}".

Example: 
```json
...
"color": "red",
"gender": {
    "female": 50, //percentage
    "male": 50
}
...
```

The reason I'm suggesting this feature is because at the moment there is no way to get the color and gender ratio of a single pokemon (at least from what I found in the documantion). The only way to do it, is to get all the colors/genders and search for the pokemon in the resources, this way in my opinion is not optimal at all and defies the whole reason for an API.

**Comment by Naramsim** [comment]
Use the `pokemon-species` endpoint. 

https://pokeapi.co/api/v2/pokemon-species/venusaur

**Comment by andreas-hub** [comment]
Oh my bad, I missed this end point. Sorry.
