### ISSUE TITLE
CORS - access-control-allow-origin hardcoded

### ISSUE THREAD

**Issue by patryknawolski** [PokeAPI/pokeapi#654]
Steps to Reproduce:

1. Clone this repository which utilizes graphql pokeapi
2. Install dependencies via `npm install`
3. Run development server via `npm run dev`
4. Error should be visible under Network tab in Chrome Developer Tools

Error preview: https://imgur.com/a/yIqbC8G

**Comment by Naramsim** [comment]
That's not our repository. That's https://github.com/smokku/pokedex

We cannot do anything about it.

**Comment by patryknawolski** [comment]
I know @Naramsim, but this repo utilizes your API, do you have any idea why the request might have that `access-control-allow-origin`?

**Comment by Naramsim** [comment]
Yes

1. we cache responses
2. Hasura has a bug where it sets `access-control-allow-origin` to the `Origin` of the request. https://github.com/hasura/graphql-engine/issues/7566 (Just found out)
2. a request hit PokeAPI
3. it was cached with an `access-control-allow-origin: beta.pokeapi.co`
4. the very same request (same body, same method) was fired on the third-pary website
5. you got the cached response

I added in our Nginx conf another header `add_header Access-Control-Allow-Origin *;` So the latter (`*`) will have precedence and the error should be gone.
