### ISSUE TITLE
How do I get all the records without setting a limit?

### ISSUE THREAD

**Issue by dipanshparmar** [PokeAPI/pokeapi#659]
Hello team,
I am just wondering that how can I get all the records without setting a limit. Because when I call the API without any limit then there is a default limit of 20. So is there any way to get all the records in one request?

> I did ask this on Stackoverflow but got no reply. Here is the thread: https://stackoverflow.com/questions/69504970/how-to-fetch-all-the-pokemos-at-once

I can set a pretty long limit like 10000 but it might not be the best way to do it.

**Comment by galatea21** [comment]
@Kronopt I just realized that `limit=-1` get you all the records except the last one. Like in your example query the result count is 1118 items while the actual results only include items with index 0 to 1116, so 1117 items.
