### ISSUE TITLE
Feature for fuzzy search

### ISSUE THREAD

**Issue by dipanshparmar** [PokeAPI/pokeapi#660]
I think it will be a great idea to implement a fuzzy search. e.g. There are thousands of pokemon's data available, and if I'm fetching only the 20 at a time it will take pretty long to reach the end. Right now we can create a search query that will retrieve the pokemon's details but we need to know the complete name of the pokemon and the correct spelling. But implementing a fuzzy search will help to show pokemon suggestions according to the search query even if it is not spelled correctly or only spelled half yet. It will save a lot of scrolling time and will also enhance the search experience.

Looking forward to hearing opinions on this.

**Comment by Naramsim** [comment]
You can use the Graphql Beta for searching
