### ISSUE TITLE
Pokémon missing

### ISSUE THREAD

**Issue by Henry-Hiles** [PokeAPI/pokeapi#669]
The Pokémon Darmanitan is in the Pokédex Conquest-Gallery, but when I try to make a request to  https://pokeapi.co/api/v2/pokemon/darmanitan I get a 404 (Not Found) error back.

**Comment by Kronopt** [comment]
As Darmanitan has forms, you can't find it by using its standard name.

use
https://pokeapi.co/api/v2/pokemon/555
or
https://pokeapi.co/api/v2/pokemon/darmanitan-standard

**Comment by Naramsim** [comment]
Yeah, also, use the `pokemon-species` endpoint.
