### ISSUE TITLE
GraphQL API seems to be down?

### ISSUE THREAD

**Issue by MiroStW** [PokeAPI/pokeapi#670]
Steps to Reproduce:

opening https://beta.pokeapi.co/graphql/v1beta in the browser returns a 502 bad gateway

OR

trying to query the API with react ApolloClient results in a CORS error: 
```
const pokemonClient = new ApolloClient({
  uri: "https://beta.pokeapi.co/graphql/v1beta",
  cache: new InMemoryCache(),
});
```

```
const TEST_QUERY = gql`
  query MyQuery {
    pokemon_v2_pokemon(where: { id: { _eq: 10 } }) {
      id
      name
    }
  }
`;
```

```
pokemonClient.query({ query: TEST_QUERY }).then((response) => {
  console.log(response.data.name);
});
```

> Access to fetch at 'https://beta.pokeapi.co/graphql/v1beta' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by Naramsim** [comment]
Yep

**Comment by Naramsim** [comment]
I restarted the service, probably some query killed it. Can you keep posting to me if the service is down?

**Comment by MiroStW** [comment]
it's is up again for me - thank you very much!! Being a newbie it took me a while to figure out the problem 😅  - will keep you posted if it happens again

**Comment by Naramsim** [comment]
Yeah, I'm very sorry it crashed. The problem is that the VM is so small and we are really constrained by the small amount to RAM available. We have to use swap and carefully limit container memory otherwise the system becomes unstable. 

If only we could afford half a giga of additional RAM, we wouldn't have these problems.

**Comment by conioX** [comment]
Hi @Naramsim i think grapql host down i got 522 error

![image](https://user-images.githubusercontent.com/73159491/163147860-8dada2cd-b702-4355-b7fe-fbe858bb8bd7.png)

**Comment by Naramsim** [comment]
Yeah, I saw it. I restarted the machine and everything went well

**Comment by conioX** [comment]
Hi @Naramsim, I think there is something error again with graphql  server, i cant open it just the page just loading and timeout

**Comment by pesakitan22** [comment]
Hello @Naramsim the graphql server seems cannot be accessed by localhost origins, other domains works fine though

**Comment by Naramsim** [comment]
Ok, restarted
