### ISSUE TITLE
[feature request] A better way to filter resources

### ISSUE THREAD

**Issue by zurgeg** [PokeAPI/pokeapi#674]
I.e., Bulbapedia has "List of items by Index Number (Generation I)"

The reason I brought this up is because I'm designing an assembler for arbitrary code execution using the glitch item "8F". Since items are the most common way to pull this off, having the ability to do something like `https://pokeapi.co/api/v2/item/42?by=index&gen=1` would be nice!

**Comment by Naramsim** [comment]
Hi, I was about to suggest using GraphQL when I realized we miss data for gen-i, gen-ii, and gen-viii.

For these generations, we cannot list their items.

The GraphQL query would have been:

```gql
query samplePokeAPIquery {
  pokemon_v2_generation {
    name
    pokemon_v2_itemgameindices {
      pokemon_v2_item {
        name
      }
    }
  }
}
```

https://beta.pokeapi.co/graphql/console/

**Comment by zurgeg** [comment]
> Hi, I was about to suggest using GraphQL when I realized we miss data for gen-i, gen-ii, and gen-viii.
> 
> For these generations, we cannot list their items.
> 
> The GraphQL query would have been:
> 
> ```graphql
> query samplePokeAPIquery {
>   pokemon_v2_generation {
>     name
>     pokemon_v2_itemgameindices {
>       pokemon_v2_item {
>         name
>       }
>     }
>   }
> }
> ```
> 
> https://beta.pokeapi.co/graphql/console/

Ah okay. by "can not", do you mean your current system for ripping item info is unable to rip data from gen-i, gen-ii, and gen-viii, or do you mean PokeAPI currently does not?

**Comment by Naramsim** [comment]
Pokeapi currenty doesn't have the necessary data. One could fill/scrape it, but as of now we don't have it

**Comment by zurgeg** [comment]
Ah, okay. I'd be glad to help fill it manually, since I need to fill the data in my program anyways :P

**Comment by Naramsim** [comment]
perfect, then you should update the file https://github.com/PokeAPI/pokeapi/blob/master/data/v2/csv/item_game_indices.csv

The task is a bit more difficult than marking whether an item is in a generation. Here actually we need to know the specific index or the item for that generation.
