### ISSUE TITLE
Wrong data type for field Move.learned_by_pokemon in the docs

### ISSUE THREAD

**Issue by galatea21** [PokeAPI/pokeapi#684]
It should be a List of NamedAPIResource as it is described "List of Pokemon that can learn the move" but the docs lists it as a NamedAPIResource instead.

**Comment by oliiiiiiiiiiiii** [comment]
![image](https://user-images.githubusercontent.com/74825334/149701560-39872050-f317-465f-a061-620f37d2c1b5.png)
pls fix this at the earliest
