### ISSUE TITLE
EvolutionChain endpoint return invalid resource references

### ISSUE THREAD

**Issue by galatea21** [PokeAPI/pokeapi#686]
Result for https://pokeapi.co/api/v2/evolution-chain?limit=2&offset=466:

![1](https://user-images.githubusercontent.com/75539244/150710167-d7448cab-b6dc-4c35-9d25-afebd6fdab86.png)

Result for https://pokeapi.co/api/v2/evolution-chain/476:

![2](https://user-images.githubusercontent.com/75539244/150710187-bc85bd93-c772-478a-adbc-d34dcb7552fe.png)

**Comment by C-Garza** [comment]
Yes, this is an issue because we're currently syncing up our data with Veekun upstream. It should be resolved when we eventually sync up the `pokemon_species.csv` file.

**Comment by Naramsim** [comment]
Is it fixed now @galatea21?

**Comment by galatea21** [comment]
@Naramsim Yes it is. Thank you for notifying me.
