### ISSUE TITLE
Effect_entries has $effect_chance% which does not return a number

### ISSUE THREAD

**Issue by thibaudbrault** [PokeAPI/pokeapi#687]
Inside the effect_entries of the move endpoint has $effect_chance% in the text (for example the move "blizzard") which does not return the number defined at effet_chance but return "$effect_entries". There is also a problem with the "(100 - accuracy)%" inside the text which also does not return a number. I think that there should be a space before "%".

**Comment by C-Garza** [comment]
The `$effect_chance%` is supposed to be replaced with whatever value is in the `effect_chance` property for the `move` endpoint. Different moves have different chances, so it's left as a placeholder to be replaced with.

Ex: Blizzard's `effect_chance` is 10: [Blizzard move endpoint](https://pokeapi.co/api/v2/move/59)

As for the `(100 - accuracy)` inside of the `effect-entries` for blizzard, I'm actually not sure about that. Looking into it, it seems like it had around a 30% chance to break through protect but only in Diamond/Pearl?

Oh, I found this on bulbapedia. It's an equation, it's base 100 minus the move accuracy.
[Protection bypass glitch](https://bulbapedia.bulbagarden.net/wiki/List_of_glitches_(Generation_IV)#Protection_bypass_glitch)

**Comment by thibaudbrault** [comment]
So I have to assign $effect_chance% to move.effect_chance ?  
I know that it's an equation but the problem is that it does not display the results but it displays "(100 - accuracy)"

**Comment by C-Garza** [comment]
Yeah exactly. Veekun, where the pokemon data is pulled upstream, has to do the same thing. They describe their way here: [Parsing effect chance](https://github.com/veekun/pokedex/issues/272).

As for the accuracy one, the `move` endpoint has an `accuracy` property as well, so you can use that in the equation to get the correct result.
Ex: Blizzard has an accuracy of 70, so (`100 - 70)` comes out to 30.

**Comment by thibaudbrault** [comment]
So I need to do a replace function ?

**Comment by C-Garza** [comment]
Yes, you need to replace `$effect_chance` and `(100 - accuracy)` with the correct values for that move. A regular expression comes to mind if you want to replace multiple things at once.

**Comment by thibaudbrault** [comment]
But I want to do that for every move so is it possible to replace this text with "move.effect_chance" and "move.accuracy" ?

**Comment by C-Garza** [comment]
You could perhaps write a function that could check if that text, `$effect_chance`, is in the string, and then replace it with the correct value.

**Comment by thibaudbrault** [comment]
I think I'll do that. Thx for the answer
