### ISSUE TITLE
Sprite for Galarian Moltres is the one for Galarion Zigzagoon

### ISSUE THREAD

**Issue by thibaudbrault** [PokeAPI/pokeapi#688]
What is said in the title the sprites for galarian moltres are the ones for galarian zigzagoon

**Comment by Naramsim** [comment]
Ugh, thanks for the info. 

Would you be able to propose a fix?

**Comment by thibaudbrault** [comment]
I would gladly help but I don't know how to fix that and I don't know Python.

**Comment by Naramsim** [comment]
Argh!!!!

All the galar varieties mismatch!

We have a problem. I think I'll revert to a previous version. Let's keep analyzing on the staging version

**Comment by Naramsim** [comment]
So last PR (https://github.com/PokeAPI/pokedex/pull/86) messed up some IDs, I think the ones above 10000. But I didn't fully analyze the issue

**Comment by thibaudbrault** [comment]
Ok
What did it do ?

**Comment by C-Garza** [comment]
Right, we shifted the galarian id's but we didn't rename the sprite images since it's tied with their id.

In the `pokemon.csv`, everything above `10158` got renamed, and in the `pokemon_forms.csv`, everything above `10317` got renamed.

**Comment by thibaudbrault** [comment]
So in pokemon_forms.csv everything between 10158 and 10317 needs to be renamed ?

**Comment by C-Garza** [comment]
Yeah, this should be a one time thing since we're syncing up with veekun. I'll try to rename the existing sprites to the new id's with a script and make a PR.

**Comment by thibaudbrault** [comment]
Ok
Great
Thx for the answers

**Comment by Naramsim** [comment]
Ok, it seems to work, can you confirm @thibaudbrault ?

huge thanks to @C-Garza

**Comment by thibaudbrault** [comment]
Right now I can't but I'll look tomorrow
