### ISSUE TITLE
Name search doesn't work on mobile devices

### ISSUE THREAD

**Issue by Brandon-B91** [PokeAPI/pokeapi#689]
search by name or Id works fine on web browser tested on both safari and chrome. When accessing on mobile device (iphone. 11) browser used was safari and chrome. the search will not return based on name but will return values based on id#

**Comment by Naramsim** [comment]
Hmm, I tried on an Android device and on an iPhone 12 and it works fine. 

The CSS has to be rewritten but the functionality works. And for the CSS we already have a PR that fixes the formatting

**Comment by Naramsim** [comment]
Pull Request. Anyways, I don't see the issue you are talking about. 

Could you maybe provide a screenshot?

**Comment by Brandon-B91** [comment]
Oh right, hahah it was early when I read that. A screen shot wont really do any justice here but here is the app. 
https://pokemoncardapi.netlify.app/ if you access this from laptop or desktop it works fine you can enter pokemon name or corresponding ID it works. However access it from a mobile device in my case iphone 11 entering a pokemon name does nothing example mew. if you enter his corresponding ID 151 it does work.

**Comment by Naramsim** [comment]
Hey @Brandon-B91, we don't make that app. Is it yours? We cannot provide support for something we didn't make.
