### ISSUE TITLE
What is the admin secret for Hasura?

### ISSUE THREAD

**Issue by 684efs3** [PokeAPI/pokeapi#690]
I followed the instructions for Docker and Compose, and GraphQL. Everything looks like it is working, but when I go to http://localhost:8080/, I get a request for the 'admin-secret.' What should I enter?

Thank you!

![image](https://user-images.githubusercontent.com/48864759/154283289-63346ecd-d7e1-4b91-b292-5d84c018aa0b.png)

**Comment by Naramsim** [comment]
If still needed:

https://github.com/PokeAPI/pokeapi/blob/b80e8f411b1eabe8553b918f99ca56130c0fbb9e/docker-compose.yml#L59

https://github.com/PokeAPI/pokeapi/blob/b80e8f411b1eabe8553b918f99ca56130c0fbb9e/Resources/k8s/kustomize/base/secrets/graphql.env.sample#L1

It defaults to `pokemon` if on Docker Compose or `pokeapi-change-me` if on Kubernetes

**Comment by alburdette619** [comment]
changed to `pokemon` it seems
