### ISSUE TITLE
Missing data for Pikachu-World-Cap, Pikachu-Starter and Eevee-Starter

### ISSUE THREAD

**Issue by supermii2** [PokeAPI/pokeapi#691]
https://github.com/veekun/pokedex/blob/master/pokedex/data/csv/pokemon_forms.csv

Just as the title describes.

10317, 10318 and 10319 in the above link.

**Comment by Naramsim** [comment]
I see them

**Comment by Naramsim** [comment]
Oh, you linked Veekun. haha, my bad. I guess we have them added recently -> https://github.com/PokeAPI/pokedex/blob/master-pokeapi/pokedex/data/csv/pokemon_forms.csv

**Comment by Deleca7755** [comment]
@Naramsim resolved/stale Issue?
