### ISSUE TITLE
EvolutionChain

### ISSUE THREAD

**Issue by Bindamen** [PokeAPI/pokeapi#692]
Steps to Reproduce:

1.find grookey Pokémon id 810
2.call Pokémon-species/810 endpoint
3.call evolution chain endpoint
4.we retrieve wrong evolution chain id -1 so here Melmetal

**Comment by C-Garza** [comment]
The evolution chain on the endpoint [`/pokemon-species/810`](https://pokeapi.co/api/v2/pokemon-species/810) leads to the correct evolution chain for me. Perhaps you could post a screenshot?

**Comment by Bindamen** [comment]
Sure My bad sorry
I made a mistake

Thanks
