### ISSUE TITLE
Venusaur Gmax Missing Stats

### ISSUE THREAD

**Issue by TurtIeSocks** [PokeAPI/pokeapi#697]
Steps to Reproduce:

1. https://pokeapi.co/api/v2/pokemon/venusaur-gmax/
2. Scroll to stats section

They used to be there but are currently missing. I tried to dig around in the data CSVs to see if I could find where they're missing from and PR it but I was unsuccessful. Thanks for the help!

**Comment by C-Garza** [comment]
You're right! It seems when we shifted the new pokemon id's, we didn't shift the first 3 stats for pokemon id `10195`, as seen in the [`pokemon_stats.csv`](https://github.com/PokeAPI/pokeapi/blob/master/data/v2/csv/pokemon_stats.csv#L6554) file, row 6554.

The first three should be:
```
10195,1,80,0
10195,2,82,0
10195,3,83,0
```
I probably won't get around to it until tomorrow if someone else wants to quickly patch that up.
