### ISSUE TITLE
?limit=-1 does not show all moves

### ISSUE THREAD

**Issue by thatsalltheyare** [PokeAPI/pokeapi#705]
When I use [https://pokeapi.co/api/v2/move/?limit=-1](https://pokeapi.co/api/v2/move/?limit=-1) the last move that is listed is [https://pokeapi.co/api/v2/move/10017/](https://pokeapi.co/api/v2/move/10017/). But when I use [https://pokeapi.co/api/v2/move/?offset=840&limit=20](https://pokeapi.co/api/v2/move/?offset=840&limit=20), the last move is [https://pokeapi.co/api/v2/move/10018/](https://pokeapi.co/api/v2/move/10018/). I have a feeling that this is happening to all API calls that support `?limit=-1` to be honest.

**Comment by Naramsim** [comment]
Hi, we are aware of this and this is the expected behavior.
