### ISSUE TITLE
Pokemon 10150 and 10105 wrong shiny image

### ISSUE THREAD

**Issue by LaufenderBaum** [PokeAPI/pokeapi#722]
Description: 
The Pokemon with the ID 10105 (diglett-alola) is missing the url under `sprites.other.home.front_shiny`.
Missing image can instead be found on Pokemon 10150 (ribombee-totem), again under `sprites.other.home.front_shiny`.

(Note: ribombee-totem has an overall lack of images compared to the others, not sure if they aren't available or if there was perhaps a mistake)

Steps to Reproduce:
1. Follow the link [https://pokeapi.co/api/v2/pokemon/10150](url)
2. Check `sprites.other.home.front_shiny` and follow the link [https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/shiny/10150.png](url)
3. Be faced with Shiny Alola Diglett

4. Go to Alola Diglett's url [https://pokeapi.co/api/v2/pokemon/10105/](url)
5. Navigate to `sprites.other.home.front_shiny`
6. Notice the lack of an url

Big fan of the API, I am having a blast using it to learn Angular. Props!

Images (in the hopes they make things a bit easier):
![grafik](https://user-images.githubusercontent.com/75691320/170794424-7134b146-be45-4ad9-8565-6f1286039883.png)
![grafik](https://user-images.githubusercontent.com/75691320/170794561-ba69910f-98c5-4c58-b4ba-97fd41bfc70c.png)

**Comment by C-Garza** [comment]
This looks resolved, although now ribombee-totem (https://pokeapi.co/api/v2/pokemon/10150) has a `home` front shiny sprite that returns a 404.
https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/shiny/10150.png
