### ISSUE TITLE
Missing Array length

### ISSUE THREAD

**Issue by bidery** [PokeAPI/pokeapi#733]
Hey,

I worked in C# with this API and it was verry cool. But i missed something.

It would be realy nice to have a field, wich shows the length of the following Array. 

For example like this:

```
"types_length": 2,
 "types": [
    {
      "slot": 1,
      "type": {
        "name": "grass",
        "url": "https://pokeapi.co/api/v2/type/12/"
      }
    },
    {
      "slot": 2,
      "type": {
        "name": "poison",
        "url": "https://pokeapi.co/api/v2/type/4/"
      }
    }
  ]
```

**Comment by diekmrcoin** [comment]
Ey @bidery i suppose that you figured it out by now but you can know the lenght of an array in your favourite language.  
> [Array Size (Length) in C#](https://stackoverflow.com/questions/2843987/array-size-length-in-c-sharp)

**Comment by bidery** [comment]
yes I noticed, but thank you
