### ISSUE TITLE
Route 13 Crystal walk encounters missing time restriction

### ISSUE THREAD

**Issue by Eiim** [PokeAPI/pokeapi#735]
I was pulling Crystal encounter data and noticed that [Pidgeotto](https://pokeapi.co/api/v2/pokemon/pidgeotto/encounters) had one encounter location which strangely wasn't time-restricted like its other encounter locations, Kanto Route 13. [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Kanto_Route_13#Generation_II) said this encounter was restricted to morning and day, like its other encounters, so I decided to test in-game.

I loaded the VC edition of Crystal (to my knowledge, the only difference between GBC Crystal and VC Crystal with regards to encounters is the ability to obtain the [GS Ball](https://bulbapedia.bulbagarden.net/wiki/GS_Ball) without an event) and did 30 encounters at night, without encountering a single Pidgeotto. At the given 20% spawn rate, there would be approximately a 0.1% chance of not getting a Pidgeotto. Then, I repeated in the morning and day, getting a Pidgeotto on the third and second encounters respectively, consistent with the given encounter rate.

Notably, the JSON has two identical `encounter_details` objects for this encounter, each of which appears to simply be missing an object in `condition_values`. Compare the (likely correct) Silver entry to the Crystal entry:

```
{
  "encounter_details": [
    {
      "chance": 20,
      "condition_values": [
        {
          "name": "time-day",
          "url": "https://pokeapi.co/api/v2/encounter-condition-value/4/"
        }
      ],
      "max_level": 25,
      "method": {
        "name": "walk",
        "url": "https://pokeapi.co/api/v2/encounter-method/1/"
      },
      "min_level": 25
    },
    {
      "chance": 20,
      "condition_values": [
        {
          "name": "time-morning",
          "url": "https://pokeapi.co/api/v2/encounter-condition-value/3/"
        }
      ],
      "max_level": 25,
      "method": {
        "name": "walk",
        "url": "https://pokeapi.co/api/v2/encounter-method/1/"
      },
      "min_level": 25
    }
  ],
  "max_chance": 40,
  "version": {
    "name": "silver",
    "url": "https://pokeapi.co/api/v2/version/5/"
  }
}
```
```
{
  "encounter_details": [
    {
      "chance": 20,
      "condition_values": [],
      "max_level": 25,
      "method": {
        "name": "walk",
        "url": "https://pokeapi.co/api/v2/encounter-method/1/"
      },
      "min_level": 25
    },
    {
      "chance": 20,
      "condition_values": [],
      "max_level": 25,
      "method": {
        "name": "walk",
        "url": "https://pokeapi.co/api/v2/encounter-method/1/"
      },
      "min_level": 25
    }
  ],
  "max_chance": 40,
  "version": {
    "name": "crystal",
    "url": "https://pokeapi.co/api/v2/version/6/"
  }
}
```

**Comment by SimplyBLGDev** [comment]
This issue can be closed now
