### ISSUE TITLE
Incorrect sprite URLs

### ISSUE THREAD

**Issue by marko-knoebl** [PokeAPI/pokeapi#736]
If I access

https://pokeapi.co/api/v2/pokemon/1

the value of `sprites.front_default` is:

`https://raw.githubusercontent.com/PokeAPI/sprites/master/https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png`

- which is not a valid image URL - a correct value would be:

`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png`

Looking at some code examples / demos that are using this API, they are all not showing images anymore at the moment

A couple of hours ago, images were still working for me

**Comment by mertthesamael** [comment]
Same here, i thought my code just blown up

**Comment by igordeoliveira95** [comment]
The moment I deployed my personal project this occurs haha, waiting for fixes.

**Comment by Naramsim** [comment]
Hi all, I'm really sorry for the problem. I rolledback and purge the Cloudflare cache. Thanks for raising the issue

**Comment by marko-knoebl** [comment]
Thanks for the quick fix! Everything seems to be working again from my POV

**Comment by Naramsim** [comment]
Hi, this isn't a fix, just a roll back. This is the PR (https://github.com/PokeAPI/pokeapi/pull/727) that broke the sprites. 

I think we add the duplicated `https://raw.githubusercontent.com/PokeAPI/sprites/master/` not in the build phase, but in Ditto or something. I'll investigate next Monday.

**Comment by C-Garza** [comment]
Was this issue resolved in #745 @Naramsim?

**Comment by jayk-gupta** [comment]
> If I access
> 
> https://pokeapi.co/api/v2/pokemon/1
> 
> the value of `sprites.front_default` is:
> 
> `https://raw.githubusercontent.com/PokeAPI/sprites/master/https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png`
> 
> * which is not a valid image URL - a correct value would be:
> 
> `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png`
> 
> Looking at some code examples / demos that are using this API, they are all not showing images anymore at the moment
> 
> A couple of hours ago, images were still working for me

Not working

**Comment by Naramsim** [comment]
Not true, I get https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/1.png which is valid
