### ISSUE TITLE
GraphQL does not support GET requests

### ISSUE THREAD

**Issue by theninthsky** [PokeAPI/pokeapi#740]
Hi.

It seems that the GraphQL endpoint returns error for all GET requests.

Steps to Reproduce:

1. Open Postman or a web browser.
2. Send the following GET request: 
https://beta.pokeapi.co/graphql/v1beta?query={pokemon_v2_pokemon{name}}

The following data is returned:

{
    "path": "$",
    "error": "resource does not exist",
    "code": "not-found"
}

**Comment by Naramsim** [comment]
Yep, we only support POST

**Comment by phalt** [comment]
Have a read on how GraphQL is implemented, this is part of the way HTTP works! You cannot (officially) send a POST body in a GET request.

**Comment by theninthsky** [comment]
> Have a read on how GraphQL is implemented, this is part of the way HTTP works! You cannot (officially) send a POST body in a GET request.

GraphQL fully supports GET requests.

"This request could be sent via an HTTP GET like so:"

`http://myapi/graphql?query={me{name}}`

Source: https://graphql.org/learn/serving-over-http

I ended up using an another API which supports GET requests:
https://graphql-pokeapi.vercel.app
