### ISSUE TITLE
Docker container doesn't build the database for image paths?

### ISSUE THREAD

**Issue by sunny7dusk** [PokeAPI/pokeapi#744]
I tried running my own instance of PokeApi, but the container does not return any `raw.githubusercontent.com` paths
![image](https://user-images.githubusercontent.com/71191616/183527909-7f391610-96e2-43d8-9732-bf8a4a361534.png)

Steps to reproduce:
1. Clone the project
2. Run `make docker-setup `

**Comment by Naramsim** [comment]
Hi, you need to clone the submodules as well

**Comment by sunny7dusk** [comment]
Ohh, I missed that part in the documentation, sorry about that. Thank you for helping!
