### ISSUE TITLE
No Evolution-Chain endpoint for Pokemon 899-905 (Hisuian Pokemon)

### ISSUE THREAD

**Issue by 12velos12** [PokeAPI/pokeapi#747]
Not sure if this is intentionally blank because legends arceus is weird or known and hasn't been done yet. Pokemon 899-905 each have their own page under the pokemon and pokemon-species endpoints but don't have a evolution-chain endpoint.

**Comment by huyta55** [comment]
Where can I find the pokemon and pokemon-species endpoints?

**Comment by C-Garza** [comment]
Looks like this was resolved in PR #763.
@huyta55 Those endpoints are at `https://pokeapi.co/api/v2/pokemon/{id or name}/` and `https://pokeapi.co/api/v2/pokemon-species/{id or name}/` respectively. You can find them on the [pokeapi docs](https://pokeapi.co/docs/v2)

**Comment by Naramsim** [comment]
THanks, @C-Garza !
