### ISSUE TITLE
The move effect data for Scale Shot is incorrect

### ISSUE THREAD

**Issue by AshFrancisDev** [PokeAPI/pokeapi#749]
Scale Shot's effect entry in English simply reads that it "Inflicts regular damage with no additional effect.", which is incomplete and incorrect. The attack deals regular damage two to five times, raising speed but lowering its defense stat if the attack is successful. This is referenced in the flavor text entry, but not in the effect entry, which is typically the more complete and detailed entry. 

For comparison, Close Combat, which has a similar ability to deal damage, but at the detriment of lowering the user's stat, displays this information in the effect entry.

Steps to Reproduce:

1. https://pokeapi.co/api/v2/move/799/ - Scale Shot
2. https://pokeapi.co/api/v2/move/370/ - Close Combat

**Comment by Naramsim** [comment]
Hi, could you open a PR fixing the issue? Maybe you can take the text from Bulbapedia

**Comment by norman-codes** [comment]
Hi! I'll open a PR fixing this issue soon, within the next few days at the latest. 👍

**Comment by norman-codes** [comment]
Here is a side-by-side comparison of the effect text before (LEFT) and after (RIGHT) the changes.

![749_sidebyside](https://user-images.githubusercontent.com/78187320/193343307-0afec7dc-35fe-44af-a2e3-85ecae8771e1.png)

**Comment by C-Garza** [comment]
Looks like this got fixed in #758, but the API is still showing the old value?
[https://pokeapi.co/api/v2/move/scale-shot](https://pokeapi.co/api/v2/move/scale-shot)

**Comment by Deleca7755** [comment]
@Naramsim resolved/stale Issue
