### ISSUE TITLE
Meltan and Melmetal shape is None

### ISSUE THREAD

**Issue by PatrunoLuca** [PokeAPI/pokeapi#762]

**Comment by DevMike123** [comment]
Can you please specify the problem in detail:)

**Comment by PatrunoLuca** [comment]
If you go to https://pokeapi.co/api/v2/pokemon-species/808 and
https://pokeapi.co/api/v2/pokemon-species/809 the shape value is null.
Meltan shape should be shape 01 and Melmetal shape should be shape 12

Il giorno sab 19 nov 2022 alle ore 15:49 Aniket Bhattacharjee <
***@***.***> ha scritto:
