### ISSUE TITLE
Basculegion Male and Female Official Art Urls are Swapped

### ISSUE THREAD

**Issue by joseph-bayer** [PokeAPI/pokeapi#764]
## Description
The official art in the API response for female Basculegion is for male Basculegion and vice versa.

## Steps to Reproduce:

1. Check the url provided in sprites.other.official-artwork.front_default from [this API response](https://pokeapi.co/api/v2/pokemon/basculegion-male) for male Basculegion
2. Verify that the url provided links to an image of Female Basculegion
3.  Check the url provided in sprites.other.official-artwork.front_default from [this API response](https://pokeapi.co/api/v2/pokemon/basculegion-female) for female Basculegion
4. Verify that the url provided links to an image of Male Basculegion

## Expected Behavior
Male Basculegion's official art should link to an image of Male Basculegion and Female Basculegion's official art should link to an image of Female Basculegion.

I'm not sure where this change would be made, but if someone could point me in the general direction, I can make a pull request.

**Comment by C-Garza** [comment]
Hello! The sprites live in this repo here! Changing the image file names should resolve this issue if you'd like to make the PR.
https://github.com/PokeAPI/sprites

**Comment by joseph-bayer** [comment]
Thanks for pointing me in the right direction!
I just opened a pull request here: https://github.com/PokeAPI/sprites/pull/91
