### ISSUE TITLE
https://beta.pokeapi.co/graphql/v1beta Offline

### ISSUE THREAD

**Issue by itechKaitoQueiroz** [PokeAPI/pokeapi#772]
Steps to Reproduce:

1. Go to https://beta.pokeapi.co/graphql/console/
2. Excecute query

**Comment by ebailin** [comment]
I had the same problem. I'd really like to get the console back. I've been struggling to get the docker set up, so it's all I've got.

**Comment by bobs619** [comment]
down for me as well

**Comment by c5inco** [comment]
Yes down for me as well

**Comment by martipello** [comment]
Can you point to the duplicate please

**Comment by Naramsim** [comment]
https://github.com/PokeAPI/pokeapi/discussions/776#discussioncomment-4290805

**Comment by Naramsim** [comment]
It's fixed now

**Comment by enumag** [comment]
> It's fixed now

@Naramsim No it isn't. For instance I need a list of mons with their types so I have a simple query like this:

```
query {
  pokemon_v2_pokemon(limit: 10) {
    name
    pokemon_v2_pokemonforms {
      name
      pokemon_v2_pokemonformtypes {
        pokemon_v2_type {
          name
        }
      }
    }
  }
}
```

The API returns error 504: Gateway time-out.

**Comment by martipello** [comment]
I've been using it this morning and it was running fine until it suddenly wasn't around 20 minutes ago, I think I may have broken it using the console 🤔

**Comment by Naramsim** [comment]
So it's you @martipello ?

sometimes we get queries that kill us! Can you paste it here?
\

**Comment by martipello** [comment]
😂 I think it's been me twice but yes I will

**Comment by itechKaitoQueiroz** [comment]
I get an error on the following:
```
query samplePokeAPIquery {
  species: pokemon_v2_pokemonspecies(limit: 24, offset: 24, order_by: {id: asc}, where: {
      name: {_like: "%%"},
      pokemon_v2_pokemons: {is_default: { _eq: true }, pokemon_v2_pokemontypes: {pokemon_v2_type: {name: {_regex: ""}}}}
    }) {
      id
      pokemon: pokemon_v2_pokemons(limit: 1) {
        types: pokemon_v2_pokemontypes {
          type: pokemon_v2_type {
            name
          }
        }
      }
      names: pokemon_v2_pokemonspeciesnames(where: {language_id: {_eq: 9}}) {
        name
      }
    }
    total: pokemon_v2_pokemonspecies_aggregate(where: {
      name: {_like: "%%" },
      pokemon_v2_pokemons: {is_default: { _eq: true }, pokemon_v2_pokemontypes: {pokemon_v2_type: {name: {_regex: ""}}}}
    }) {
      aggregate {
        count
      }
    }
}
```

Though, if I change `offset: 0` it works fine.

**Comment by martipello** [comment]
the query i think killed it is below, hope it helps 

`query MyQuery {
  pokemon_v2_pokemon(where: {id: {_eq: 1}}) {
    id
    pokemon_v2_pokemonmoves(distinct_on: id) {
      id
      level
      pokemon_v2_move {
        accuracy
        move_effect_chance
        name
        priority
        pp
        power
        super_contest_effect_id
        type_id
        pokemon_v2_type {
          name
          pokemon_v2_movedamageclass {
            pokemon_v2_movedamageclassdescriptions(where: {language_id: {_eq: 9}}) {
              pokemon_v2_movedamageclass {
                name
                id
              }
            }
          }
          id
        }
        pokemon_v2_movemetum {
          crit_rate
          ailment_chance
          flinch_chance
          drain
          max_hits
          max_turns
          min_hits
          min_turns
          stat_chance
          pokemon_v2_movemetaailment {
            name
          }
          pokemon_v2_movemetacategory {
            name
          }
        }
        id
      }
      pokemon_v2_movelearnmethod {
        name
        pokemon_v2_versiongroupmovelearnmethods {
          pokemon_v2_versiongroup {
            name
          }
        }
        pokemon_v2_movelearnmethoddescriptions(where: {language_id: {_eq: 9}}) {
          description
          pokemon_v2_movelearnmethod {
            name
            pokemon_v2_movelearnmethoddescriptions(where: {language_id: {_eq: 9}}) {
              description
              id
              move_learn_method_id
            }
          }
        }
      }
    }
  }
  pokemon_v2_move {
    id
  }
}
`

**Comment by martipello** [comment]
i think it was working before i added the pokemon_v2_versiongroupmovelearnmethods

**Comment by Naramsim** [comment]
@martipello , try not to run it anymore :)

**Comment by martipello** [comment]
That makes perfect sense, i will add limits and if i break it again its your fault 😂

**Comment by c5inco** [comment]
Seems the GraphQL endpoint is down again - I'm getting a 522 :(
