### ISSUE TITLE
CORS error using apollo client from react

### ISSUE THREAD

**Issue by vikramdewangan** [PokeAPI/pokeapi#777]
### Discussed in https://github.com/PokeAPI/pokeapi/discussions/776

<div type='discussions-op-text'>

<sup>Originally posted by **vikramdewangan** November 27, 2022</sup>
The service is blocked by CORS when accessed through @apollo/client with graphql packages from react localhost:3000. 
The same setup works with [https://graphql.anilist.co/](https://graphql.anilist.co/)
The problem is if **mode: "no-cors"** is passed the fetch payload won't be sent as application/json and rather would be sent as text/plain which gives 502.

Please add a CORS policy for Access-Control-Allow-Origin: *

CC: @phalt </div>

**Comment by martipello** [comment]
possibly also relates to https://github.com/PokeAPI/pokeapi/issues/774

**Comment by martipello** [comment]
Still broken
