### ISSUE TITLE
Data merged 3 weeks ago disappeared

### ISSUE THREAD

**Issue by mlemesle** [PokeAPI/pokeapi#789]
Hello there !

I submitted a PR 3 weeks ago, it has been merged but the data aren't available on pokeapi.co nor staging.pokeapi.co.

Can you please check this and make the data available please ?
The PR I'm talking about https://github.com/PokeAPI/pokeapi/pull/765

Thanks, I stay available if you need !

**Comment by mlemesle** [comment]
Hey @Naramsim !
A little up of this issue. You said on Slack that you were looking into it. Did you find anything ?
This is kinda weird because the issue isn't on newly merged PR ?

**Comment by Naramsim** [comment]
Hi, didn't have time! Just got back from Japan 2 weeks ago, these days I reviewed/pulled in gen9 data and fixed the delivery pipeline.

**Comment by Naramsim** [comment]
Can you investigate? If not, can you resubmit the PR?

**Comment by mlemesle** [comment]
Hey! No worries, I'll take a look this afternoon!
What's strange is that the data is in the CSV, but not present in the API.

I'll keep you updated!

**Comment by Naramsim** [comment]
ok, even now? Our pipeline got broken since CircleCI got hacked and they invalidated all our tokens. Yesterday I fixed the pipeline and deployed in prod. Maybe you see some changes

**Comment by mlemesle** [comment]
It seems to be available now!
Thanks!!
