### ISSUE TITLE
Broken Slack invite link

### ISSUE THREAD

**Issue by p16r** [PokeAPI/pokeapi#790]
The invitation link to Slack (https://pokeapi-slack-invite.herokuapp.com) is broken both on https://pokeapi.co/docs/v2#slack as well as on the New Issue choices screen on GitHub.

**Comment by Naramsim** [comment]
Ok, this new one should work: https://join.slack.com/t/pokeapi/shared_invite/zt-1l4vpwa8k-muQmMrFfv7TIFGrVWzjzcw

Can you test?

**Comment by p16r** [comment]
Yup, this worked. Thanks a lot!
