### ISSUE TITLE
Syntax error thrown when 

### ISSUE THREAD

**Issue by martipello** [PokeAPI/pokeapi#792]
GraphQL console throws SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON for a query that includes distinct and order by fields.
The actual error thrown is - Error : "distinct_on" columns must match initial "order_by" columns.

Steps to Reproduce:

1. create a query that includes distinct and order by fields such as the below query
2. query MyQuery {
  pokemon_v2_pokemon(where: {id: {_eq: 64}}) {
    id
    pokemon_v2_pokemonmoves(limit: 20, offset: 0, distinct_on: move_id) {
      id
      level
      pokemon_v2_movelearnmethod {
        name
        pokemon_v2_versiongroupmovelearnmethods {
          pokemon_v2_versiongroup {
            name
            id
          }
          pokemon_v2_movelearnmethod {
            name
            pokemon_v2_movelearnmethoddescriptions(where: {language_id: {_eq: 9}}, limit: 1) {
              description
            }
          }
        }
      }
      pokemon_v2_move {
        accuracy
        move_effect_chance
        name
        priority
        pp
        power
        super_contest_effect_id
        type_id
        pokemon_v2_type {
          name
          id
          pokemon_v2_movedamageclass {
            id
            name
          }
        }
        pokemon_v2_movemetum {
          crit_rate
          ailment_chance
          flinch_chance
          drain
          max_hits
          max_turns
          min_hits
          min_turns
          stat_chance
          pokemon_v2_movemetaailment {
            name
          }
          pokemon_v2_movemetacategory {
            name
          }
          healing
        }
        id
        pokemon_v2_machines(distinct_on: machine_number, order_by: {version_group_id: asc}) {
          machine_number
          pokemon_v2_versiongroup {
            name
          }
        }
        pokemon_v2_moveflavortexts(where: {language_id: {_eq: 9}}, limit: 1, order_by: {version_group_id: desc}) {
          flavor_text
        }
      }
    }
  }
}
3. See console throws SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

Expected :

The query to work or the correct error to be shown

**Comment by DigitalZebra** [comment]
Getting the same, even when running a very simple Pokemon query by ID:
```
query samplePokeAPIquery {
  pokemon_v2_pokemon_by_pk(id: 10) {
    name
  }
}
```

Looks like a 504/gateway timeout issue?

**Comment by DigitalZebra** [comment]
@martipello I think this is now resolved - I'm no longer getting the 504/syntax errors for the above queries. However, it looks like there's a different error with your query in particular.

**Comment by martipello** [comment]
Yh same, mark this resolved the issue was trying to get too much data
