### ISSUE TITLE
GraphQL API is missing Paldea data

### ISSUE THREAD

**Issue by timroesner** [PokeAPI/pokeapi#820]
Thanks so much for making this data and API available to us. 

For awhile I've been using the GraphQL API (https://beta.pokeapi.co/graphql/v1beta), and now that Scarlet / Violet are out I noticed that the Pokedex for the Paldea region is still missing from those endpoints.

As I understand from the commits here that data is already available through the REST API.

**Comment by Naramsim** [comment]
yep, when we'll finish merging data I'll update the GQL

**Comment by LRasile** [comment]
Thanks for setting API up. 

Any expected ETA on this I would rather stay using the GraphQL API rather than rewrite my code to do the rest calls.

**Comment by Naramsim** [comment]
we have updated the data
