### ISSUE TITLE
German Translations for Sprigatito and Floragato

### ISSUE THREAD

**Issue by BelaDerDev** [PokeAPI/pokeapi#827]
Of every Pokémon, there is the German name available, except for Sprigatito and Floragato.
https://pokeapi.co/api/v2/pokemon-species/sprigatito
https://pokeapi.co/api/v2/pokemon-species/floragato

In German, Sprigatito is called "Felori" and Floragato is called "Feliospa".

**Comment by Naramsim** [comment]
hi, could you fix this and submit a PR?

**Comment by jalajk24** [comment]
Can I work on this? I am pretty new to this

**Comment by Naramsim** [comment]
Of course! It should be a matter of renaming the pokemon name in a CSV file

**Comment by helblingjoel** [comment]
This has been addressed with the MR above and should now be resolved
