### ISSUE TITLE
Evolution chain is null for paldea (generation IX) pokemons species

### ISSUE THREAD

**Issue by arix2000** [PokeAPI/pokeapi#837]
For example: 
https://pokeapi.co/api/v2/pokemon-species/sprigatito
https://pokeapi.co/api/v2/pokemon-species/fidough

**Comment by Naramsim** [comment]
yes, we are aware. Would you be willing to help us fixing it?

**Comment by helblingjoel** [comment]
This has been fixed now, no? I found it a nice surprise when they suddenly started working 😄

**Comment by SKCwillie** [comment]
This looks like this has been taken care of and can be closed out.
