### ISSUE TITLE
Pokemon name for "deoxys" is inconsistent

### ISSUE THREAD

**Issue by diduseetheocean** [PokeAPI/pokeapi#838]
**Example:**
I want to display all pokemons from the pokedex hoenn with the api-v2.

**Current Behavior:**
Endpoint **pokedex/15** returns the pokedex **updated-hoenn** and inside **pokemon_entries** deoxys is listet with name **deoxys**.
Fetching the endpoint **pokemon** to search for **deoxys** returns **404 not found** because here the pkmn is listet under **deoxys-normal**.

This makes it necessary after getting the pokemon-entries from a **pokedex**, searching first inside the **pokemon-species** endpoint to get the **national-dex-id** and than search via this id inside the **pokemon-endpoint** to get the desired information. 
So I have one more request than expected.

**Expectation**:
Fetching the endpoint **pokemon** to search for **deoxys** returns the resource for **deoxys**.

In my current understanding the prefix **-normal** should not be needed. Maybe I don't understand something.

**Comment by Naramsim** [comment]
Hi, we decided that way. Basically many Deoxys `pokemon` exist. One has an `id` below 10000, the others have an `id` above 10000. So the correct way would be to query `pokemon-species` first, select which deoxys you'd like to have, then query the exact `pokemon`.
