### ISSUE TITLE
CORS error in GraphQL API

### ISSUE THREAD

**Issue by ottonielmatheus** [PokeAPI/pokeapi#842]
Hi guys,

When acessing GraphQL API from my local client, I get CORS error, probably Allow Origin header is missing. 

![image](https://user-images.githubusercontent.com/37461352/217813492-674cf1d9-d4b6-415f-8b4c-31d0c66f5289.png)

Steps to Reproduce:

1. Try a request from another origin to https://beta.pokeapi.co/graphql/console/.

**Comment by brunoenribeiro** [comment]
I believe the endpoint should be https://beta.pokeapi.co/graphql/v1beta.

Anyways, I facing the same issue, even when making calls to that endpoint. It was working yesterday.

![image](https://user-images.githubusercontent.com/3811141/217831142-094d0833-bb7c-42d9-9044-780332677841.png)

**Comment by ottonielmatheus** [comment]
> I believe the endpoint should be https://beta.pokeapi.co/graphql/v1beta.
> 
> Anyways, I facing the same issue, even when making calls to that endpoint. It was working yesterday.
> 
> ![image](https://user-images.githubusercontent.com/3811141/217831142-094d0833-bb7c-42d9-9044-780332677841.png)

I tried https://beta.pokeapi.co/graphql/v1beta before, but got 502 error as it happened to you in your example.

I think they migrated from the server, changed the link but some settings were missing. :thinking:

**Comment by brunoenribeiro** [comment]
Maybe developers don't like brazilians anymore :brazil: :rofl:

**Comment by brunoenribeiro** [comment]
Just for completion, here's my request made from VS Code's ThunderClient extension.

**Headers:**
![image](https://user-images.githubusercontent.com/3811141/217835249-861e89b0-7b76-43a8-9e74-ddc5e61156ef.png)

**Body:** (it's the API Explorer's default query)
![image](https://user-images.githubusercontent.com/3811141/217835582-1b15f048-c3eb-4c0a-b47c-647c189fbc57.png)

**Comment by brunoenribeiro** [comment]
It's working again :rocket: 

![image](https://user-images.githubusercontent.com/3811141/217883676-78b5dc8f-902d-464d-b84f-14008deb13f4.png)

**Comment by Naramsim** [comment]
I was updating the data

**Comment by mugnimaestra** [comment]
> I was updating the data

It's been 3 weeks and I still having the host error

**Comment by Naramsim** [comment]
We are down right now

**Comment by blevy115** [comment]
I'm getting the same issue now, seems to also be broken in the https://beta.pokeapi.co/graphql/console/ in my browser
