### ISSUE TITLE
Add Evolution chain details

### ISSUE THREAD

**Issue by FallenDeity** [PokeAPI/pokeapi#844]
Currently Evolution details dont include reigonal forms in the data those should be added for more clear information. Also some evolution details are missing such as one for rockruff where it shows details for all evolution forms and conditions but states only lycanroc in evolved species when it should be stating dusk midnight etc so I think a round if data validation is needed.

**Comment by FallenDeity** [comment]
ok so after a bit of analysis and tiny bit of hardcoding i figured out an algorithm to get all branched evolutions as listed with reigonal and form support except the ones in which api lacks the data. the algorithm works on depth nesting of the evolution chain data and fetching the corresponding form from the pokemon species variety
https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_with_branched_evolutions
so hardcoded bit is the slowbro data where mega appears in depth where galar needs to be and also api lacks data for the following
- all reigonal forms as mentioned in the bulbapedia link exeggcute onwards
- toxel / toxtricity needs another level of nesting for low-key / amped

**Comment by helblingjoel** [comment]
I'm not sure if this is something that could be supported first party?

Like you say, data is present in some places where altered forms are listed in "Forms" or "Varieties". I imagine the difficulty with this is that those forms will depend on the game.
The evolution chains, as they are at the moment, link Pokémon species to each other.

Personally, I would rather the API sticks to this single definition of truth and the forms and varieties are for the consumers to figure out. That being said, it would be helpful if `pokemon-forms` would have a key to describe the game of their first appearance (i.e. for Alolan Wooper).

**Comment by FallenDeity** [comment]
I am not talking about forms and varieties only few reigonal variants like alola and galar where mon has different sprite and evolution also some evolution chains are complete like meowth accounts for perrserker and persian alola i dont see any reason why some mon like exxegcute cannot have it cause the evolution chain exists its part of it even in bulbapedia

**Comment by FallenDeity** [comment]
Solved this issue a while back with a custom evolution chain parser script can be found [here](https://github.com/FallenDeity/PokeLance/blob/master/examples/evolutions.py) and the exported resolved evolution chain [here](https://github.com/FallenDeity/PokeLance/blob/master/examples/evolutions.json)

**Comment by drohack** [comment]
Here's a full list of the evolution chains for pokeapi
https://pastebin.com/ekhYUQKA
I just edited FallenDeity's code a little to generate this. But the example.json they have doesn't actually have all of the pokemon. And their names are not exactly the same as what pokeapi expects. (for example the evolution.json would return "meowstic" instead of "meowstic-male" and "meowstic-female", which are 2 different variants/pokemon in pokeapi).

**Comment by FallenDeity** [comment]
> Here's a full list of the evolution chains for pokeapi
> https://pastebin.com/ekhYUQKA
> I just edited FallenDeity's code a little to generate this. But the example.json they have doesn't actually have all of the pokemon. And their names are not exactly the same as what pokeapi expects. (for example the evolution.json would return "meowstic" instead of "meowstic-male" and "meowstic-female", which are 2 different variants/pokemon in pokeapi).

Hey that's pretty cool, would you mind sharing the updated script here or make a pr to the pokelance repo.

**Comment by drohack** [comment]
> Hey that's pretty cool, would you mind sharing the updated script here or make a pr to the pokelance repo.

Here's the changes from the /examples/evolutions.py to generate the evolutions.json

```
def match_variety(name: str) -> bool:
    if len(name.split("-")) > 1:
        return not any(i in name for i in INVALID_FORMS)
    return False

async def main() -> None:
    client = PokeLance(cache_endpoints=True)
    await client.wait_until_ready()
    
    # Fetch all Pokémon if not cached
    if not client.pokemon.all_pokemons:
        for i in range(1, 1000000):  # Adjust the range as needed
            try:
                await client.pokemon.fetch_pokemon(i)
            except Exception as e:
                print(f"Error fetching Pokémon with ID {i}: {e}")
    
    all_pokemons = client.pokemon.all_pokemons

    if all_pokemons:
        pokemon_json = json.dumps(all_pokemons)
        print(pokemon_json)
    
    branched = all_pokemons
    strings = []
    processed_pokemon = set()
    failed = []
    for pokemon in branched:
        if pokemon in processed_pokemon:
            continue
        try:
            species: PokemonSpecies = await client.pokemon.fetch_pokemon_species(pokemon)
            evolution_chain: EvolutionChain = await client.from_url(species.evolution_chain.url)
            evo_data, detail_data = get_evolutions(evolution_chain)
            variety_data = {}
            for k in evo_data.keys():
                varieties = (await client.pokemon.fetch_pokemon_species(k)).varieties
                default = [i.pokemon.name for i in varieties if i.is_default][0]
                forms = [i.pokemon.name for i in varieties if not i.is_default and match_variety(i.pokemon.name)]
                if forms:
                    variety_data[k] = [default] + forms
            full_evolution_data = converge_data(evo_data, detail_data, variety_data)
            strings.append(json.dumps(full_evolution_data, indent=4))
            processed_pokemon.update(full_evolution_data.keys())
        except Exception as e:
            print(f"Error fetching evolution data for {pokemon}: {e}")
            failed.append(pokemon)
            continue
    with open("evolutions.json", "w") as f:
        f.write("[" + ",\n".join(strings) + "]")
    await client.close()
    print(f"Failed to fetch evolution data for: {failed}")
    print(f"Failed size: {len(failed)}")
```
I wasn't sure the best way to get all of the pokemon in one list in your code, so I just cached all of them?

Also with this code I'm getting this error:
Error fetching evolution data for slowpoke: list index out of range
Error fetching evolution data for slowbro: list index out of range
Error fetching evolution data for slowking: list index out of range

Not sure why just those 3. So I had to manually add those to the json. Here's the updated.
https://pastebin.com/vw5mqiDr

**Comment by FallenDeity** [comment]
Oh I see thats how you mean it, yeah my evolution script was generating only branch and evolution variants based this list here https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_with_branched_Evolutions, also `cache_endpoints` actually just makes a list of all possible routes for say example /pokemon, so if you ever pass a wrong parameter path say /pokemon/piiiikachu it will send you an informative error message with like did you mean pikachu?

```
import asyncio

from pokelance import PokeLance

client = PokeLance()

async def main() -> None:
    await client.ping()
    await asyncio.sleep(10)
    pikachu = await client.pokemon.fetch_pokemon("pikachu")
    try:
        pikachu = await client.pokemon.fetch_pokemon("pikach")
    except Exception as e:
        print(e)
    return None


asyncio.run(main())
```
```
Resource not found. Did you mean pikachu, pichu, pikachu-phd, pikachu-gmax, pikachu-libre, pikachu-belle, pancham, jirachi, trapinch, rapidash? | <Route endpoint=/pokemon/pikach method=GET> | 404
```
Cache size is also by default 100 iirc as the docs mention you need to change that to allow caching of more items at a time, otherwise it evicts the first item added to the cache.

Also on a side not i checked your pastebin link it isnt actually accurate since it shows arbitray megas and forms for example aegislash and ivysaur to venusaur mega, frogadier into greninja ash, battle bond and so on. I checked out the script and fixed it to work with male and female too here you go https://github.com/FallenDeity/PokeLance/blob/master/examples/evolutions.py
also generated the json for all the cases i found on bulba and other edge cases for regression testing

**Comment by drohack** [comment]
Crosspost to: https://github.com/FallenDeity/PokeLance/issues/53
