### ISSUE TITLE
Pokemon Stats are wrong for older versions of the game

### ISSUE THREAD

**Issue by MetalKid** [PokeAPI/pokeapi#850]
I think around Gen 6 & 7, some Pokemon base stats changed slightly to make some Pokemon more competitive.  For example, Pikachu's base defense went from 30 to 40.  However, that fact is completely glossed over in the raw data files.  Thus, if anyone tried to use these stats to IV calculations from older games, they would be wrong.  Is the intent to completely ignore these changes? If not, then the structure of this data would need to change significantly or have some weird changelog of the base stats, I guess.

**Comment by Naramsim** [comment]
Yeah, right now we are ignoring those changes. We are keeping only the latest data
