### ISSUE TITLE
Paldea Evolution Chains are Missing

### ISSUE THREAD

**Issue by Ratismal** [PokeAPI/pokeapi#865]
All of Paldea's evolution chains are broken in the API. The data for most of them exists in the CSV files, but some is also missing from there as well.

Steps to Reproduce:
1. Go to <https://pokeapi.co/api/v2/evolution-chain/478> (Sprigatito's evolution chain) - get a 404
2. Go to <https://pokeapi.co/api/v2/pokemon-species/906> (Sprigatito's species) - evolution_chain is null

Some of the evolution chains in <https://github.com/PokeAPI/pokeapi/blob/master/data/v2/csv/pokemon_evolution.csv> are also missing, such as Baxcalibre's line.

**Comment by C-Garza** [comment]
Seems like it's working now for those two endpoints at least.
