### ISSUE TITLE
Paldea Pokedex endpoint is 404

### ISSUE THREAD

**Issue by elliebartling** [PokeAPI/pokeapi#866]
Steps to Reproduce:

1. Go to https://pokeapi.co/api/v2/pokedex/paldea — get a 404
2. Go to https://pokeapi.co/api/v2/pokedex — see Paldea is missing from the list

**Comment by C-Garza** [comment]
Hmm, I see that the endpoint is step 1 exists and is indeed Paldea, but the endpoint in step 2 is missing pokedex endpoints after id 21.

**Comment by Deleca7755** [comment]
@Naramsim resolved/stale Issue
