### ISSUE TITLE
Page 60 of 61 if Forbidden when using pagination

### ISSUE THREAD

**Issue by pbldmngz** [PokeAPI/pokeapi#882]
I've encountered this issue specifically on one of my paginated requests:

> `https://pokeapi.co/api/v2/pokemon?offset=1218&limit=21` is just fine.

> `https://pokeapi.co/api/v2/pokemon?offset=1239&limit=21` This raises 403 - Forbidden

> `https://pokeapi.co/api/v2/pokemon?offset=1260&limit=21` is just fine.

Basically I created pages of 21 elements, which gives me around 61 pages. Page 60 is the only one that it seems that I cannot access. Is there some secret Pokemon there or why could this be happening?

![image](https://user-images.githubusercontent.com/32307513/238962016-97677ba6-d8bd-4f8f-810c-3da065baad41.png)

This is the [consumer app](https://pbldmngz.github.io/react-typescript-pokemon-api-consumer/) I was toying around with when I found out:

_Originally posted by @pbldmngz in https://github.com/PokeAPI/pokeapi/issues/135#issuecomment-1551374609_

**Comment by Naramsim** [comment]
On my side i don't get your 403, so i think it's a rare cache problem. Could you wait a few days and update us?

**Comment by ddmuzyk** [comment]
I'm also receiving a 403 error (Forbidden) on some of the pokemon requests on my side - for example this one "https://pokeapi.co/api/v2/pokemon/yveltal" doesn't work. My site doesn't have a server, for the past month everything worked fine. It started happening yesterday.

**Comment by ddmuzyk** [comment]
Or did I receive a ban of some sort by the pokeApi

**Comment by phalt** [comment]
Hmmm where are you sending your API requests from? Cloudflare may be blocking you if you're sending a lot of requests.

**Comment by ddmuzyk** [comment]
From Poland, although now I reduced the number of requests to the API and I don't see the problem anymore, will see if it happens again. But it wasn't a cache problem I think cause I had the same issue when requesting on my phone.

**Comment by Gabb-c** [comment]
I'm also recieving some 403 in my tests:

![image](https://github.com/PokeAPI/pokeapi/assets/65926741/e7f6e03b-4b46-4224-b94a-f2ee16ac56f7)

Node: lts/hydrogen
OS: Ubuntu latest

**Comment by phalt** [comment]
In our security logs on Cloudflare I can see a significant number of blocked threats (in excess of 100,000 requests) from Colombia and Brazil. This is likely triggering Cloudflare to be extra sensitive for all traffic. We should double check firebase isn't setting off these 403's though just to be sure

**Comment by Naramsim** [comment]
Hmm, I modified some parameters in our function on GCP. Let's see if this changes something. Otherwise, the issue might be in the function's dependencies update I did the other day. 

If the issue doesn't resolve I'll roll back

**Comment by pbldmngz** [comment]
After several attempts over the days, this is what I know:
- The page that gets the `403 FORBIDDEN` seems random at first, but it's consistent at least for a few minutes
- I happens when I try to run through all the pages, so it might have to do as you say with some sort of limiter as I'm doing a lot of requests in a few seconds (60 requests for the pokemons, 21*60 for the sprites, all that from the same IP in 30 seconds)
- **I was no longer able to reproduce the issue today**

**Comment by PauliusRap** [comment]
I had similar situations to @pbldmngz :) but the situation seems to have been fixed or at least improved. Thanks!
