### ISSUE TITLE
mistake in pikachu /evolution-chain. 

### ISSUE THREAD

**Issue by MrchinFTW** [PokeAPI/pokeapi#888]
Hello!

in the evolution chain number 10 - in the evolution details of pikachu the trigger is level-up but min_level key is null and instead the min_happiness key has a value. 
maybe it need to be fixed by placing value in min_level or changing the of change the trigger.

**Comment by MrchinFTW** [comment]
excuse me but what PR means?

**Comment by Naramsim** [comment]
Pull request, a proposal for a change in the code/data
