### ISSUE TITLE
Multiple typos in romanized Japanese names of ninth-generation Pokémon

### ISSUE THREAD

**Issue by Vigentian** [PokeAPI/pokeapi#893]
There are several Pokémon whose trademarked Japanese names are inaccurate in `data/v2/csv/pokemon_species_names.csv`. These include:
#0911 Skeledirge - Trademarked name should be `Laudbon` rather than `Loudbone`.
#0917 Tarountula - Trademarked name should be `Tamantula` rather than `Tamanchura`.
#0918 Spidops - Trademarked name should be `Wanaider` rather than `Wanaidā`.
#0926 Fidough - Trademarked name should be `Pupimocchi` rather than `Papimocchi`.
#0928 Smoliv - Trademarked name should be `Minive` rather than `Minību`.
#0929 Dolliv - Trademarked name should be `Olinyo` rather than `Orīnyo`.
#0930 Arboliva - Trademarked name should be `Oliva` rather than `Orīva`.
#0933 Naclstack - Trademarked name should be `Jiodumu` rather than `Jiozumu`.
#0934 Garganacl - Trademarked name should be `Kyojiohn` rather than `Kyojiōn`.
#0939 Bellibolt - Trademarked name should be `Harabarie` rather than `Harabarī`.
#0943 Mabosstiff - Trademarked name should be `Mafitiff` rather than `Mafitifu`.
#0944 Shroodle - Trademarked name should be `Shirushrew` rather than `Shirushurū`.
#0945 Grafaiai - Trademarked name should be `Taggingru` rather than `Taginguru`.
#0951 Capsakid - Trademarked name should be `Capsaiji` rather than `Kapusaiji`.
#0952 Scovillain - Trademarked name should be `Scovillain` rather than `Sukoviran`.
#0954 Rabsca - Trademarked name should be `Beracas` rather than `Berakasu`.
#0956 Espathra - Trademarked name should be `Cuespatra` rather than `Kaesupatora` (which was misspelled to begin with; the correct romanization for the latter is `Kuesupatora`)
#0966 Revavroom - Trademarked name should be `Burororoom` rather than `Burororōmu`.
#0969 Glimmet - Trademarked name should be `Kirame` rather than `Kirāme`.
#0970 Glimmora - Trademarked name should be `Kiraflor` rather than `Kirafuroru`.
#0972 Houndstone - Trademarked name should be `Hakadog` rather than `Hakadoggu`.
#0975 Cetitan - Trademarked name should be `Hulkujira` rather than `Harukajira` (which was misspelled to begin with; the correct romanization for the latter is `Harukujira`)
#0976 Veluza - Trademarked name should be `Migalusa` rather than `Migarūsa`.
#0981 Farigiraf - Trademarked name should be `Rikikirin` rather than `Rikikirn`.
#0982 Dudunsparce - Trademarked name should be `Nokokocchi` rather than `Nokokotchi`.
#0984 Great Tusk - Trademarked name should be `Idainakiba` rather than `Idaina Kiba`.
#0987 Flutter Mane - Trademarked name should be `Habatakukami` rather than `Habtakukami`.
#0988 Slither Wing - Trademarked name should be `Chiwohauhane` rather than `Chiohauhane`.
#0997 Arctibax - Trademarked name should be `Segohru` rather than `Segōru`.
#1004 Chi-Yu - Trademarked name should be `Yiyui` rather than `Īyui`.

**Comment by Naramsim** [comment]
Hi, is this the same as https://github.com/PokeAPI/pokedex/issues/168 ?

**Comment by Vigentian** [comment]
Yes, it is essentially the same issue. However, I thought it would be helpful to open it here since this is the branch with the ninth-generation data and a full list of the necessary changes would make it easier to implement them.

**Comment by Naramsim** [comment]
Yes, actually it's better here. Would you also be able to submit a PR?

**Comment by Vigentian** [comment]
Yes, I can submit a pull request. I may need some time to set it up (forking, making the commit, submitting the request).
