### ISSUE TITLE
Missing data for distortion world location areas

### ISSUE THREAD

**Issue by truite-codeuse** [PokeAPI/pokeapi#904]
Hi ! There is no data for `areas` when calling the API on `https://pokeapi.co/api/v2/location/distortion-world/`. This implies that `giratina-origin` doesn't have any encounter data.

Steps to Reproduce:

1. Go to `https://pokeapi.co/api/v2/location/distortion-world` and see the empty `areas` array
2. Go to `https://pokeapi.co/api/v2/pokemon/giratina-origin/encounters/`, there is no data provided

**Comment by Naramsim** [comment]
yeah, we lack that data :(

**Comment by truite-codeuse** [comment]
Thanks for your answer ! :c do you know if it will be added in the future ?

**Comment by Naramsim** [comment]
Eh, its gonna be tough. We currently rely on individual contributors. We don't have time to update by ourselves the data

**Comment by truite-codeuse** [comment]
I see... thank you for all the work you make on this project, hope someone will gather the data someday (copium) !
