### ISSUE TITLE
csv dataset too big to view all

### ISSUE THREAD

**Issue by ollyhb** [PokeAPI/pokeapi#913]
I am trying to retrieve moveset data. But it seems the dataset in pokemon_moves.csv chops off overflow data. I only get information down to alolan_raticate (id 10271)

Steps to Reproduce:

1. go to link https://github.com/PokeAPI/pokeapi/blob/master/data/v2/csv/pokemon_moves.csv
2. download, or view raw
3. Notice row counts

Is there an accessible source file that's bigger?

**Comment by Naramsim** [comment]
You can clone the repo locally and check the files out with VSCode
