### ISSUE TITLE
BDSP egg moves

### ISSUE THREAD

**Issue by penelopeysm** [PokeAPI/pokeapi#914]
Hello!

PokeAPI doesn't seem to have data on BDSP egg moves, as far as I can tell.

I could potentially put a PR together with some data scraped from PokemonDB (it might take me a while) — would you be interested in this?

**Comment by penelopeysm** [comment]
In fact, I guess there is just not much data on BDSP at all 😅 I guess this might be one place to start. I'm a bit more motivated to do this because it ties in with another project I'm doing, but I could possibly also look into adding more stuff (namely other parts of the learnset).

**Comment by Naramsim** [comment]
Hi! Of course we'd love you to contribute to our data 🙂🙂

Feel free to open a PR even though we won't be able to support you with your work. 

We will review it when it's ready
