### ISSUE TITLE
Data from GraphQL is not update

### ISSUE THREAD

**Issue by charlescyt** [PokeAPI/pokeapi#918]
Hi! I notice that the data from GraphQL and Rest api is not the same.
While I understand that GraphQL is still in beta, I would like to know how long it typically takes for the data from GraphQL to synchronise and align with the data from REST API.

For example, there is Italian translation for move 827 from Rest api, https://pokeapi.co/api/v2/move/827
```json
"language": {
"name": "it",
"url": "https://pokeapi.co/api/v2/language/8/"
},
"name": "Artigli Fatali"
```

But there is no Italian translation in the response from GraphQL
```
query moveQuery {
  pokemon_v2_move(where: {id: {_eq: 827}}) {
    id
    name
    pokemon_v2_movenames {
      language_id
      name
    }
  }
}
```

```json
{
  "data": {
    "pokemon_v2_move": [
      {
        "id": 827,
        "name": "dire-claw",
        "pokemon_v2_movenames": [
          {
            "language_id": 1,
            "name": "フェイタルクロー"
          },
          {
            "language_id": 4,
            "name": "克命爪"
          },
          {
            "language_id": 9,
            "name": "Dire Claw"
          },
          {
            "language_id": 11,
            "name": "フェイタルクロー"
          }
        ]
      }
    ]
  }
}
```

**Comment by Naramsim** [comment]
Yeah you're right. Right now we have to update the darà manually on gql. I haven't done it in a while. 

Will try next week.

**Comment by Naramsim** [comment]
hi, could you check again?

**Comment by charlescyt** [comment]
Hi! just run a few tests, seems like the data is updated. Thanks.

**Comment by alexanderjophus** [comment]
Sorry to ping on a closed issue, but looks like it's missing the latest data from SV DLC part 2.

Specifically, I'm trying to get pokemon by dex and type using this.
```graphql
query samplePokeAPIquery {
  pokemon_v2_pokemon(where: {_and: {pokemon_v2_pokemonspecy: {pokemon_v2_pokemondexnumbers: {pokemon_v2_pokedex: {name: {_eq: "paldea"}}}}, pokemon_v2_pokemontypes: {pokemon_v2_type: {name: {_eq: "ice"}}}}}) {
    name
    pokemon_v2_pokemontypes {
      pokemon_v2_type {
        name
      }
    }
  }
}
```

Swapping `paldea` for `blueberry` results in nothing found. Is that the same issue?
