### ISSUE TITLE
GraphQL is down

### ISSUE THREAD

**Issue by jmacboy** [PokeAPI/pokeapi#923]
Couldn´t join on slack, so throwing it here instead, sorry about that.
First thanks for all the hard work, your API is amazing and really complete.
I wanted to report that the graphql is down right now and we´re getting error 502 everytime from every client. It only works on the graphql console.
Also tried the docker version but couldn't compile using the master script.

**Comment by camposmichel** [comment]
I have the same problem.

**Comment by Naramsim** [comment]
We have a script that reboots the machine every 24h. Is it still down?

**Comment by jmacboy** [comment]
Thanks, it works again now
