### ISSUE TITLE
Ivy cudgel has wrong accuracy value

### ISSUE THREAD

**Issue by tillfox** [PokeAPI/pokeapi#925]
The move ivy cudgel has an accuracy value of 1100 in moves.csv. It should be changed to 100.

![image](https://github.com/PokeAPI/pokeapi/assets/15571805/7453dc2f-c8fa-479e-bc4a-4376d58c4c9f)

**Comment by Naramsim** [comment]
Hi, could you change that and submit a PR?

**Comment by tillfox** [comment]
> Hi, could you change that and submit a PR?

Hi, I've done, but I forgot to assign reviewers. Tell me if it's ok.
