### ISSUE TITLE
Moves missing 'stat_changes' entries

### ISSUE THREAD

**Issue by joelesbennett** [PokeAPI/pokeapi#950]
Stockpile, Memento, Defog and Shell Smash are all missing stat_changes. Since these moves all result in stat changes on every use (barring if stats are at max or min modifier), seems like this data could be present but perhaps this is deliberately not there?

**Comment by Naramsim** [comment]
Could you help us and fill in the missing data into our CSV files? Thanks!

**Comment by JintoYamanaka** [comment]
@Naramsim @joelesbennett 
Hi.
I too noticed that "stat_changes" in "Shell Smash" is empty and just want to fix it.

May I fix it all together?

**Comment by Naramsim** [comment]
Go for it

**Comment by joelesbennett** [comment]
Hi both,

Sorry I missed the replies! @JintoYamanaka sounds good, I was unlikely to get to it in the next couple days now anyway!

Thanks!

**Comment by JintoYamanaka** [comment]
I have created Pull Request in response to this issue. 
I would appreciate it if you could consider reviewing and merging it.

**Comment by Naramsim** [comment]
Hi is the issue solved?

**Comment by JintoYamanaka** [comment]
Hi, I've confirmed that the fixes have been reflected in the production environment. 
I'm unable to close this issue, so could you close it? Thank you.
