### ISSUE TITLE
Sprite images return a bad url

### ISSUE THREAD

**Issue by Cova-ops** [PokeAPI/pokeapi#952]
I'm submitting a issue with the POKEAPI. (e.g. https://pokeapi.co/api/v2/pokemon/ditto) the URLs in the "sprites" section return incorrect values. You can verify this on the official website.

Example:
![Example](https://github.com/PokeAPI/pokeapi/assets/54122783/1ceda360-9f6d-4b78-ada7-9e2923e847a3)

I suspect this issue is related to the following [PR](https://github.com/PokeAPI/pokeapi/commit/ca8a3a6a07fb200e6b5ba7095fd43cac1d0d8876)

The problem is that the URLs in the "sprites" section are incorrect, as shown below:
`
"sprites": {
  "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/132.png",
  "back_female": null,
}
`

**Comment by lazy-goose** [comment]
Сonfirm that all sprite links except `https://pokeapi.co/api/v2/pokemon/ditto` are broken.

**Comment by Naramsim** [comment]
I'm very sorry. We rolled back to an earlier version.

**Comment by caiangums** [comment]
I was about to open an issue with the same reason 😅 

Do you have a plan to fix this? Do you need any help @Naramsim?

**Comment by CalebeCopello** [comment]
It's happening here too, but not all the time, sometimes it returns the correct url, but sometimes it returns the "double" url

**Comment by Cova-ops** [comment]
Hi, I have cleared my local cache and retested the website. It appears that the issue has been resolved, and everything is working as expected now.

I'm closing the issue.
