### ISSUE TITLE
Adding a showdown field for animated sprites to pokemon

### ISSUE THREAD

**Issue by FallenDeity** [PokeAPI/pokeapi#977]
This regarding this [pr](https://github.com/PokeAPI/sprites/pull/105) that was merged which added showdown/animated sprites to the sprites repository so i think it would be nice to have a showdown or animated field in the pokemon data resource as well which points to these sprites

#978 here is a pr for the proposed change

@Naramsim do take a look when you're free 😄

**Comment by Naramsim** [comment]
Hi! I'll review everything in a couple of days. I'm coming back from a trip and don't have time now

**Comment by FallenDeity** [comment]
completed with #978
