### ISSUE TITLE
Adding pokemon cries to the api

### ISSUE THREAD

**Issue by FallenDeity** [PokeAPI/pokeapi#982]
In relation to this super ancient issue https://github.com/PokeAPI/pokeapi/issues/242 I think it would be a great idea to have pokemon cries in the api 

I am willing to work on a pr for this just want to clear some doubts beforehand getting started, what would be preferred format for the sounds files (ogg, mp3, wav)?

@Naramsim any thoughts about this?

**Comment by Naramsim** [comment]
Give me some days to think about it.

Questions: do we have all the cries? Could we serve the original file type or is it better to convert them for quality/portability reasons?

**Comment by FallenDeity** [comment]
ogg and mp3 is readily available (veekun and showdown) for wavs they are also available on showdown but size is quite a bit bigger i am not professional with audio stuff perhaps someone experienced could differentiate between quality

**Comment by Naramsim** [comment]
Are there multiple sounds for each game version? Should we do a similar thing as we did for the sprites?

**Comment by Naramsim** [comment]
We should also make sure those sounds are playable if we serve them. Ideally we will host them in a separate repo and the like will be something like https://raw.githubusercontent.com/PokeAPI/cries/master/cries/pokemon/132.ogg. Maybe you can create a test repo with only one sprite and reference it in an HTML page to see if it plays.

**Comment by FallenDeity** [comment]
> Are there multiple sounds for each game version? Should we do a similar thing as we did for the sprites?

Its not game wise completely old games upto gen 5 had a different sound available and from pokemon xy the old sounds have been replaced with new ones for most Pokemon. So there are 2 sounds available for Pokemon upto gen 5

Also html supports
- mp3
- wav
- ogg
For in browser playing

**Comment by FallenDeity** [comment]
> Ok, let's use ogg! I'll make a new repo and we can start using that one. We can use the same tree we are using for the sprites. So something like:
> 
> ```
> /cries/pokemon/versions/generation-i/1.ogg
> /cries/pokemon/other/...
> ```
> 
> We can add only one generation only initially and build the code API-wise.

I am working on this pr rn ran into an issue mainly is that pokemon cries upto gen 5 is same for all games going forward from gen 6 the cries were revised so essentially there are only two sets of cries `old set (gen 1 - gen 5)` and `revised set (gen 1 - gen 9)` so if we are making it generation wise wont a lot of tracks be repeated?

**Comment by FallenDeity** [comment]
https://veekun.com/dex/media/pokemon/cries/
 Veekun for old ones
https://play.pokemonshowdown.com/audio/cries/
showdown for newer ones
https://drive.google.com/drive/folders/1-1gquXnADe9fdQ7GDM0wFGIV36_O_g3L?usp=sharing (these are a few other i took and converted to compare quality)

**Comment by Naramsim** [comment]
I listened to them (bulbasaur) and they all differ. Let's use the most recent and complete set and add those only for now

**Comment by FallenDeity** [comment]
sure

**Comment by FallenDeity** [comment]
Complete with pr #1030
