### ISSUE TITLE
Image Links require VPN to load image

### ISSUE THREAD

**Issue by nayeemsama2000** [PokeAPI/pokeapi#985]
Hii,

I'm currently developing a pokedex app and facing an issue.

All the links of images are not working for me. They used to work before few days ago. But now it's not working. 
I have to use VPN to load the images now.

Is something wrong from my side? Or there's issue in API itself.

I'm from India BTW

**Comment by Naramsim** [comment]
Hi, your provider might be blocking the domain where we host the images. Rawgithubusercontent

**Comment by Naramsim** [comment]
The best is to clone the repo and serve the images by yourself
