### ISSUE TITLE
Add learnset introduced since Indigo Disk

### ISSUE THREAD

**Issue by giginet** [PokeAPI/pokeapi#987]
`data/pokemon_moves` data has not been updated which changed since Indigo Disk.

**Comment by giginet** [comment]
@penelopeysm Hi. I appreciate your help updating the learnset of the previous DLC.

Do you have any plan to update the learnset of Indigo Disk?

You said you have a script to generate CSV from other data sources.
If you have spare time. it's great to use the tool again.

If it's difficult to update the data, I'll try to prepare the data by implementing my new script. Thank you.

**Comment by penelopeysm** [comment]
Hi, @giginet! Happy New Year!

I think my scripts should all still work. I'm a little busy right now but in 1 or 2 days' time I can get to it, if that's alright? 🙂

**Comment by giginet** [comment]
Sure. I’m grad to hear you can help us.

If there are something to help you, feel free ask me 😊

**Comment by giginet** [comment]
@penelopeysm Sorry, I found more issues with your data.

Some legendary Pokémon introduced in this DLC were wrong.
(Suicune, Entei, Latios, or any other legendary)

They seem to have the same issue in this comment.
https://github.com/PokeAPI/pokeapi/pull/999#issuecomment-1890327974

Could you check this again? Thank you.

**Comment by giginet** [comment]
@penelopeysm I created an issue about the above problem.

Please help us again 🙇 🙏 
https://github.com/PokeAPI/pokeapi/issues/1006
